-- Generated by ratel schema
-- DO NOT EDIT

CREATE TABLE IF NOT EXISTS currency (
  code TEXT PRIMARY KEY,
  name TEXT
);
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  email TEXT UNIQUE,
  full_name TEXT,
  is_active BOOLEAN DEFAULT true
);
CREATE TABLE IF NOT EXISTS categories (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  name TEXT,
  slug TEXT UNIQUE,
  parent_id BIGINT NULL
);
CREATE TABLE IF NOT EXISTS tags (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  name TEXT,
  slug TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS products (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  sku TEXT UNIQUE,
  name TEXT,
  price DOUBLE PRECISION,
  currency TEXT,
  stock_qty INTEGER DEFAULT 0,
  is_deleted BOOLEAN DEFAULT false
);
CREATE TABLE IF NOT EXISTS orders (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  user_id BIGINT,
  status TEXT DEFAULT 'NEW',
  currency TEXT
);
CREATE TABLE IF NOT EXISTS order_items (
  order_id BIGINT,
  line_no INTEGER,
  product_id BIGINT,
  qty INTEGER,
  unit_price DOUBLE PRECISION
);
