// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: examples/proto/store.proto

package storepb

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	_ "github.com/yaroher/ratel/ratelproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntityID - базовый type alias для ID сущностей
type EntityID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityID) Reset() {
	*x = EntityID{}
	mi := &file_examples_proto_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityID) ProtoMessage() {}

func (x *EntityID) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityID.ProtoReflect.Descriptor instead.
func (*EntityID) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{0}
}

func (x *EntityID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ============================================================================
// Timestamps - embedded message для created_at/updated_at
// ============================================================================
type Timestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamps) Reset() {
	*x = Timestamps{}
	mi := &file_examples_proto_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps) ProtoMessage() {}

func (x *Timestamps) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps.ProtoReflect.Descriptor instead.
func (*Timestamps) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{1}
}

func (x *Timestamps) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timestamps) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ============================================================================
// BaseEntity - базовая сущность с ID и timestamps (nested embed)
// ============================================================================
type BaseEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *EntityID              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamps    *Timestamps            `protobuf:"bytes,2,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEntity) Reset() {
	*x = BaseEntity{}
	mi := &file_examples_proto_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEntity) ProtoMessage() {}

func (x *BaseEntity) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEntity.ProtoReflect.Descriptor instead.
func (*BaseEntity) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{2}
}

func (x *BaseEntity) GetId() *EntityID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BaseEntity) GetTimestamps() *Timestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// ============================================================================
// Currency - справочник валют (не использует BaseEntity)
// ============================================================================
type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_examples_proto_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{3}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ============================================================================
// User - пользователь системы (с BaseEntity)
// ============================================================================
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedded BaseEntity (id + timestamps)
	Base     *BaseEntity `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Email    string      `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName string      `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	IsActive bool        `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Nullable via proto3 optional on Timestamp
	EmailConfirmedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=email_confirmed_at,json=emailConfirmedAt,proto3,oneof" json:"email_confirmed_at,omitempty"`
	// Nullable via proto3 optional on scalar
	Nickname *string `protobuf:"bytes,6,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	// Nullable via proto3 optional on Timestamp
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// OneToMany: User has many Orders
	Orders []*Order `protobuf:"bytes,10,rep,name=orders,proto3" json:"orders,omitempty"`
	// HasOne: User has one Profile
	Profile       *Profile `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_examples_proto_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetBase() *BaseEntity {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetEmailConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailConfirmedAt
	}
	return nil
}

func (x *User) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *User) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// ============================================================================
// Profile - профиль пользователя (один к одному с User)
// ============================================================================
type Profile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedded BaseEntity (id + timestamps)
	Base      *BaseEntity `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId    *EntityID   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // FK to users.id (unique - one profile per user)
	Bio       string      `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	AvatarUrl string      `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// BelongsTo: Profile belongs to User
	User          *User `protobuf:"bytes,10,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_examples_proto_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{5}
}

func (x *Profile) GetBase() *BaseEntity {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Profile) GetUserId() *EntityID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Profile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Profile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Profile) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// ============================================================================
// Category - категория товаров (с BaseEntity)
// ============================================================================
type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedded BaseEntity (id + timestamps)
	Base          *BaseEntity            `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId      *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // nullable self-referencing FK
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_examples_proto_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{6}
}

func (x *Category) GetBase() *BaseEntity {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetParentId() *wrapperspb.Int64Value {
	if x != nil {
		return x.ParentId
	}
	return nil
}

// ============================================================================
// Tag - тег для товаров (с BaseEntity)
// ============================================================================
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedded BaseEntity (id + timestamps)
	Base          *BaseEntity `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name          string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string      `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_examples_proto_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{7}
}

func (x *Tag) GetBase() *BaseEntity {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// ============================================================================
// Product - товар (с BaseEntity)
// ============================================================================
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedded BaseEntity (id + timestamps)
	Base      *BaseEntity `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Sku       string      `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name      string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price     float64     `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency  string      `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"` // FK to currency.code
	StockQty  int32       `protobuf:"varint,6,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"`
	IsDeleted bool        `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// ManyToMany: Product has many Categories
	Categories []*Category `protobuf:"bytes,10,rep,name=categories,proto3" json:"categories,omitempty"`
	// ManyToMany: Product has many Tags
	Tags          []*Tag `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_examples_proto_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{8}
}

func (x *Product) GetBase() *BaseEntity {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

func (x *Product) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Product) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ============================================================================
// Order - заказ (с BaseEntity)
// ============================================================================
type Order struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedded BaseEntity (id + timestamps)
	Base     *BaseEntity `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	UserId   *EntityID   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // FK to users.id
	Status   string      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Currency string      `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // FK to currency.code
	// OneToMany: Order has many OrderItems
	Items []*OrderItem `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	// BelongsTo: Order belongs to User
	User *User `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	// BelongsTo: Order belongs to Currency
	Money         *Currency `protobuf:"bytes,12,opt,name=money,proto3" json:"money,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_examples_proto_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{9}
}

func (x *Order) GetBase() *BaseEntity {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Order) GetUserId() *EntityID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Order) GetMoney() *Currency {
	if x != nil {
		return x.Money
	}
	return nil
}

// ============================================================================
// OrderItem - позиция заказа (без BaseEntity - композитный PK)
// ============================================================================
type OrderItem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrderId   *EntityID              `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // FK to orders.id
	LineNo    int32                  `protobuf:"varint,2,opt,name=line_no,json=lineNo,proto3" json:"line_no,omitempty"`
	ProductId *EntityID              `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // FK to products.id
	Qty       int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	UnitPrice float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	// BelongsTo: OrderItem belongs to Order
	Order *Order `protobuf:"bytes,10,opt,name=order,proto3" json:"order,omitempty"`
	// BelongsTo: OrderItem belongs to Product
	Product       *Product `protobuf:"bytes,11,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_examples_proto_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{10}
}

func (x *OrderItem) GetOrderId() *EntityID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderItem) GetLineNo() int32 {
	if x != nil {
		return x.LineNo
	}
	return 0
}

func (x *OrderItem) GetProductId() *EntityID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *OrderItem) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderItem) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_examples_proto_store_proto protoreflect.FileDescriptor

const file_examples_proto_store_proto_rawDesc = "" +
	"\n" +
	"\x1aexamples/proto/store.proto\x12\x05store\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bratelproto/ratelproto.proto\x1a$examples/proto/goplain/goplain.proto\"*\n" +
	"\bEntityID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\"\xa8\x01\n" +
	"\n" +
	"Timestamps\x12H\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tcreatedAt\x12H\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tupdatedAt:\x06\x82\xa6\x1d\x02\b\x01\"z\n" +
	"\n" +
	"BaseEntity\x12)\n" +
	"\x02id\x18\x01 \x01(\v2\x0f.store.EntityIDB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\x02id\x129\n" +
	"\n" +
	"timestamps\x18\x02 \x01(\v2\x11.store.TimestampsB\x06\x82\xa6\x1d\x02 \x01R\n" +
	"timestamps:\x06\x82\xa6\x1d\x02\b\x01\"`\n" +
	"\bCurrency\x12(\n" +
	"\x04code\x18\x01 \x01(\tB\x14\x9a\xb5\x18\x10\x12\x0e\x10\x01*\n" +
	"code <> ''R\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name:\x16\x92\xb5\x18\f\b\x01\x12\bcurrency\x82\xa6\x1d\x02\b\x01\"\x96\x06\n" +
	"\x04User\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x11.store.BaseEntityB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12\x1e\n" +
	"\x05email\x18\x02 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12)\n" +
	"\tis_active\x18\x04 \x01(\bB\f\x9a\xb5\x18\b\x12\x06\x1a\x04trueR\bisActive\x12M\n" +
	"\x12email_confirmed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x10emailConfirmedAt\x88\x01\x01\x12\x1f\n" +
	"\bnickname\x18\x06 \x01(\tH\x01R\bnickname\x88\x01\x01\x12>\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tdeletedAt\x88\x01\x01\x127\n" +
	"\x06orders\x18\n" +
	" \x03(\v2\f.store.OrderB\x11\xa2\xb5\x18\r\n" +
	"\v\n" +
	"\auser_id\x18\x01R\x06orders\x129\n" +
	"\aprofile\x18\v \x01(\v2\x0e.store.ProfileB\x0f\xa2\xb5\x18\v\x1a\t\n" +
	"\auser_idR\aprofile:\x9f\x02\x92\xb5\x18\x94\x02\b\x01\x12\x05users*\t\x12\x05email\x18\x01*\x17\x12\tis_active\x12\n" +
	"created_atB\x05storeJ-ALTER TABLE {table} ENABLE ROW LEVEL SECURITYJkCREATE POLICY users_own_data ON {table} FOR ALL USING (id = current_setting('app.current_user_id')::bigint)JBCREATE POLICY users_insert ON {table} FOR INSERT WITH CHECK (true)\x82\xa6\x1d\x02\b\x01B\x15\n" +
	"\x13_email_confirmed_atB\v\n" +
	"\t_nicknameB\r\n" +
	"\v_deleted_at\"\xb3\x03\n" +
	"\aProfile\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x11.store.BaseEntityB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12D\n" +
	"\auser_id\x18\x02 \x01(\v2\x0f.store.EntityIDB\x1a\x9a\xb5\x18\x16\x12\x142\x05users:\x02id@\x01R\x05storeR\x06userId\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x120\n" +
	"\x04user\x18\n" +
	" \x01(\v2\v.store.UserB\x0f\xa2\xb5\x18\v\"\t\n" +
	"\auser_idR\x04user:\xcf\x01\x92\xb5\x18\xc4\x01\b\x01\x12\bprofiles*\v\x12\auser_id\x18\x01B\x05storeJ-ALTER TABLE {table} ENABLE ROW LEVEL SECURITYJsCREATE POLICY profiles_own_data ON {table} FOR ALL USING (user_id = current_setting('app.current_user_id')::bigint)\x82\xa6\x1d\x02\b\x01\"\xe7\x01\n" +
	"\bCategory\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x11.store.BaseEntityB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\x04slug\x18\x03 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x04slug\x12Y\n" +
	"\tparent_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueB\x1f\x9a\xb5\x18\x1b\x12\x192\n" +
	"categories:\x02id@\x02R\x05storeR\bparentId:\x1f\x92\xb5\x18\x15\b\x01\x12\n" +
	"categoriesB\x05store\x82\xa6\x1d\x02\b\x01\"z\n" +
	"\x03Tag\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x11.store.BaseEntityB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\x04slug\x18\x03 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x04slug:\x12\x92\xb5\x18\b\b\x01\x12\x04tags\x82\xa6\x1d\x02\b\x01\"\xeb\x03\n" +
	"\aProduct\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x11.store.BaseEntityB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12\x1a\n" +
	"\x03sku\x18\x02 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x124\n" +
	"\bcurrency\x18\x05 \x01(\tB\x18\x9a\xb5\x18\x14\x12\x122\bcurrency:\x04code@\x04R\bcurrency\x12&\n" +
	"\tstock_qty\x18\x06 \x01(\x05B\t\x9a\xb5\x18\x05\x12\x03\x1a\x010R\bstockQty\x12,\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bB\r\x9a\xb5\x18\t\x12\a\x1a\x05falseR\tisDeleted\x12;\n" +
	"\n" +
	"categories\x18\n" +
	" \x03(\v2\x0f.store.CategoryB\n" +
	"\xa2\xb5\x18\x06\x12\x04\x10\x01 \x01R\n" +
	"categories\x12*\n" +
	"\x04tags\x18\v \x03(\v2\n" +
	".store.TagB\n" +
	"\xa2\xb5\x18\x06\x12\x04\x10\x01 \x01R\x04tags:v\x92\xb5\x18l\b\x01\x12\bproducts\"\x16CHECK (stock_qty >= 0)*\x05\x12\x03sku*\n" +
	"\x12\bcurrency*,\x12\n" +
	"is_deleted\x12\n" +
	"created_at\"\x12is_deleted = falseB\x05store\x82\xa6\x1d\x02\b\x01\"\xa5\x05\n" +
	"\x05Order\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x11.store.BaseEntityB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12D\n" +
	"\auser_id\x18\x02 \x01(\v2\x0f.store.EntityIDB\x1a\x9a\xb5\x18\x16\x12\x142\x05users:\x02id@\x01R\x05storeR\x06userId\x12%\n" +
	"\x06status\x18\x03 \x01(\tB\r\x9a\xb5\x18\t\x12\a\x1a\x05'NEW'R\x06status\x124\n" +
	"\bcurrency\x18\x04 \x01(\tB\x18\x9a\xb5\x18\x14\x12\x122\bcurrency:\x04code@\x04R\bcurrency\x12:\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x10.store.OrderItemB\x12\xa2\xb5\x18\x0e\n" +
	"\f\n" +
	"\border_id\x18\x01R\x05items\x120\n" +
	"\x04user\x18\v \x01(\v2\v.store.UserB\x0f\xa2\xb5\x18\v\"\t\n" +
	"\auser_idR\x04user\x12=\n" +
	"\x05money\x18\f \x01(\v2\x0f.store.CurrencyB\x16\xa2\xb5\x18\x12\"\x10\n" +
	"\bcurrency\x12\x04codeR\x05money:\x9c\x02\x92\xb5\x18\x91\x02\b\x01\x12\x06orders\"9CHECK (status IN ('NEW', 'PAID', 'CANCELLED', 'SHIPPED'))*\t\x12\auser_id*\b\x12\x06status*\f\x12\n" +
	"created_atB\x05storeJ-ALTER TABLE {table} ENABLE ROW LEVEL SECURITYJqCREATE POLICY orders_own_data ON {table} FOR ALL USING (user_id = current_setting('app.current_user_id')::bigint)\x82\xa6\x1d\x02\b\x01\"\xba\x05\n" +
	"\tOrderItem\x12G\n" +
	"\border_id\x18\x01 \x01(\v2\x0f.store.EntityIDB\x1b\x9a\xb5\x18\x17\x12\x152\x06orders:\x02id@\x01R\x05storeR\aorderId\x12\x17\n" +
	"\aline_no\x18\x02 \x01(\x05R\x06lineNo\x12M\n" +
	"\n" +
	"product_id\x18\x03 \x01(\v2\x0f.store.EntityIDB\x1d\x9a\xb5\x18\x19\x12\x172\bproducts:\x02id@\x04R\x05storeR\tproductId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice\x124\n" +
	"\x05order\x18\n" +
	" \x01(\v2\f.store.OrderB\x10\xa2\xb5\x18\f\"\n" +
	"\n" +
	"\border_idR\x05order\x12<\n" +
	"\aproduct\x18\v \x01(\v2\x0e.store.ProductB\x12\xa2\xb5\x18\x0e\"\f\n" +
	"\n" +
	"product_idR\aproduct:\xd6\x02\x92\xb5\x18\xcb\x02\b\x01\x12\vorder_items\"\x13CHECK (line_no > 0)\"\x0fCHECK (qty > 0)2\x16\x12\border_id\x12\n" +
	"product_id:\x13\n" +
	"\border_id\n" +
	"\aline_noB\x05storeJ-ALTER TABLE {table} ENABLE ROW LEVEL SECURITYJ\xb0\x01CREATE POLICY order_items_own_data ON {table} FOR ALL USING (order_id IN (SELECT o.id FROM \"store\".\"orders\" o WHERE o.user_id = current_setting('app.current_user_id')::bigint))\x82\xa6\x1d\x02\b\x01B\xea\x01\x82\xb5\x18&CREATE EXTENSION IF NOT EXISTS pg_trgm\x82\xb5\x18\x8a\x01CREATE OR REPLACE FUNCTION store.set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$Z/github.com/yaroher/ratel/examples/proto/storepbb\x06proto3"

var (
	file_examples_proto_store_proto_rawDescOnce sync.Once
	file_examples_proto_store_proto_rawDescData []byte
)

func file_examples_proto_store_proto_rawDescGZIP() []byte {
	file_examples_proto_store_proto_rawDescOnce.Do(func() {
		file_examples_proto_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_proto_store_proto_rawDesc), len(file_examples_proto_store_proto_rawDesc)))
	})
	return file_examples_proto_store_proto_rawDescData
}

var file_examples_proto_store_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_examples_proto_store_proto_goTypes = []any{
	(*EntityID)(nil),              // 0: store.EntityID
	(*Timestamps)(nil),            // 1: store.Timestamps
	(*BaseEntity)(nil),            // 2: store.BaseEntity
	(*Currency)(nil),              // 3: store.Currency
	(*User)(nil),                  // 4: store.User
	(*Profile)(nil),               // 5: store.Profile
	(*Category)(nil),              // 6: store.Category
	(*Tag)(nil),                   // 7: store.Tag
	(*Product)(nil),               // 8: store.Product
	(*Order)(nil),                 // 9: store.Order
	(*OrderItem)(nil),             // 10: store.OrderItem
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil), // 12: google.protobuf.Int64Value
}
var file_examples_proto_store_proto_depIdxs = []int32{
	11, // 0: store.Timestamps.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: store.Timestamps.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: store.BaseEntity.id:type_name -> store.EntityID
	1,  // 3: store.BaseEntity.timestamps:type_name -> store.Timestamps
	2,  // 4: store.User.base:type_name -> store.BaseEntity
	11, // 5: store.User.email_confirmed_at:type_name -> google.protobuf.Timestamp
	11, // 6: store.User.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 7: store.User.orders:type_name -> store.Order
	5,  // 8: store.User.profile:type_name -> store.Profile
	2,  // 9: store.Profile.base:type_name -> store.BaseEntity
	0,  // 10: store.Profile.user_id:type_name -> store.EntityID
	4,  // 11: store.Profile.user:type_name -> store.User
	2,  // 12: store.Category.base:type_name -> store.BaseEntity
	12, // 13: store.Category.parent_id:type_name -> google.protobuf.Int64Value
	2,  // 14: store.Tag.base:type_name -> store.BaseEntity
	2,  // 15: store.Product.base:type_name -> store.BaseEntity
	6,  // 16: store.Product.categories:type_name -> store.Category
	7,  // 17: store.Product.tags:type_name -> store.Tag
	2,  // 18: store.Order.base:type_name -> store.BaseEntity
	0,  // 19: store.Order.user_id:type_name -> store.EntityID
	10, // 20: store.Order.items:type_name -> store.OrderItem
	4,  // 21: store.Order.user:type_name -> store.User
	3,  // 22: store.Order.money:type_name -> store.Currency
	0,  // 23: store.OrderItem.order_id:type_name -> store.EntityID
	0,  // 24: store.OrderItem.product_id:type_name -> store.EntityID
	9,  // 25: store.OrderItem.order:type_name -> store.Order
	8,  // 26: store.OrderItem.product:type_name -> store.Product
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_examples_proto_store_proto_init() }
func file_examples_proto_store_proto_init() {
	if File_examples_proto_store_proto != nil {
		return
	}
	file_examples_proto_store_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_proto_store_proto_rawDesc), len(file_examples_proto_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_proto_store_proto_goTypes,
		DependencyIndexes: file_examples_proto_store_proto_depIdxs,
		MessageInfos:      file_examples_proto_store_proto_msgTypes,
	}.Build()
	File_examples_proto_store_proto = out.File
	file_examples_proto_store_proto_goTypes = nil
	file_examples_proto_store_proto_depIdxs = nil
}
