// Code generated by protoc-gen-go-plain. DO NOT EDIT.
// source: examples/proto/store.proto

package storepb

import (
	ratelcast "github.com/yaroher/ratel/pkg/ratelcast"
	time "time"
)

// ============================================================================
//
//	Currency - справочник валют
//	============================================================================
type CurrencyScanner struct {
	Code string `json:"code"`
	Name string `json:"name"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Currency) IntoPlain() *CurrencyScanner {
	if pb == nil {
		return nil
	}
	p := &CurrencyScanner{}

	p.Code = pb.Code
	p.Src_ = append(p.Src_, 0)
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 1)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *CurrencyScanner) IntoPb() *Currency {
	if p == nil {
		return nil
	}
	pb := &Currency{}

	pb.Code = p.Code
	pb.Name = p.Name
	return pb
}

// ============================================================================
//
//	User - пользователь системы
//	============================================================================
type UserScanner struct {
	UserId    int64          `json:"userId"` // origin: type_alias, empath: user_id
	Email     string         `json:"email"`
	FullName  string         `json:"fullName"`
	IsActive  bool           `json:"isActive"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	Orders    []OrderScanner `json:"orders"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *User) IntoPlain() *UserScanner {
	if pb == nil {
		return nil
	}
	p := &UserScanner{}

	// UserId type alias from user_id
	if pb.GetUserId() != nil {
		p.UserId = pb.GetUserId().GetValue()
		p.Src_ = append(p.Src_, 0)
	}
	p.Email = pb.Email
	p.Src_ = append(p.Src_, 1)
	p.FullName = pb.FullName
	p.Src_ = append(p.Src_, 2)
	p.IsActive = pb.IsActive
	p.Src_ = append(p.Src_, 3)
	if pb.CreatedAt != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.CreatedAt)
		p.Src_ = append(p.Src_, 4)
	}
	if pb.UpdatedAt != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.UpdatedAt)
		p.Src_ = append(p.Src_, 5)
	}
	if len(pb.Orders) > 0 {
		p.Orders = make([]OrderScanner, len(pb.Orders))
		for i, v := range pb.Orders {
			if v != nil {
				p.Orders[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 6)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *UserScanner) IntoPb() *User {
	if p == nil {
		return nil
	}
	pb := &User{}

	// UserId type alias -> user_id
	{
		pb.UserId = &UserID{Value: p.UserId}
	}
	pb.Email = p.Email
	pb.FullName = p.FullName
	pb.IsActive = p.IsActive
	pb.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	pb.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	if len(p.Orders) > 0 {
		pb.Orders = make([]*Order, len(p.Orders))
		for i := range p.Orders {
			pb.Orders[i] = (&p.Orders[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	Category - категория товаров (с иерархией)
//	============================================================================
type CategoryScanner struct {
	CategoryId int64  `json:"categoryId"` // origin: type_alias, empath: category_id
	Name       string `json:"name"`
	Slug       string `json:"slug"`
	ParentId   int64  `json:"parentId"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Category) IntoPlain() *CategoryScanner {
	if pb == nil {
		return nil
	}
	p := &CategoryScanner{}

	// CategoryId type alias from category_id
	if pb.GetCategoryId() != nil {
		p.CategoryId = pb.GetCategoryId().GetValue()
		p.Src_ = append(p.Src_, 0)
	}
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 1)
	p.Slug = pb.Slug
	p.Src_ = append(p.Src_, 2)
	if pb.ParentId != nil {
		p.ParentId = ratelcast.Int64ValueToInt64(pb.ParentId)
		p.Src_ = append(p.Src_, 3)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *CategoryScanner) IntoPb() *Category {
	if p == nil {
		return nil
	}
	pb := &Category{}

	// CategoryId type alias -> category_id
	{
		pb.CategoryId = &CategoryID{Value: p.CategoryId}
	}
	pb.Name = p.Name
	pb.Slug = p.Slug
	pb.ParentId = ratelcast.Int64ToInt64Value(p.ParentId)
	return pb
}

// ============================================================================
//
//	Tag - тег для товаров
//	============================================================================
type TagScanner struct {
	TagId int64  `json:"tagId"` // origin: type_alias, empath: tag_id
	Name  string `json:"name"`
	Slug  string `json:"slug"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Tag) IntoPlain() *TagScanner {
	if pb == nil {
		return nil
	}
	p := &TagScanner{}

	// TagId type alias from tag_id
	if pb.GetTagId() != nil {
		p.TagId = pb.GetTagId().GetValue()
		p.Src_ = append(p.Src_, 0)
	}
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 1)
	p.Slug = pb.Slug
	p.Src_ = append(p.Src_, 2)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *TagScanner) IntoPb() *Tag {
	if p == nil {
		return nil
	}
	pb := &Tag{}

	// TagId type alias -> tag_id
	{
		pb.TagId = &TagID{Value: p.TagId}
	}
	pb.Name = p.Name
	pb.Slug = p.Slug
	return pb
}

// ============================================================================
//
//	Product - товар
//	============================================================================
type ProductScanner struct {
	ProductId  int64             `json:"productId"` // origin: type_alias, empath: product_id
	Sku        string            `json:"sku"`
	Name       string            `json:"name"`
	Price      float64           `json:"price"`
	Currency   string            `json:"currency"`
	StockQty   int32             `json:"stockQty"`
	IsDeleted  bool              `json:"isDeleted"`
	CreatedAt  time.Time         `json:"createdAt"`
	UpdatedAt  time.Time         `json:"updatedAt"`
	Categories []CategoryScanner `json:"categories"`
	Tags       []TagScanner      `json:"tags"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Product) IntoPlain() *ProductScanner {
	if pb == nil {
		return nil
	}
	p := &ProductScanner{}

	// ProductId type alias from product_id
	if pb.GetProductId() != nil {
		p.ProductId = pb.GetProductId().GetValue()
		p.Src_ = append(p.Src_, 0)
	}
	p.Sku = pb.Sku
	p.Src_ = append(p.Src_, 1)
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 2)
	p.Price = pb.Price
	p.Src_ = append(p.Src_, 3)
	p.Currency = pb.Currency
	p.Src_ = append(p.Src_, 4)
	p.StockQty = pb.StockQty
	p.Src_ = append(p.Src_, 5)
	p.IsDeleted = pb.IsDeleted
	p.Src_ = append(p.Src_, 6)
	if pb.CreatedAt != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.CreatedAt)
		p.Src_ = append(p.Src_, 7)
	}
	if pb.UpdatedAt != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.UpdatedAt)
		p.Src_ = append(p.Src_, 8)
	}
	if len(pb.Categories) > 0 {
		p.Categories = make([]CategoryScanner, len(pb.Categories))
		for i, v := range pb.Categories {
			if v != nil {
				p.Categories[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 9)
	}
	if len(pb.Tags) > 0 {
		p.Tags = make([]TagScanner, len(pb.Tags))
		for i, v := range pb.Tags {
			if v != nil {
				p.Tags[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 10)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *ProductScanner) IntoPb() *Product {
	if p == nil {
		return nil
	}
	pb := &Product{}

	// ProductId type alias -> product_id
	{
		pb.ProductId = &ProductID{Value: p.ProductId}
	}
	pb.Sku = p.Sku
	pb.Name = p.Name
	pb.Price = p.Price
	pb.Currency = p.Currency
	pb.StockQty = p.StockQty
	pb.IsDeleted = p.IsDeleted
	pb.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	pb.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	if len(p.Categories) > 0 {
		pb.Categories = make([]*Category, len(p.Categories))
		for i := range p.Categories {
			pb.Categories[i] = (&p.Categories[i]).IntoPb()
		}
	}
	if len(p.Tags) > 0 {
		pb.Tags = make([]*Tag, len(p.Tags))
		for i := range p.Tags {
			pb.Tags[i] = (&p.Tags[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	Order - заказ
//	============================================================================
type OrderScanner struct {
	OrderId   int64              `json:"orderId"` // origin: type_alias, empath: order_id
	UserId    int64              `json:"userId"`  // origin: type_alias, empath: user_id
	Status    string             `json:"status"`
	Currency  string             `json:"currency"`
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
	Items     []OrderItemScanner `json:"items"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Order) IntoPlain() *OrderScanner {
	if pb == nil {
		return nil
	}
	p := &OrderScanner{}

	// OrderId type alias from order_id
	if pb.GetOrderId() != nil {
		p.OrderId = pb.GetOrderId().GetValue()
		p.Src_ = append(p.Src_, 0)
	}
	// UserId type alias from user_id
	if pb.GetUserId() != nil {
		p.UserId = pb.GetUserId().GetValue()
		p.Src_ = append(p.Src_, 1)
	}
	p.Status = pb.Status
	p.Src_ = append(p.Src_, 2)
	p.Currency = pb.Currency
	p.Src_ = append(p.Src_, 3)
	if pb.CreatedAt != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.CreatedAt)
		p.Src_ = append(p.Src_, 4)
	}
	if pb.UpdatedAt != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.UpdatedAt)
		p.Src_ = append(p.Src_, 5)
	}
	if len(pb.Items) > 0 {
		p.Items = make([]OrderItemScanner, len(pb.Items))
		for i, v := range pb.Items {
			if v != nil {
				p.Items[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 6)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *OrderScanner) IntoPb() *Order {
	if p == nil {
		return nil
	}
	pb := &Order{}

	// OrderId type alias -> order_id
	{
		pb.OrderId = &OrderID{Value: p.OrderId}
	}
	// UserId type alias -> user_id
	{
		pb.UserId = &UserID{Value: p.UserId}
	}
	pb.Status = p.Status
	pb.Currency = p.Currency
	pb.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	pb.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	if len(p.Items) > 0 {
		pb.Items = make([]*OrderItem, len(p.Items))
		for i := range p.Items {
			pb.Items[i] = (&p.Items[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	OrderItem - позиция заказа
//	============================================================================
type OrderItemScanner struct {
	OrderId   int64   `json:"orderId"` // origin: type_alias, empath: order_id
	LineNo    int32   `json:"lineNo"`
	ProductId int64   `json:"productId"` // origin: type_alias, empath: product_id
	Qty       int32   `json:"qty"`
	UnitPrice float64 `json:"unitPrice"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *OrderItem) IntoPlain() *OrderItemScanner {
	if pb == nil {
		return nil
	}
	p := &OrderItemScanner{}

	// OrderId type alias from order_id
	if pb.GetOrderId() != nil {
		p.OrderId = pb.GetOrderId().GetValue()
		p.Src_ = append(p.Src_, 0)
	}
	p.LineNo = pb.LineNo
	p.Src_ = append(p.Src_, 1)
	// ProductId type alias from product_id
	if pb.GetProductId() != nil {
		p.ProductId = pb.GetProductId().GetValue()
		p.Src_ = append(p.Src_, 2)
	}
	p.Qty = pb.Qty
	p.Src_ = append(p.Src_, 3)
	p.UnitPrice = pb.UnitPrice
	p.Src_ = append(p.Src_, 4)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *OrderItemScanner) IntoPb() *OrderItem {
	if p == nil {
		return nil
	}
	pb := &OrderItem{}

	// OrderId type alias -> order_id
	{
		pb.OrderId = &OrderID{Value: p.OrderId}
	}
	pb.LineNo = p.LineNo
	// ProductId type alias -> product_id
	{
		pb.ProductId = &ProductID{Value: p.ProductId}
	}
	pb.Qty = p.Qty
	pb.UnitPrice = p.UnitPrice
	return pb
}
