// Code generated by protoc-gen-go-plain. DO NOT EDIT.
// source: examples/proto/store.proto

package storepb

import (
	ratelcast "github.com/yaroher/ratel/pkg/ratelcast"
	time "time"
)

// ============================================================================
//
//	Timestamps - embedded message для created_at/updated_at
//	============================================================================
type TimestampsScanner struct {
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Timestamps) IntoPlain() *TimestampsScanner {
	if pb == nil {
		return nil
	}
	p := &TimestampsScanner{}

	if pb.CreatedAt != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.CreatedAt)
	}
	if pb.UpdatedAt != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.UpdatedAt)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *TimestampsScanner) IntoPb() *Timestamps {
	if p == nil {
		return nil
	}
	pb := &Timestamps{}

	pb.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	pb.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	return pb
}

// ============================================================================
//
//	BaseEntity - базовая сущность с ID и timestamps (nested embed)
//	============================================================================
type BaseEntityScanner struct {
	Id        int64     `json:"id"` // origin: type_alias, empath: id
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *BaseEntity) IntoPlain() *BaseEntityScanner {
	if pb == nil {
		return nil
	}
	p := &BaseEntityScanner{}

	// Id type alias from id
	if pb.GetId() != nil {
		p.Id = pb.GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetTimestamps() != nil && pb.GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetTimestamps() != nil && pb.GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetTimestamps().GetUpdatedAt())
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *BaseEntityScanner) IntoPb() *BaseEntity {
	if p == nil {
		return nil
	}
	pb := &BaseEntity{}

	// Id type alias -> id
	{
		pb.Id = &EntityID{Value: p.Id}
	}
	// CreatedAt ->
	if pb.Timestamps == nil {
		pb.Timestamps = &Timestamps{}
	}
	pb.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Timestamps == nil {
		pb.Timestamps = &Timestamps{}
	}
	pb.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	return pb
}

// ============================================================================
//
//	Currency - справочник валют (не использует BaseEntity)
//	============================================================================
type CurrencyScanner struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Currency) IntoPlain() *CurrencyScanner {
	if pb == nil {
		return nil
	}
	p := &CurrencyScanner{}

	p.Code = pb.Code
	p.Name = pb.Name
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *CurrencyScanner) IntoPb() *Currency {
	if p == nil {
		return nil
	}
	pb := &Currency{}

	pb.Code = p.Code
	pb.Name = p.Name
	return pb
}

// ============================================================================
//
//	User - пользователь системы (с BaseEntity)
//	============================================================================
type UserScanner struct {
	Id        int64           `json:"id"` // origin: embed, empath: id
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
	Email     string          `json:"email"`
	FullName  string          `json:"fullName"`
	IsActive  bool            `json:"isActive"`
	Orders    []OrderScanner  `json:"orders"`
	Profile   *ProfileScanner `json:"profile"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *User) IntoPlain() *UserScanner {
	if pb == nil {
		return nil
	}
	p := &UserScanner{}

	// Id from id
	if pb.GetBase() != nil && pb.GetBase().GetId() != nil {
		p.Id = pb.GetBase().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetUpdatedAt())
	}
	p.Email = pb.Email
	p.FullName = pb.FullName
	p.IsActive = pb.IsActive
	if len(pb.Orders) > 0 {
		p.Orders = make([]OrderScanner, len(pb.Orders))
		for i, v := range pb.Orders {
			if v != nil {
				p.Orders[i] = *v.IntoPlain()
			}
		}
	}
	if pb.Profile != nil {
		p.Profile = pb.Profile.IntoPlain()
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *UserScanner) IntoPb() *User {
	if p == nil {
		return nil
	}
	pb := &User{}

	// Id -> id
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Id == nil {
		pb.Base.Id = &EntityID{}
	}
	pb.Base.Id.Value = p.Id
	// CreatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	pb.Email = p.Email
	pb.FullName = p.FullName
	pb.IsActive = p.IsActive
	if len(p.Orders) > 0 {
		pb.Orders = make([]*Order, len(p.Orders))
		for i := range p.Orders {
			pb.Orders[i] = (&p.Orders[i]).IntoPb()
		}
	}
	if p.Profile != nil {
		pb.Profile = p.Profile.IntoPb()
	}
	return pb
}

// ============================================================================
//
//	Profile - профиль пользователя (один к одному с User)
//	============================================================================
type ProfileScanner struct {
	Id        int64        `json:"id"` // origin: embed, empath: id
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt time.Time    `json:"updatedAt"`
	UserId    int64        `json:"userId"` // origin: type_alias, empath: user_id
	Bio       string       `json:"bio"`
	AvatarUrl string       `json:"avatarUrl"`
	User      *UserScanner `json:"user"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Profile) IntoPlain() *ProfileScanner {
	if pb == nil {
		return nil
	}
	p := &ProfileScanner{}

	// Id from id
	if pb.GetBase() != nil && pb.GetBase().GetId() != nil {
		p.Id = pb.GetBase().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetUpdatedAt())
	}
	// UserId type alias from user_id
	if pb.GetUserId() != nil {
		p.UserId = pb.GetUserId().GetValue()
	}
	p.Bio = pb.Bio
	p.AvatarUrl = pb.AvatarUrl
	if pb.User != nil {
		p.User = pb.User.IntoPlain()
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *ProfileScanner) IntoPb() *Profile {
	if p == nil {
		return nil
	}
	pb := &Profile{}

	// Id -> id
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Id == nil {
		pb.Base.Id = &EntityID{}
	}
	pb.Base.Id.Value = p.Id
	// CreatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	// UserId type alias -> user_id
	{
		pb.UserId = &EntityID{Value: p.UserId}
	}
	pb.Bio = p.Bio
	pb.AvatarUrl = p.AvatarUrl
	if p.User != nil {
		pb.User = p.User.IntoPb()
	}
	return pb
}

// ============================================================================
//
//	Category - категория товаров (с BaseEntity)
//	============================================================================
type CategoryScanner struct {
	Id        int64     `json:"id"` // origin: embed, empath: id
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	ParentId  int64     `json:"parentId"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Category) IntoPlain() *CategoryScanner {
	if pb == nil {
		return nil
	}
	p := &CategoryScanner{}

	// Id from id
	if pb.GetBase() != nil && pb.GetBase().GetId() != nil {
		p.Id = pb.GetBase().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetUpdatedAt())
	}
	p.Name = pb.Name
	p.Slug = pb.Slug
	if pb.ParentId != nil {
		p.ParentId = ratelcast.Int64ValueToInt64(pb.ParentId)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *CategoryScanner) IntoPb() *Category {
	if p == nil {
		return nil
	}
	pb := &Category{}

	// Id -> id
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Id == nil {
		pb.Base.Id = &EntityID{}
	}
	pb.Base.Id.Value = p.Id
	// CreatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	pb.Name = p.Name
	pb.Slug = p.Slug
	pb.ParentId = ratelcast.Int64ToInt64Value(p.ParentId)
	return pb
}

// ============================================================================
//
//	Tag - тег для товаров (с BaseEntity)
//	============================================================================
type TagScanner struct {
	Id        int64     `json:"id"` // origin: embed, empath: id
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Tag) IntoPlain() *TagScanner {
	if pb == nil {
		return nil
	}
	p := &TagScanner{}

	// Id from id
	if pb.GetBase() != nil && pb.GetBase().GetId() != nil {
		p.Id = pb.GetBase().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetUpdatedAt())
	}
	p.Name = pb.Name
	p.Slug = pb.Slug
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *TagScanner) IntoPb() *Tag {
	if p == nil {
		return nil
	}
	pb := &Tag{}

	// Id -> id
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Id == nil {
		pb.Base.Id = &EntityID{}
	}
	pb.Base.Id.Value = p.Id
	// CreatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	pb.Name = p.Name
	pb.Slug = p.Slug
	return pb
}

// ============================================================================
//
//	Product - товар (с BaseEntity)
//	============================================================================
type ProductScanner struct {
	Id         int64             `json:"id"` // origin: embed, empath: id
	CreatedAt  time.Time         `json:"createdAt"`
	UpdatedAt  time.Time         `json:"updatedAt"`
	Sku        string            `json:"sku"`
	Name       string            `json:"name"`
	Price      float64           `json:"price"`
	Currency   string            `json:"currency"`
	StockQty   int32             `json:"stockQty"`
	IsDeleted  bool              `json:"isDeleted"`
	Categories []CategoryScanner `json:"categories"`
	Tags       []TagScanner      `json:"tags"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Product) IntoPlain() *ProductScanner {
	if pb == nil {
		return nil
	}
	p := &ProductScanner{}

	// Id from id
	if pb.GetBase() != nil && pb.GetBase().GetId() != nil {
		p.Id = pb.GetBase().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetUpdatedAt())
	}
	p.Sku = pb.Sku
	p.Name = pb.Name
	p.Price = pb.Price
	p.Currency = pb.Currency
	p.StockQty = pb.StockQty
	p.IsDeleted = pb.IsDeleted
	if len(pb.Categories) > 0 {
		p.Categories = make([]CategoryScanner, len(pb.Categories))
		for i, v := range pb.Categories {
			if v != nil {
				p.Categories[i] = *v.IntoPlain()
			}
		}
	}
	if len(pb.Tags) > 0 {
		p.Tags = make([]TagScanner, len(pb.Tags))
		for i, v := range pb.Tags {
			if v != nil {
				p.Tags[i] = *v.IntoPlain()
			}
		}
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *ProductScanner) IntoPb() *Product {
	if p == nil {
		return nil
	}
	pb := &Product{}

	// Id -> id
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Id == nil {
		pb.Base.Id = &EntityID{}
	}
	pb.Base.Id.Value = p.Id
	// CreatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	pb.Sku = p.Sku
	pb.Name = p.Name
	pb.Price = p.Price
	pb.Currency = p.Currency
	pb.StockQty = p.StockQty
	pb.IsDeleted = p.IsDeleted
	if len(p.Categories) > 0 {
		pb.Categories = make([]*Category, len(p.Categories))
		for i := range p.Categories {
			pb.Categories[i] = (&p.Categories[i]).IntoPb()
		}
	}
	if len(p.Tags) > 0 {
		pb.Tags = make([]*Tag, len(p.Tags))
		for i := range p.Tags {
			pb.Tags[i] = (&p.Tags[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	Order - заказ (с BaseEntity)
//	============================================================================
type OrderScanner struct {
	Id        int64              `json:"id"` // origin: embed, empath: id
	CreatedAt time.Time          `json:"createdAt"`
	UpdatedAt time.Time          `json:"updatedAt"`
	UserId    int64              `json:"userId"` // origin: type_alias, empath: user_id
	Status    string             `json:"status"`
	Currency  string             `json:"currency"`
	Items     []OrderItemScanner `json:"items"`
	User      *UserScanner       `json:"user"`
	Money     *CurrencyScanner   `json:"money"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Order) IntoPlain() *OrderScanner {
	if pb == nil {
		return nil
	}
	p := &OrderScanner{}

	// Id from id
	if pb.GetBase() != nil && pb.GetBase().GetId() != nil {
		p.Id = pb.GetBase().GetId().GetValue()
	}
	// CreatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetCreatedAt() != nil {
		p.CreatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetCreatedAt())
	}
	// UpdatedAt from
	if pb.GetBase() != nil && pb.GetBase().GetTimestamps() != nil && pb.GetBase().GetTimestamps().GetUpdatedAt() != nil {
		p.UpdatedAt = ratelcast.TimestampToTime(pb.GetBase().GetTimestamps().GetUpdatedAt())
	}
	// UserId type alias from user_id
	if pb.GetUserId() != nil {
		p.UserId = pb.GetUserId().GetValue()
	}
	p.Status = pb.Status
	p.Currency = pb.Currency
	if len(pb.Items) > 0 {
		p.Items = make([]OrderItemScanner, len(pb.Items))
		for i, v := range pb.Items {
			if v != nil {
				p.Items[i] = *v.IntoPlain()
			}
		}
	}
	if pb.User != nil {
		p.User = pb.User.IntoPlain()
	}
	if pb.Money != nil {
		p.Money = pb.Money.IntoPlain()
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *OrderScanner) IntoPb() *Order {
	if p == nil {
		return nil
	}
	pb := &Order{}

	// Id -> id
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Id == nil {
		pb.Base.Id = &EntityID{}
	}
	pb.Base.Id.Value = p.Id
	// CreatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.CreatedAt = ratelcast.TimeToTimestamp(p.CreatedAt)
	// UpdatedAt ->
	if pb.Base == nil {
		pb.Base = &BaseEntity{}
	}
	if pb.Base.Timestamps == nil {
		pb.Base.Timestamps = &Timestamps{}
	}
	pb.Base.Timestamps.UpdatedAt = ratelcast.TimeToTimestamp(p.UpdatedAt)
	// UserId type alias -> user_id
	{
		pb.UserId = &EntityID{Value: p.UserId}
	}
	pb.Status = p.Status
	pb.Currency = p.Currency
	if len(p.Items) > 0 {
		pb.Items = make([]*OrderItem, len(p.Items))
		for i := range p.Items {
			pb.Items[i] = (&p.Items[i]).IntoPb()
		}
	}
	if p.User != nil {
		pb.User = p.User.IntoPb()
	}
	if p.Money != nil {
		pb.Money = p.Money.IntoPb()
	}
	return pb
}

// ============================================================================
//
//	OrderItem - позиция заказа (без BaseEntity - композитный PK)
//	============================================================================
type OrderItemScanner struct {
	OrderId   int64           `json:"orderId"` // origin: type_alias, empath: order_id
	LineNo    int32           `json:"lineNo"`
	ProductId int64           `json:"productId"` // origin: type_alias, empath: product_id
	Qty       int32           `json:"qty"`
	UnitPrice float64         `json:"unitPrice"`
	Order     *OrderScanner   `json:"order"`
	Product   *ProductScanner `json:"product"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *OrderItem) IntoPlain() *OrderItemScanner {
	if pb == nil {
		return nil
	}
	p := &OrderItemScanner{}

	// OrderId type alias from order_id
	if pb.GetOrderId() != nil {
		p.OrderId = pb.GetOrderId().GetValue()
	}
	p.LineNo = pb.LineNo
	// ProductId type alias from product_id
	if pb.GetProductId() != nil {
		p.ProductId = pb.GetProductId().GetValue()
	}
	p.Qty = pb.Qty
	p.UnitPrice = pb.UnitPrice
	if pb.Order != nil {
		p.Order = pb.Order.IntoPlain()
	}
	if pb.Product != nil {
		p.Product = pb.Product.IntoPlain()
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *OrderItemScanner) IntoPb() *OrderItem {
	if p == nil {
		return nil
	}
	pb := &OrderItem{}

	// OrderId type alias -> order_id
	{
		pb.OrderId = &EntityID{Value: p.OrderId}
	}
	pb.LineNo = p.LineNo
	// ProductId type alias -> product_id
	{
		pb.ProductId = &EntityID{Value: p.ProductId}
	}
	pb.Qty = p.Qty
	pb.UnitPrice = p.UnitPrice
	if p.Order != nil {
		pb.Order = p.Order.IntoPb()
	}
	if p.Product != nil {
		pb.Product = p.Product.IntoPb()
	}
	return pb
}
