// Code generated by protoc-gen-ratel. DO NOT EDIT.
// source: examples/proto/store.proto

package storepb

import (
	"errors"
	"time"

	"github.com/yaroher/ratel/pkg/ddl"
	"github.com/yaroher/ratel/pkg/dml/set"
	"github.com/yaroher/ratel/pkg/exec"
	"github.com/yaroher/ratel/pkg/pgx-ext/sqlerr"
	"github.com/yaroher/ratel/pkg/repository"
	"github.com/yaroher/ratel/pkg/schema"
)

var (
	_ = time.Time{}
	_ = errors.New
	_ = sqlerr.IsConstraintNamed
)

// ============================================================================
// Additional SQL Statements (file-level)
// ============================================================================

// AdditionalSQL contains raw SQL statements declared via additional_code
// file option. Pass these to ddl.SchemaSQL() alongside table definitions.
var AdditionalSQL = []ddl.SchemaSqler{
	ddl.RawSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm"),
	ddl.RawSQL("CREATE OR REPLACE FUNCTION store.set_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$"),
}

// CurrencyAlias is the table alias type for the currency table
type CurrencyAlias string

func (a CurrencyAlias) String() string { return string(a) }

const CurrencyAliasName CurrencyAlias = "currency"

// CurrencyColumnAlias represents column names for the currency table
type CurrencyColumnAlias string

func (c CurrencyColumnAlias) String() string { return string(c) }

const (
	CurrencyColumnCode CurrencyColumnAlias = "code"
	CurrencyColumnName CurrencyColumnAlias = "name"
)

func (s *CurrencyScanner) GetTarget(col string) func() any {
	switch CurrencyColumnAlias(col) {
	case CurrencyColumnCode:
		return func() any { return &s.Code }
	case CurrencyColumnName:
		return func() any { return &s.Name }
	default:
		panic("unknown field: " + col)
	}
}

func (s *CurrencyScanner) GetSetter(f CurrencyColumnAlias) func() set.ValueSetter[CurrencyColumnAlias] {
	switch f {
	case CurrencyColumnCode:
		return func() set.ValueSetter[CurrencyColumnAlias] { return set.NewSetter(f, &s.Code) }
	case CurrencyColumnName:
		return func() set.ValueSetter[CurrencyColumnAlias] { return set.NewSetter(f, &s.Name) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *CurrencyScanner) GetValue(f CurrencyColumnAlias) func() any {
	switch f {
	case CurrencyColumnCode:
		return func() any { return s.Code }
	case CurrencyColumnName:
		return func() any { return s.Name }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the currency table
func (s *CurrencyScanner) Relations() []exec.RelationLoader[*CurrencyScanner] {
	return nil
}

// CurrencysTable represents the currency table with its columns
type CurrencysTable struct {
	*schema.Table[CurrencyAlias, CurrencyColumnAlias, *CurrencyScanner]
	Code schema.TextColumnI[CurrencyColumnAlias]
	Name schema.TextColumnI[CurrencyColumnAlias]
}

// Currencys is the global currency table instance
var Currencys = func() CurrencysTable {
	codeCol := schema.TextColumn(CurrencyColumnCode, ddl.WithPrimaryKey[CurrencyColumnAlias](), ddl.WithCheck[CurrencyColumnAlias]("code <> ''"))
	nameCol := schema.TextColumn(CurrencyColumnName, ddl.WithNotNull[CurrencyColumnAlias]())

	return CurrencysTable{
		Table: schema.NewTable[CurrencyAlias, CurrencyColumnAlias, *CurrencyScanner](
			CurrencyAliasName,
			func() *CurrencyScanner { return &CurrencyScanner{} },
			[]*ddl.ColumnDDL[CurrencyColumnAlias]{
				codeCol.DDL(),
				nameCol.DDL(),
			},
		),
		Code: codeCol,
		Name: nameCol,
	}
}()

// CurrencysRef is a reference to the currency table for relations
var CurrencysRef schema.RelationTableAlias[CurrencyAlias] = Currencys.Table

// CurrencyConverter provides conversion between Currency and CurrencyScanner
var CurrencyConverter = repository.Converter[*CurrencyScanner, *Currency]{
	ToScanner: (*Currency).IntoPlain,
	ToProto:   (*CurrencyScanner).IntoPb,
}

// UserAlias is the table alias type for the users table
type UserAlias string

func (a UserAlias) String() string { return string(a) }

const UserAliasName UserAlias = "users"

// UserColumnAlias represents column names for the users table
type UserColumnAlias string

func (c UserColumnAlias) String() string { return string(c) }

const (
	UserColumnId               UserColumnAlias = "id"
	UserColumnCreatedAt        UserColumnAlias = "created_at"
	UserColumnUpdatedAt        UserColumnAlias = "updated_at"
	UserColumnEmail            UserColumnAlias = "email"
	UserColumnFullName         UserColumnAlias = "full_name"
	UserColumnIsActive         UserColumnAlias = "is_active"
	UserColumnEmailConfirmedAt UserColumnAlias = "email_confirmed_at"
	UserColumnNickname         UserColumnAlias = "nickname"
	UserColumnDeletedAt        UserColumnAlias = "deleted_at"
)

func (s *UserScanner) GetTarget(col string) func() any {
	switch UserColumnAlias(col) {
	case UserColumnId:
		return func() any { return &s.Id }
	case UserColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case UserColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	case UserColumnEmail:
		return func() any { return &s.Email }
	case UserColumnFullName:
		return func() any { return &s.FullName }
	case UserColumnIsActive:
		return func() any { return &s.IsActive }
	case UserColumnEmailConfirmedAt:
		return func() any { return &s.EmailConfirmedAt }
	case UserColumnNickname:
		return func() any { return &s.Nickname }
	case UserColumnDeletedAt:
		return func() any { return &s.DeletedAt }
	default:
		panic("unknown field: " + col)
	}
}

func (s *UserScanner) GetSetter(f UserColumnAlias) func() set.ValueSetter[UserColumnAlias] {
	switch f {
	case UserColumnId:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.Id) }
	case UserColumnCreatedAt:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case UserColumnUpdatedAt:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	case UserColumnEmail:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.Email) }
	case UserColumnFullName:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.FullName) }
	case UserColumnIsActive:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.IsActive) }
	case UserColumnEmailConfirmedAt:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.EmailConfirmedAt) }
	case UserColumnNickname:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.Nickname) }
	case UserColumnDeletedAt:
		return func() set.ValueSetter[UserColumnAlias] { return set.NewSetter(f, &s.DeletedAt) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *UserScanner) GetValue(f UserColumnAlias) func() any {
	switch f {
	case UserColumnId:
		return func() any { return s.Id }
	case UserColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case UserColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	case UserColumnEmail:
		return func() any { return s.Email }
	case UserColumnFullName:
		return func() any { return s.FullName }
	case UserColumnIsActive:
		return func() any { return s.IsActive }
	case UserColumnEmailConfirmedAt:
		return func() any { return s.EmailConfirmedAt }
	case UserColumnNickname:
		return func() any { return s.Nickname }
	case UserColumnDeletedAt:
		return func() any { return s.DeletedAt }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the users table
func (s *UserScanner) Relations() []exec.RelationLoader[*UserScanner] {
	return []exec.RelationLoader[*UserScanner]{
		schema.HasManyLoad(
			UserOrders,
			Orders.Table,
			UserColumnId,
			func(base *UserScanner, related []*OrderScanner) {
				base.Orders = make([]OrderScanner, len(related))
				for i, r := range related {
					if r != nil {
						base.Orders[i] = *r
					}
				}
			},
		),
		schema.HasOneLoad(
			UserProfile,
			Profiles.Table,
			UserColumnId,
			func(base *UserScanner, related *ProfileScanner) {
				base.Profile = related
			},
		),
	}
}

// ============================================================================
// User Relation Query Options
// ============================================================================

// UsersWithOrders returns a QueryOption to load Orders relation
func UsersWithOrders() exec.QueryOption[UserColumnAlias, *UserScanner] {
	return exec.WithRelationLoaders[UserColumnAlias, *UserScanner](
		schema.HasManyLoad(
			UserOrders,
			Orders.Table,
			UserColumnId,
			func(base *UserScanner, related []*OrderScanner) {
				base.Orders = make([]OrderScanner, len(related))
				for i, r := range related {
					if r != nil {
						base.Orders[i] = *r
					}
				}
			},
		),
	)
}

// UsersWithProfile returns a QueryOption to load Profile relation
func UsersWithProfile() exec.QueryOption[UserColumnAlias, *UserScanner] {
	return exec.WithRelationLoaders[UserColumnAlias, *UserScanner](
		schema.HasOneLoad(
			UserProfile,
			Profiles.Table,
			UserColumnId,
			func(base *UserScanner, related *ProfileScanner) {
				base.Profile = related
			},
		),
	)
}

// UsersWithAllRelations returns a QueryOption to load all relations
func UsersWithAllRelations() exec.QueryOption[UserColumnAlias, *UserScanner] {
	return exec.WithRelationLoaders[UserColumnAlias, *UserScanner](
		schema.HasManyLoad(
			UserOrders,
			Orders.Table,
			UserColumnId,
			func(base *UserScanner, related []*OrderScanner) {
				base.Orders = make([]OrderScanner, len(related))
				for i, r := range related {
					if r != nil {
						base.Orders[i] = *r
					}
				}
			},
		),
		schema.HasOneLoad(
			UserProfile,
			Profiles.Table,
			UserColumnId,
			func(base *UserScanner, related *ProfileScanner) {
				base.Profile = related
			},
		),
	)
}

// UsersTable represents the users table with its columns
type UsersTable struct {
	*schema.Table[UserAlias, UserColumnAlias, *UserScanner]
	Id               schema.BigSerialColumnI[UserColumnAlias]
	CreatedAt        schema.TimestamptzColumnI[UserColumnAlias]
	UpdatedAt        schema.TimestamptzColumnI[UserColumnAlias]
	Email            schema.TextColumnI[UserColumnAlias]
	FullName         schema.TextColumnI[UserColumnAlias]
	IsActive         schema.BooleanColumnI[UserColumnAlias]
	EmailConfirmedAt schema.NullTimestamptzColumnI[UserColumnAlias]
	Nickname         schema.NullTextColumnI[UserColumnAlias]
	DeletedAt        schema.NullTimestamptzColumnI[UserColumnAlias]
}

// Users is the global users table instance
var Users = func() UsersTable {
	idCol := schema.BigSerialColumn(UserColumnId, ddl.WithPrimaryKey[UserColumnAlias]())
	createdAtCol := schema.TimestamptzColumn(UserColumnCreatedAt, ddl.WithDefault[UserColumnAlias]("now()"), ddl.WithNotNull[UserColumnAlias]())
	updatedAtCol := schema.TimestamptzColumn(UserColumnUpdatedAt, ddl.WithDefault[UserColumnAlias]("now()"), ddl.WithNotNull[UserColumnAlias]())
	emailCol := schema.TextColumn(UserColumnEmail, ddl.WithUnique[UserColumnAlias](), ddl.WithNotNull[UserColumnAlias]())
	fullNameCol := schema.TextColumn(UserColumnFullName, ddl.WithNotNull[UserColumnAlias]())
	isActiveCol := schema.BooleanColumn(UserColumnIsActive, ddl.WithDefault[UserColumnAlias]("true"), ddl.WithNotNull[UserColumnAlias]())
	emailConfirmedAtCol := schema.NullTimestamptzColumn(UserColumnEmailConfirmedAt)
	nicknameCol := schema.NullTextColumn(UserColumnNickname)
	deletedAtCol := schema.NullTimestamptzColumn(UserColumnDeletedAt)

	idx0 := ddl.NewIndex[UserAlias, UserColumnAlias]("idx_users_email", UserAliasName).OnColumns(UserColumnEmail)
	idx0 = idx0.Unique()
	idx1 := ddl.NewIndex[UserAlias, UserColumnAlias]("idx_users_is_active_created_at", UserAliasName).OnColumns(UserColumnIsActive, UserColumnCreatedAt)

	return UsersTable{
		Table: schema.NewTable[UserAlias, UserColumnAlias, *UserScanner](
			UserAliasName,
			func() *UserScanner { return &UserScanner{} },
			[]*ddl.ColumnDDL[UserColumnAlias]{
				idCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
				emailCol.DDL(),
				fullNameCol.DDL(),
				isActiveCol.DDL(),
				emailConfirmedAtCol.DDL(),
				nicknameCol.DDL(),
				deletedAtCol.DDL(),
			},
			ddl.WithIndexes[UserAlias, UserColumnAlias](
				idx0,
				idx1,
			),
			ddl.WithSchema[UserAlias, UserColumnAlias]("store"),
			ddl.WithPostStatements[UserAlias, UserColumnAlias](
				"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
				"CREATE POLICY users_own_data ON {table} FOR ALL USING (id = current_setting('app.current_user_id')::bigint)",
				"CREATE POLICY users_insert ON {table} FOR INSERT WITH CHECK (true)",
			),
		),
		Id:               idCol,
		CreatedAt:        createdAtCol,
		UpdatedAt:        updatedAtCol,
		Email:            emailCol,
		FullName:         fullNameCol,
		IsActive:         isActiveCol,
		EmailConfirmedAt: emailConfirmedAtCol,
		Nickname:         nicknameCol,
		DeletedAt:        deletedAtCol,
	}
}()

// UsersRef is a reference to the users table for relations
var UsersRef schema.RelationTableAlias[UserAlias] = Users.Table

// UserConverter provides conversion between User and UserScanner
var UserConverter = repository.Converter[*UserScanner, *User]{
	ToScanner: (*User).IntoPlain,
	ToProto:   (*UserScanner).IntoPb,
}

// ProfileAlias is the table alias type for the profiles table
type ProfileAlias string

func (a ProfileAlias) String() string { return string(a) }

const ProfileAliasName ProfileAlias = "profiles"

// ProfileColumnAlias represents column names for the profiles table
type ProfileColumnAlias string

func (c ProfileColumnAlias) String() string { return string(c) }

const (
	ProfileColumnId        ProfileColumnAlias = "id"
	ProfileColumnCreatedAt ProfileColumnAlias = "created_at"
	ProfileColumnUpdatedAt ProfileColumnAlias = "updated_at"
	ProfileColumnUserId    ProfileColumnAlias = "user_id"
	ProfileColumnBio       ProfileColumnAlias = "bio"
	ProfileColumnAvatarUrl ProfileColumnAlias = "avatar_url"
)

func (s *ProfileScanner) GetTarget(col string) func() any {
	switch ProfileColumnAlias(col) {
	case ProfileColumnId:
		return func() any { return &s.Id }
	case ProfileColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case ProfileColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	case ProfileColumnUserId:
		return func() any { return &s.UserId }
	case ProfileColumnBio:
		return func() any { return &s.Bio }
	case ProfileColumnAvatarUrl:
		return func() any { return &s.AvatarUrl }
	default:
		panic("unknown field: " + col)
	}
}

func (s *ProfileScanner) GetSetter(f ProfileColumnAlias) func() set.ValueSetter[ProfileColumnAlias] {
	switch f {
	case ProfileColumnId:
		return func() set.ValueSetter[ProfileColumnAlias] { return set.NewSetter(f, &s.Id) }
	case ProfileColumnCreatedAt:
		return func() set.ValueSetter[ProfileColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case ProfileColumnUpdatedAt:
		return func() set.ValueSetter[ProfileColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	case ProfileColumnUserId:
		return func() set.ValueSetter[ProfileColumnAlias] { return set.NewSetter(f, &s.UserId) }
	case ProfileColumnBio:
		return func() set.ValueSetter[ProfileColumnAlias] { return set.NewSetter(f, &s.Bio) }
	case ProfileColumnAvatarUrl:
		return func() set.ValueSetter[ProfileColumnAlias] { return set.NewSetter(f, &s.AvatarUrl) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *ProfileScanner) GetValue(f ProfileColumnAlias) func() any {
	switch f {
	case ProfileColumnId:
		return func() any { return s.Id }
	case ProfileColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case ProfileColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	case ProfileColumnUserId:
		return func() any { return s.UserId }
	case ProfileColumnBio:
		return func() any { return s.Bio }
	case ProfileColumnAvatarUrl:
		return func() any { return s.AvatarUrl }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the profiles table
func (s *ProfileScanner) Relations() []exec.RelationLoader[*ProfileScanner] {
	return []exec.RelationLoader[*ProfileScanner]{
		schema.BelongsToLoad(
			ProfileUser,
			Users.Table,
			ProfileColumnUserId,
			func(base *ProfileScanner, related *UserScanner) {
				base.User = related
			},
		),
	}
}

// ============================================================================
// Profile Relation Query Options
// ============================================================================

// ProfilesWithUser returns a QueryOption to load User relation
func ProfilesWithUser() exec.QueryOption[ProfileColumnAlias, *ProfileScanner] {
	return exec.WithRelationLoaders[ProfileColumnAlias, *ProfileScanner](
		schema.BelongsToLoad(
			ProfileUser,
			Users.Table,
			ProfileColumnUserId,
			func(base *ProfileScanner, related *UserScanner) {
				base.User = related
			},
		),
	)
}

// ProfilesWithAllRelations returns a QueryOption to load all relations
func ProfilesWithAllRelations() exec.QueryOption[ProfileColumnAlias, *ProfileScanner] {
	return exec.WithRelationLoaders[ProfileColumnAlias, *ProfileScanner](
		schema.BelongsToLoad(
			ProfileUser,
			Users.Table,
			ProfileColumnUserId,
			func(base *ProfileScanner, related *UserScanner) {
				base.User = related
			},
		),
	)
}

// ProfilesTable represents the profiles table with its columns
type ProfilesTable struct {
	*schema.Table[ProfileAlias, ProfileColumnAlias, *ProfileScanner]
	Id        schema.BigSerialColumnI[ProfileColumnAlias]
	CreatedAt schema.TimestamptzColumnI[ProfileColumnAlias]
	UpdatedAt schema.TimestamptzColumnI[ProfileColumnAlias]
	UserId    schema.BigIntColumnI[ProfileColumnAlias]
	Bio       schema.TextColumnI[ProfileColumnAlias]
	AvatarUrl schema.TextColumnI[ProfileColumnAlias]
}

// Profiles is the global profiles table instance
var Profiles = func() ProfilesTable {
	idCol := schema.BigSerialColumn(ProfileColumnId, ddl.WithPrimaryKey[ProfileColumnAlias]())
	createdAtCol := schema.TimestamptzColumn(ProfileColumnCreatedAt, ddl.WithDefault[ProfileColumnAlias]("now()"), ddl.WithNotNull[ProfileColumnAlias]())
	updatedAtCol := schema.TimestamptzColumn(ProfileColumnUpdatedAt, ddl.WithDefault[ProfileColumnAlias]("now()"), ddl.WithNotNull[ProfileColumnAlias]())
	userIdCol := schema.BigIntColumn(ProfileColumnUserId, ddl.WithReferences[ProfileColumnAlias]("\"store\".\"users\"", "id"), ddl.WithOnDelete[ProfileColumnAlias]("CASCADE"), ddl.WithNotNull[ProfileColumnAlias]())
	bioCol := schema.TextColumn(ProfileColumnBio, ddl.WithNotNull[ProfileColumnAlias]())
	avatarUrlCol := schema.TextColumn(ProfileColumnAvatarUrl, ddl.WithNotNull[ProfileColumnAlias]())

	idx0 := ddl.NewIndex[ProfileAlias, ProfileColumnAlias]("idx_profiles_user_id", ProfileAliasName).OnColumns(ProfileColumnUserId)
	idx0 = idx0.Unique()

	return ProfilesTable{
		Table: schema.NewTable[ProfileAlias, ProfileColumnAlias, *ProfileScanner](
			ProfileAliasName,
			func() *ProfileScanner { return &ProfileScanner{} },
			[]*ddl.ColumnDDL[ProfileColumnAlias]{
				idCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
				userIdCol.DDL(),
				bioCol.DDL(),
				avatarUrlCol.DDL(),
			},
			ddl.WithIndexes[ProfileAlias, ProfileColumnAlias](
				idx0,
			),
			ddl.WithSchema[ProfileAlias, ProfileColumnAlias]("store"),
			ddl.WithPostStatements[ProfileAlias, ProfileColumnAlias](
				"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
				"CREATE POLICY profiles_own_data ON {table} FOR ALL USING (user_id = current_setting('app.current_user_id')::bigint)",
			),
		),
		Id:        idCol,
		CreatedAt: createdAtCol,
		UpdatedAt: updatedAtCol,
		UserId:    userIdCol,
		Bio:       bioCol,
		AvatarUrl: avatarUrlCol,
	}
}()

// ProfilesRef is a reference to the profiles table for relations
var ProfilesRef schema.RelationTableAlias[ProfileAlias] = Profiles.Table

// ProfileConverter provides conversion between Profile and ProfileScanner
var ProfileConverter = repository.Converter[*ProfileScanner, *Profile]{
	ToScanner: (*Profile).IntoPlain,
	ToProto:   (*ProfileScanner).IntoPb,
}

// CategoryAlias is the table alias type for the categories table
type CategoryAlias string

func (a CategoryAlias) String() string { return string(a) }

const CategoryAliasName CategoryAlias = "categories"

// CategoryColumnAlias represents column names for the categories table
type CategoryColumnAlias string

func (c CategoryColumnAlias) String() string { return string(c) }

const (
	CategoryColumnId        CategoryColumnAlias = "id"
	CategoryColumnCreatedAt CategoryColumnAlias = "created_at"
	CategoryColumnUpdatedAt CategoryColumnAlias = "updated_at"
	CategoryColumnName      CategoryColumnAlias = "name"
	CategoryColumnSlug      CategoryColumnAlias = "slug"
	CategoryColumnParentId  CategoryColumnAlias = "parent_id"
)

func (s *CategoryScanner) GetTarget(col string) func() any {
	switch CategoryColumnAlias(col) {
	case CategoryColumnId:
		return func() any { return &s.Id }
	case CategoryColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case CategoryColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	case CategoryColumnName:
		return func() any { return &s.Name }
	case CategoryColumnSlug:
		return func() any { return &s.Slug }
	case CategoryColumnParentId:
		return func() any { return &s.ParentId }
	default:
		panic("unknown field: " + col)
	}
}

func (s *CategoryScanner) GetSetter(f CategoryColumnAlias) func() set.ValueSetter[CategoryColumnAlias] {
	switch f {
	case CategoryColumnId:
		return func() set.ValueSetter[CategoryColumnAlias] { return set.NewSetter(f, &s.Id) }
	case CategoryColumnCreatedAt:
		return func() set.ValueSetter[CategoryColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case CategoryColumnUpdatedAt:
		return func() set.ValueSetter[CategoryColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	case CategoryColumnName:
		return func() set.ValueSetter[CategoryColumnAlias] { return set.NewSetter(f, &s.Name) }
	case CategoryColumnSlug:
		return func() set.ValueSetter[CategoryColumnAlias] { return set.NewSetter(f, &s.Slug) }
	case CategoryColumnParentId:
		return func() set.ValueSetter[CategoryColumnAlias] { return set.NewSetter(f, &s.ParentId) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *CategoryScanner) GetValue(f CategoryColumnAlias) func() any {
	switch f {
	case CategoryColumnId:
		return func() any { return s.Id }
	case CategoryColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case CategoryColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	case CategoryColumnName:
		return func() any { return s.Name }
	case CategoryColumnSlug:
		return func() any { return s.Slug }
	case CategoryColumnParentId:
		return func() any { return s.ParentId }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the categories table
func (s *CategoryScanner) Relations() []exec.RelationLoader[*CategoryScanner] {
	return nil
}

// CategorysTable represents the categories table with its columns
type CategorysTable struct {
	*schema.Table[CategoryAlias, CategoryColumnAlias, *CategoryScanner]
	Id        schema.BigSerialColumnI[CategoryColumnAlias]
	CreatedAt schema.TimestamptzColumnI[CategoryColumnAlias]
	UpdatedAt schema.TimestamptzColumnI[CategoryColumnAlias]
	Name      schema.TextColumnI[CategoryColumnAlias]
	Slug      schema.TextColumnI[CategoryColumnAlias]
	ParentId  schema.NullBigIntColumnI[CategoryColumnAlias]
}

// Categorys is the global categories table instance
var Categorys = func() CategorysTable {
	idCol := schema.BigSerialColumn(CategoryColumnId, ddl.WithPrimaryKey[CategoryColumnAlias]())
	createdAtCol := schema.TimestamptzColumn(CategoryColumnCreatedAt, ddl.WithDefault[CategoryColumnAlias]("now()"), ddl.WithNotNull[CategoryColumnAlias]())
	updatedAtCol := schema.TimestamptzColumn(CategoryColumnUpdatedAt, ddl.WithDefault[CategoryColumnAlias]("now()"), ddl.WithNotNull[CategoryColumnAlias]())
	nameCol := schema.TextColumn(CategoryColumnName, ddl.WithNotNull[CategoryColumnAlias]())
	slugCol := schema.TextColumn(CategoryColumnSlug, ddl.WithUnique[CategoryColumnAlias](), ddl.WithNotNull[CategoryColumnAlias]())
	parentIdCol := schema.NullBigIntColumn(CategoryColumnParentId, ddl.WithReferences[CategoryColumnAlias]("\"store\".\"categories\"", "id"), ddl.WithOnDelete[CategoryColumnAlias]("SET NULL"))

	return CategorysTable{
		Table: schema.NewTable[CategoryAlias, CategoryColumnAlias, *CategoryScanner](
			CategoryAliasName,
			func() *CategoryScanner { return &CategoryScanner{} },
			[]*ddl.ColumnDDL[CategoryColumnAlias]{
				idCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
				nameCol.DDL(),
				slugCol.DDL(),
				parentIdCol.DDL(),
			},
			ddl.WithSchema[CategoryAlias, CategoryColumnAlias]("store"),
		),
		Id:        idCol,
		CreatedAt: createdAtCol,
		UpdatedAt: updatedAtCol,
		Name:      nameCol,
		Slug:      slugCol,
		ParentId:  parentIdCol,
	}
}()

// CategorysRef is a reference to the categories table for relations
var CategorysRef schema.RelationTableAlias[CategoryAlias] = Categorys.Table

// CategoryConverter provides conversion between Category and CategoryScanner
var CategoryConverter = repository.Converter[*CategoryScanner, *Category]{
	ToScanner: (*Category).IntoPlain,
	ToProto:   (*CategoryScanner).IntoPb,
}

// TagAlias is the table alias type for the tags table
type TagAlias string

func (a TagAlias) String() string { return string(a) }

const TagAliasName TagAlias = "tags"

// TagColumnAlias represents column names for the tags table
type TagColumnAlias string

func (c TagColumnAlias) String() string { return string(c) }

const (
	TagColumnId        TagColumnAlias = "id"
	TagColumnCreatedAt TagColumnAlias = "created_at"
	TagColumnUpdatedAt TagColumnAlias = "updated_at"
	TagColumnName      TagColumnAlias = "name"
	TagColumnSlug      TagColumnAlias = "slug"
)

func (s *TagScanner) GetTarget(col string) func() any {
	switch TagColumnAlias(col) {
	case TagColumnId:
		return func() any { return &s.Id }
	case TagColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case TagColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	case TagColumnName:
		return func() any { return &s.Name }
	case TagColumnSlug:
		return func() any { return &s.Slug }
	default:
		panic("unknown field: " + col)
	}
}

func (s *TagScanner) GetSetter(f TagColumnAlias) func() set.ValueSetter[TagColumnAlias] {
	switch f {
	case TagColumnId:
		return func() set.ValueSetter[TagColumnAlias] { return set.NewSetter(f, &s.Id) }
	case TagColumnCreatedAt:
		return func() set.ValueSetter[TagColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case TagColumnUpdatedAt:
		return func() set.ValueSetter[TagColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	case TagColumnName:
		return func() set.ValueSetter[TagColumnAlias] { return set.NewSetter(f, &s.Name) }
	case TagColumnSlug:
		return func() set.ValueSetter[TagColumnAlias] { return set.NewSetter(f, &s.Slug) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *TagScanner) GetValue(f TagColumnAlias) func() any {
	switch f {
	case TagColumnId:
		return func() any { return s.Id }
	case TagColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case TagColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	case TagColumnName:
		return func() any { return s.Name }
	case TagColumnSlug:
		return func() any { return s.Slug }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the tags table
func (s *TagScanner) Relations() []exec.RelationLoader[*TagScanner] {
	return nil
}

// TagsTable represents the tags table with its columns
type TagsTable struct {
	*schema.Table[TagAlias, TagColumnAlias, *TagScanner]
	Id        schema.BigSerialColumnI[TagColumnAlias]
	CreatedAt schema.TimestamptzColumnI[TagColumnAlias]
	UpdatedAt schema.TimestamptzColumnI[TagColumnAlias]
	Name      schema.TextColumnI[TagColumnAlias]
	Slug      schema.TextColumnI[TagColumnAlias]
}

// Tags is the global tags table instance
var Tags = func() TagsTable {
	idCol := schema.BigSerialColumn(TagColumnId, ddl.WithPrimaryKey[TagColumnAlias]())
	createdAtCol := schema.TimestamptzColumn(TagColumnCreatedAt, ddl.WithDefault[TagColumnAlias]("now()"), ddl.WithNotNull[TagColumnAlias]())
	updatedAtCol := schema.TimestamptzColumn(TagColumnUpdatedAt, ddl.WithDefault[TagColumnAlias]("now()"), ddl.WithNotNull[TagColumnAlias]())
	nameCol := schema.TextColumn(TagColumnName, ddl.WithNotNull[TagColumnAlias]())
	slugCol := schema.TextColumn(TagColumnSlug, ddl.WithUnique[TagColumnAlias](), ddl.WithNotNull[TagColumnAlias]())

	return TagsTable{
		Table: schema.NewTable[TagAlias, TagColumnAlias, *TagScanner](
			TagAliasName,
			func() *TagScanner { return &TagScanner{} },
			[]*ddl.ColumnDDL[TagColumnAlias]{
				idCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
				nameCol.DDL(),
				slugCol.DDL(),
			},
		),
		Id:        idCol,
		CreatedAt: createdAtCol,
		UpdatedAt: updatedAtCol,
		Name:      nameCol,
		Slug:      slugCol,
	}
}()

// TagsRef is a reference to the tags table for relations
var TagsRef schema.RelationTableAlias[TagAlias] = Tags.Table

// TagConverter provides conversion between Tag and TagScanner
var TagConverter = repository.Converter[*TagScanner, *Tag]{
	ToScanner: (*Tag).IntoPlain,
	ToProto:   (*TagScanner).IntoPb,
}

// ProductAlias is the table alias type for the products table
type ProductAlias string

func (a ProductAlias) String() string { return string(a) }

const ProductAliasName ProductAlias = "products"

// ProductColumnAlias represents column names for the products table
type ProductColumnAlias string

func (c ProductColumnAlias) String() string { return string(c) }

const (
	ProductColumnId        ProductColumnAlias = "id"
	ProductColumnCreatedAt ProductColumnAlias = "created_at"
	ProductColumnUpdatedAt ProductColumnAlias = "updated_at"
	ProductColumnSku       ProductColumnAlias = "sku"
	ProductColumnName      ProductColumnAlias = "name"
	ProductColumnPrice     ProductColumnAlias = "price"
	ProductColumnCurrency  ProductColumnAlias = "currency"
	ProductColumnStockQty  ProductColumnAlias = "stock_qty"
	ProductColumnIsDeleted ProductColumnAlias = "is_deleted"
)

func (s *ProductScanner) GetTarget(col string) func() any {
	switch ProductColumnAlias(col) {
	case ProductColumnId:
		return func() any { return &s.Id }
	case ProductColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case ProductColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	case ProductColumnSku:
		return func() any { return &s.Sku }
	case ProductColumnName:
		return func() any { return &s.Name }
	case ProductColumnPrice:
		return func() any { return &s.Price }
	case ProductColumnCurrency:
		return func() any { return &s.Currency }
	case ProductColumnStockQty:
		return func() any { return &s.StockQty }
	case ProductColumnIsDeleted:
		return func() any { return &s.IsDeleted }
	default:
		panic("unknown field: " + col)
	}
}

func (s *ProductScanner) GetSetter(f ProductColumnAlias) func() set.ValueSetter[ProductColumnAlias] {
	switch f {
	case ProductColumnId:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.Id) }
	case ProductColumnCreatedAt:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case ProductColumnUpdatedAt:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	case ProductColumnSku:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.Sku) }
	case ProductColumnName:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.Name) }
	case ProductColumnPrice:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.Price) }
	case ProductColumnCurrency:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.Currency) }
	case ProductColumnStockQty:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.StockQty) }
	case ProductColumnIsDeleted:
		return func() set.ValueSetter[ProductColumnAlias] { return set.NewSetter(f, &s.IsDeleted) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *ProductScanner) GetValue(f ProductColumnAlias) func() any {
	switch f {
	case ProductColumnId:
		return func() any { return s.Id }
	case ProductColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case ProductColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	case ProductColumnSku:
		return func() any { return s.Sku }
	case ProductColumnName:
		return func() any { return s.Name }
	case ProductColumnPrice:
		return func() any { return s.Price }
	case ProductColumnCurrency:
		return func() any { return s.Currency }
	case ProductColumnStockQty:
		return func() any { return s.StockQty }
	case ProductColumnIsDeleted:
		return func() any { return s.IsDeleted }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the products table
func (s *ProductScanner) Relations() []exec.RelationLoader[*ProductScanner] {
	return nil
}

// ProductsTable represents the products table with its columns
type ProductsTable struct {
	*schema.Table[ProductAlias, ProductColumnAlias, *ProductScanner]
	Id        schema.BigSerialColumnI[ProductColumnAlias]
	CreatedAt schema.TimestamptzColumnI[ProductColumnAlias]
	UpdatedAt schema.TimestamptzColumnI[ProductColumnAlias]
	Sku       schema.TextColumnI[ProductColumnAlias]
	Name      schema.TextColumnI[ProductColumnAlias]
	Price     schema.DoublePrecisionColumnI[ProductColumnAlias]
	Currency  schema.TextColumnI[ProductColumnAlias]
	StockQty  schema.IntegerColumnI[ProductColumnAlias]
	IsDeleted schema.BooleanColumnI[ProductColumnAlias]
}

// Products is the global products table instance
var Products = func() ProductsTable {
	idCol := schema.BigSerialColumn(ProductColumnId, ddl.WithPrimaryKey[ProductColumnAlias]())
	createdAtCol := schema.TimestamptzColumn(ProductColumnCreatedAt, ddl.WithDefault[ProductColumnAlias]("now()"), ddl.WithNotNull[ProductColumnAlias]())
	updatedAtCol := schema.TimestamptzColumn(ProductColumnUpdatedAt, ddl.WithDefault[ProductColumnAlias]("now()"), ddl.WithNotNull[ProductColumnAlias]())
	skuCol := schema.TextColumn(ProductColumnSku, ddl.WithUnique[ProductColumnAlias](), ddl.WithNotNull[ProductColumnAlias]())
	nameCol := schema.TextColumn(ProductColumnName, ddl.WithNotNull[ProductColumnAlias]())
	priceCol := schema.DoublePrecisionColumn(ProductColumnPrice, ddl.WithNotNull[ProductColumnAlias]())
	currencyCol := schema.TextColumn(ProductColumnCurrency, ddl.WithReferences[ProductColumnAlias]("currency", "code"), ddl.WithOnDelete[ProductColumnAlias]("RESTRICT"), ddl.WithNotNull[ProductColumnAlias]())
	stockQtyCol := schema.IntegerColumn(ProductColumnStockQty, ddl.WithDefault[ProductColumnAlias]("0"), ddl.WithNotNull[ProductColumnAlias]())
	isDeletedCol := schema.BooleanColumn(ProductColumnIsDeleted, ddl.WithDefault[ProductColumnAlias]("false"), ddl.WithNotNull[ProductColumnAlias]())

	idx0 := ddl.NewIndex[ProductAlias, ProductColumnAlias]("idx_products_sku", ProductAliasName).OnColumns(ProductColumnSku)
	idx1 := ddl.NewIndex[ProductAlias, ProductColumnAlias]("idx_products_currency", ProductAliasName).OnColumns(ProductColumnCurrency)
	idx2 := ddl.NewIndex[ProductAlias, ProductColumnAlias]("idx_products_is_deleted_created_at", ProductAliasName).OnColumns(ProductColumnIsDeleted, ProductColumnCreatedAt)
	idx2 = idx2.Where("is_deleted = false")

	return ProductsTable{
		Table: schema.NewTable[ProductAlias, ProductColumnAlias, *ProductScanner](
			ProductAliasName,
			func() *ProductScanner { return &ProductScanner{} },
			[]*ddl.ColumnDDL[ProductColumnAlias]{
				idCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
				skuCol.DDL(),
				nameCol.DDL(),
				priceCol.DDL(),
				currencyCol.DDL(),
				stockQtyCol.DDL(),
				isDeletedCol.DDL(),
			},
			ddl.WithIndexes[ProductAlias, ProductColumnAlias](
				idx0,
				idx1,
				idx2,
			),
			ddl.WithSchema[ProductAlias, ProductColumnAlias]("store"),
		),
		Id:        idCol,
		CreatedAt: createdAtCol,
		UpdatedAt: updatedAtCol,
		Sku:       skuCol,
		Name:      nameCol,
		Price:     priceCol,
		Currency:  currencyCol,
		StockQty:  stockQtyCol,
		IsDeleted: isDeletedCol,
	}
}()

// ProductsRef is a reference to the products table for relations
var ProductsRef schema.RelationTableAlias[ProductAlias] = Products.Table

// ProductConverter provides conversion between Product and ProductScanner
var ProductConverter = repository.Converter[*ProductScanner, *Product]{
	ToScanner: (*Product).IntoPlain,
	ToProto:   (*ProductScanner).IntoPb,
}

// OrderAlias is the table alias type for the orders table
type OrderAlias string

func (a OrderAlias) String() string { return string(a) }

const OrderAliasName OrderAlias = "orders"

// OrderColumnAlias represents column names for the orders table
type OrderColumnAlias string

func (c OrderColumnAlias) String() string { return string(c) }

const (
	OrderColumnId        OrderColumnAlias = "id"
	OrderColumnCreatedAt OrderColumnAlias = "created_at"
	OrderColumnUpdatedAt OrderColumnAlias = "updated_at"
	OrderColumnUserId    OrderColumnAlias = "user_id"
	OrderColumnStatus    OrderColumnAlias = "status"
	OrderColumnCurrency  OrderColumnAlias = "currency"
)

func (s *OrderScanner) GetTarget(col string) func() any {
	switch OrderColumnAlias(col) {
	case OrderColumnId:
		return func() any { return &s.Id }
	case OrderColumnCreatedAt:
		return func() any { return &s.CreatedAt }
	case OrderColumnUpdatedAt:
		return func() any { return &s.UpdatedAt }
	case OrderColumnUserId:
		return func() any { return &s.UserId }
	case OrderColumnStatus:
		return func() any { return &s.Status }
	case OrderColumnCurrency:
		return func() any { return &s.Currency }
	default:
		panic("unknown field: " + col)
	}
}

func (s *OrderScanner) GetSetter(f OrderColumnAlias) func() set.ValueSetter[OrderColumnAlias] {
	switch f {
	case OrderColumnId:
		return func() set.ValueSetter[OrderColumnAlias] { return set.NewSetter(f, &s.Id) }
	case OrderColumnCreatedAt:
		return func() set.ValueSetter[OrderColumnAlias] { return set.NewSetter(f, &s.CreatedAt) }
	case OrderColumnUpdatedAt:
		return func() set.ValueSetter[OrderColumnAlias] { return set.NewSetter(f, &s.UpdatedAt) }
	case OrderColumnUserId:
		return func() set.ValueSetter[OrderColumnAlias] { return set.NewSetter(f, &s.UserId) }
	case OrderColumnStatus:
		return func() set.ValueSetter[OrderColumnAlias] { return set.NewSetter(f, &s.Status) }
	case OrderColumnCurrency:
		return func() set.ValueSetter[OrderColumnAlias] { return set.NewSetter(f, &s.Currency) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *OrderScanner) GetValue(f OrderColumnAlias) func() any {
	switch f {
	case OrderColumnId:
		return func() any { return s.Id }
	case OrderColumnCreatedAt:
		return func() any { return s.CreatedAt }
	case OrderColumnUpdatedAt:
		return func() any { return s.UpdatedAt }
	case OrderColumnUserId:
		return func() any { return s.UserId }
	case OrderColumnStatus:
		return func() any { return s.Status }
	case OrderColumnCurrency:
		return func() any { return s.Currency }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the orders table
func (s *OrderScanner) Relations() []exec.RelationLoader[*OrderScanner] {
	return []exec.RelationLoader[*OrderScanner]{
		schema.HasManyLoad(
			OrderOrderItems,
			OrderItems.Table,
			OrderColumnId,
			func(base *OrderScanner, related []*OrderItemScanner) {
				base.Items = make([]OrderItemScanner, len(related))
				for i, r := range related {
					if r != nil {
						base.Items[i] = *r
					}
				}
			},
		),
		schema.BelongsToLoad(
			OrderUser,
			Users.Table,
			OrderColumnUserId,
			func(base *OrderScanner, related *UserScanner) {
				base.User = related
			},
		),
		schema.BelongsToLoad(
			OrderCurrency,
			Currencys.Table,
			OrderColumnCurrency,
			func(base *OrderScanner, related *CurrencyScanner) {
				base.Money = related
			},
		),
	}
}

// ============================================================================
// Order Relation Query Options
// ============================================================================

// OrdersWithItems returns a QueryOption to load Items relation
func OrdersWithItems() exec.QueryOption[OrderColumnAlias, *OrderScanner] {
	return exec.WithRelationLoaders[OrderColumnAlias, *OrderScanner](
		schema.HasManyLoad(
			OrderOrderItems,
			OrderItems.Table,
			OrderColumnId,
			func(base *OrderScanner, related []*OrderItemScanner) {
				base.Items = make([]OrderItemScanner, len(related))
				for i, r := range related {
					if r != nil {
						base.Items[i] = *r
					}
				}
			},
		),
	)
}

// OrdersWithUser returns a QueryOption to load User relation
func OrdersWithUser() exec.QueryOption[OrderColumnAlias, *OrderScanner] {
	return exec.WithRelationLoaders[OrderColumnAlias, *OrderScanner](
		schema.BelongsToLoad(
			OrderUser,
			Users.Table,
			OrderColumnUserId,
			func(base *OrderScanner, related *UserScanner) {
				base.User = related
			},
		),
	)
}

// OrdersWithMoney returns a QueryOption to load Money relation
func OrdersWithMoney() exec.QueryOption[OrderColumnAlias, *OrderScanner] {
	return exec.WithRelationLoaders[OrderColumnAlias, *OrderScanner](
		schema.BelongsToLoad(
			OrderCurrency,
			Currencys.Table,
			OrderColumnCurrency,
			func(base *OrderScanner, related *CurrencyScanner) {
				base.Money = related
			},
		),
	)
}

// OrdersWithAllRelations returns a QueryOption to load all relations
func OrdersWithAllRelations() exec.QueryOption[OrderColumnAlias, *OrderScanner] {
	return exec.WithRelationLoaders[OrderColumnAlias, *OrderScanner](
		schema.HasManyLoad(
			OrderOrderItems,
			OrderItems.Table,
			OrderColumnId,
			func(base *OrderScanner, related []*OrderItemScanner) {
				base.Items = make([]OrderItemScanner, len(related))
				for i, r := range related {
					if r != nil {
						base.Items[i] = *r
					}
				}
			},
		),
		schema.BelongsToLoad(
			OrderUser,
			Users.Table,
			OrderColumnUserId,
			func(base *OrderScanner, related *UserScanner) {
				base.User = related
			},
		),
		schema.BelongsToLoad(
			OrderCurrency,
			Currencys.Table,
			OrderColumnCurrency,
			func(base *OrderScanner, related *CurrencyScanner) {
				base.Money = related
			},
		),
	)
}

// OrdersTable represents the orders table with its columns
type OrdersTable struct {
	*schema.Table[OrderAlias, OrderColumnAlias, *OrderScanner]
	Id        schema.BigSerialColumnI[OrderColumnAlias]
	CreatedAt schema.TimestamptzColumnI[OrderColumnAlias]
	UpdatedAt schema.TimestamptzColumnI[OrderColumnAlias]
	UserId    schema.BigIntColumnI[OrderColumnAlias]
	Status    schema.TextColumnI[OrderColumnAlias]
	Currency  schema.TextColumnI[OrderColumnAlias]
}

// Orders is the global orders table instance
var Orders = func() OrdersTable {
	idCol := schema.BigSerialColumn(OrderColumnId, ddl.WithPrimaryKey[OrderColumnAlias]())
	createdAtCol := schema.TimestamptzColumn(OrderColumnCreatedAt, ddl.WithDefault[OrderColumnAlias]("now()"), ddl.WithNotNull[OrderColumnAlias]())
	updatedAtCol := schema.TimestamptzColumn(OrderColumnUpdatedAt, ddl.WithDefault[OrderColumnAlias]("now()"), ddl.WithNotNull[OrderColumnAlias]())
	userIdCol := schema.BigIntColumn(OrderColumnUserId, ddl.WithReferences[OrderColumnAlias]("\"store\".\"users\"", "id"), ddl.WithOnDelete[OrderColumnAlias]("CASCADE"), ddl.WithNotNull[OrderColumnAlias]())
	statusCol := schema.TextColumn(OrderColumnStatus, ddl.WithDefault[OrderColumnAlias]("'NEW'"), ddl.WithNotNull[OrderColumnAlias]())
	currencyCol := schema.TextColumn(OrderColumnCurrency, ddl.WithReferences[OrderColumnAlias]("currency", "code"), ddl.WithOnDelete[OrderColumnAlias]("RESTRICT"), ddl.WithNotNull[OrderColumnAlias]())

	idx0 := ddl.NewIndex[OrderAlias, OrderColumnAlias]("idx_orders_user_id", OrderAliasName).OnColumns(OrderColumnUserId)
	idx1 := ddl.NewIndex[OrderAlias, OrderColumnAlias]("idx_orders_status", OrderAliasName).OnColumns(OrderColumnStatus)
	idx2 := ddl.NewIndex[OrderAlias, OrderColumnAlias]("idx_orders_created_at", OrderAliasName).OnColumns(OrderColumnCreatedAt)

	return OrdersTable{
		Table: schema.NewTable[OrderAlias, OrderColumnAlias, *OrderScanner](
			OrderAliasName,
			func() *OrderScanner { return &OrderScanner{} },
			[]*ddl.ColumnDDL[OrderColumnAlias]{
				idCol.DDL(),
				createdAtCol.DDL(),
				updatedAtCol.DDL(),
				userIdCol.DDL(),
				statusCol.DDL(),
				currencyCol.DDL(),
			},
			ddl.WithIndexes[OrderAlias, OrderColumnAlias](
				idx0,
				idx1,
				idx2,
			),
			ddl.WithSchema[OrderAlias, OrderColumnAlias]("store"),
			ddl.WithPostStatements[OrderAlias, OrderColumnAlias](
				"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
				"CREATE POLICY orders_own_data ON {table} FOR ALL USING (user_id = current_setting('app.current_user_id')::bigint)",
			),
		),
		Id:        idCol,
		CreatedAt: createdAtCol,
		UpdatedAt: updatedAtCol,
		UserId:    userIdCol,
		Status:    statusCol,
		Currency:  currencyCol,
	}
}()

// OrdersRef is a reference to the orders table for relations
var OrdersRef schema.RelationTableAlias[OrderAlias] = Orders.Table

// OrderConverter provides conversion between Order and OrderScanner
var OrderConverter = repository.Converter[*OrderScanner, *Order]{
	ToScanner: (*Order).IntoPlain,
	ToProto:   (*OrderScanner).IntoPb,
}

// OrderItemAlias is the table alias type for the order_items table
type OrderItemAlias string

func (a OrderItemAlias) String() string { return string(a) }

const OrderItemAliasName OrderItemAlias = "order_items"

// OrderItemColumnAlias represents column names for the order_items table
type OrderItemColumnAlias string

func (c OrderItemColumnAlias) String() string { return string(c) }

const (
	OrderItemColumnOrderId   OrderItemColumnAlias = "order_id"
	OrderItemColumnLineNo    OrderItemColumnAlias = "line_no"
	OrderItemColumnProductId OrderItemColumnAlias = "product_id"
	OrderItemColumnQty       OrderItemColumnAlias = "qty"
	OrderItemColumnUnitPrice OrderItemColumnAlias = "unit_price"
)

func (s *OrderItemScanner) GetTarget(col string) func() any {
	switch OrderItemColumnAlias(col) {
	case OrderItemColumnOrderId:
		return func() any { return &s.OrderId }
	case OrderItemColumnLineNo:
		return func() any { return &s.LineNo }
	case OrderItemColumnProductId:
		return func() any { return &s.ProductId }
	case OrderItemColumnQty:
		return func() any { return &s.Qty }
	case OrderItemColumnUnitPrice:
		return func() any { return &s.UnitPrice }
	default:
		panic("unknown field: " + col)
	}
}

func (s *OrderItemScanner) GetSetter(f OrderItemColumnAlias) func() set.ValueSetter[OrderItemColumnAlias] {
	switch f {
	case OrderItemColumnOrderId:
		return func() set.ValueSetter[OrderItemColumnAlias] { return set.NewSetter(f, &s.OrderId) }
	case OrderItemColumnLineNo:
		return func() set.ValueSetter[OrderItemColumnAlias] { return set.NewSetter(f, &s.LineNo) }
	case OrderItemColumnProductId:
		return func() set.ValueSetter[OrderItemColumnAlias] { return set.NewSetter(f, &s.ProductId) }
	case OrderItemColumnQty:
		return func() set.ValueSetter[OrderItemColumnAlias] { return set.NewSetter(f, &s.Qty) }
	case OrderItemColumnUnitPrice:
		return func() set.ValueSetter[OrderItemColumnAlias] { return set.NewSetter(f, &s.UnitPrice) }
	default:
		panic("unknown field: " + string(f))
	}
}

func (s *OrderItemScanner) GetValue(f OrderItemColumnAlias) func() any {
	switch f {
	case OrderItemColumnOrderId:
		return func() any { return s.OrderId }
	case OrderItemColumnLineNo:
		return func() any { return s.LineNo }
	case OrderItemColumnProductId:
		return func() any { return s.ProductId }
	case OrderItemColumnQty:
		return func() any { return s.Qty }
	case OrderItemColumnUnitPrice:
		return func() any { return s.UnitPrice }
	default:
		panic("unknown field: " + string(f))
	}
}

// Relations returns the relation loaders for the order_items table
func (s *OrderItemScanner) Relations() []exec.RelationLoader[*OrderItemScanner] {
	return []exec.RelationLoader[*OrderItemScanner]{
		schema.BelongsToLoad(
			OrderItemOrder,
			Orders.Table,
			OrderItemColumnOrderId,
			func(base *OrderItemScanner, related *OrderScanner) {
				base.Order = related
			},
		),
		schema.BelongsToLoad(
			OrderItemProduct,
			Products.Table,
			OrderItemColumnProductId,
			func(base *OrderItemScanner, related *ProductScanner) {
				base.Product = related
			},
		),
	}
}

// ============================================================================
// OrderItem Relation Query Options
// ============================================================================

// OrderItemsWithOrder returns a QueryOption to load Order relation
func OrderItemsWithOrder() exec.QueryOption[OrderItemColumnAlias, *OrderItemScanner] {
	return exec.WithRelationLoaders[OrderItemColumnAlias, *OrderItemScanner](
		schema.BelongsToLoad(
			OrderItemOrder,
			Orders.Table,
			OrderItemColumnOrderId,
			func(base *OrderItemScanner, related *OrderScanner) {
				base.Order = related
			},
		),
	)
}

// OrderItemsWithProduct returns a QueryOption to load Product relation
func OrderItemsWithProduct() exec.QueryOption[OrderItemColumnAlias, *OrderItemScanner] {
	return exec.WithRelationLoaders[OrderItemColumnAlias, *OrderItemScanner](
		schema.BelongsToLoad(
			OrderItemProduct,
			Products.Table,
			OrderItemColumnProductId,
			func(base *OrderItemScanner, related *ProductScanner) {
				base.Product = related
			},
		),
	)
}

// OrderItemsWithAllRelations returns a QueryOption to load all relations
func OrderItemsWithAllRelations() exec.QueryOption[OrderItemColumnAlias, *OrderItemScanner] {
	return exec.WithRelationLoaders[OrderItemColumnAlias, *OrderItemScanner](
		schema.BelongsToLoad(
			OrderItemOrder,
			Orders.Table,
			OrderItemColumnOrderId,
			func(base *OrderItemScanner, related *OrderScanner) {
				base.Order = related
			},
		),
		schema.BelongsToLoad(
			OrderItemProduct,
			Products.Table,
			OrderItemColumnProductId,
			func(base *OrderItemScanner, related *ProductScanner) {
				base.Product = related
			},
		),
	)
}

// OrderItemsTable represents the order_items table with its columns
type OrderItemsTable struct {
	*schema.Table[OrderItemAlias, OrderItemColumnAlias, *OrderItemScanner]
	OrderId   schema.BigIntColumnI[OrderItemColumnAlias]
	LineNo    schema.IntegerColumnI[OrderItemColumnAlias]
	ProductId schema.BigIntColumnI[OrderItemColumnAlias]
	Qty       schema.IntegerColumnI[OrderItemColumnAlias]
	UnitPrice schema.DoublePrecisionColumnI[OrderItemColumnAlias]
}

// OrderItems is the global order_items table instance
var OrderItems = func() OrderItemsTable {
	orderIdCol := schema.BigIntColumn(OrderItemColumnOrderId, ddl.WithReferences[OrderItemColumnAlias]("\"store\".\"orders\"", "id"), ddl.WithOnDelete[OrderItemColumnAlias]("CASCADE"), ddl.WithNotNull[OrderItemColumnAlias]())
	lineNoCol := schema.IntegerColumn(OrderItemColumnLineNo, ddl.WithNotNull[OrderItemColumnAlias]())
	productIdCol := schema.BigIntColumn(OrderItemColumnProductId, ddl.WithReferences[OrderItemColumnAlias]("\"store\".\"products\"", "id"), ddl.WithOnDelete[OrderItemColumnAlias]("RESTRICT"), ddl.WithNotNull[OrderItemColumnAlias]())
	qtyCol := schema.IntegerColumn(OrderItemColumnQty, ddl.WithNotNull[OrderItemColumnAlias]())
	unitPriceCol := schema.DoublePrecisionColumn(OrderItemColumnUnitPrice, ddl.WithNotNull[OrderItemColumnAlias]())

	return OrderItemsTable{
		Table: schema.NewTable[OrderItemAlias, OrderItemColumnAlias, *OrderItemScanner](
			OrderItemAliasName,
			func() *OrderItemScanner { return &OrderItemScanner{} },
			[]*ddl.ColumnDDL[OrderItemColumnAlias]{
				orderIdCol.DDL(),
				lineNoCol.DDL(),
				productIdCol.DDL(),
				qtyCol.DDL(),
				unitPriceCol.DDL(),
			},
			ddl.WithUniqueColumns[OrderItemAlias, OrderItemColumnAlias](
				[]OrderItemColumnAlias{OrderItemColumnOrderId, OrderItemColumnProductId},
			),
			ddl.WithPrimaryKeyColumns[OrderItemAlias, OrderItemColumnAlias]([]OrderItemColumnAlias{OrderItemColumnOrderId, OrderItemColumnLineNo}),
			ddl.WithSchema[OrderItemAlias, OrderItemColumnAlias]("store"),
			ddl.WithPostStatements[OrderItemAlias, OrderItemColumnAlias](
				"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
				"CREATE POLICY order_items_own_data ON {table} FOR ALL USING (order_id IN (SELECT o.id FROM \"store\".\"orders\" o WHERE o.user_id = current_setting('app.current_user_id')::bigint))",
			),
		),
		OrderId:   orderIdCol,
		LineNo:    lineNoCol,
		ProductId: productIdCol,
		Qty:       qtyCol,
		UnitPrice: unitPriceCol,
	}
}()

// OrderItemsRef is a reference to the order_items table for relations
var OrderItemsRef schema.RelationTableAlias[OrderItemAlias] = OrderItems.Table

// OrderItemConverter provides conversion between OrderItem and OrderItemScanner
var OrderItemConverter = repository.Converter[*OrderItemScanner, *OrderItem]{
	ToScanner: (*OrderItem).IntoPlain,
	ToProto:   (*OrderItemScanner).IntoPb,
}

// ============================================================================
// User Relations
// ============================================================================

// UserOrders defines the one-to-many relationship: User has many Order
var UserOrders = schema.HasMany[
	UserAlias, UserColumnAlias, *UserScanner,
	OrderAlias, OrderColumnAlias, *OrderScanner,
](
	UserAliasName,
	OrdersRef,
	OrderColumnUserId,
	UserColumnId,
)

// UserProfile defines the one-to-one relationship: User has one Profile
var UserProfile = schema.HasOne[
	UserAlias, UserColumnAlias, *UserScanner,
	ProfileAlias, ProfileColumnAlias, *ProfileScanner,
](
	UserAliasName,
	ProfilesRef,
	ProfileColumnUserId,
	UserColumnId,
)

// ============================================================================
// Profile Relations
// ============================================================================

// ProfileUser defines the belongs-to relationship: Profile belongs to User
var ProfileUser = schema.BelongsTo[
	ProfileAlias, ProfileColumnAlias, *ProfileScanner,
	UserAlias, UserColumnAlias, *UserScanner,
](
	ProfileAliasName,
	UsersRef,
	ProfileColumnUserId,
	UserColumnId,
)

// ============================================================================
// Order Relations
// ============================================================================

// OrderOrderItems defines the one-to-many relationship: Order has many OrderItem
var OrderOrderItems = schema.HasMany[
	OrderAlias, OrderColumnAlias, *OrderScanner,
	OrderItemAlias, OrderItemColumnAlias, *OrderItemScanner,
](
	OrderAliasName,
	OrderItemsRef,
	OrderItemColumnOrderId,
	OrderColumnId,
)

// OrderUser defines the belongs-to relationship: Order belongs to User
var OrderUser = schema.BelongsTo[
	OrderAlias, OrderColumnAlias, *OrderScanner,
	UserAlias, UserColumnAlias, *UserScanner,
](
	OrderAliasName,
	UsersRef,
	OrderColumnUserId,
	UserColumnId,
)

// OrderCurrency defines the belongs-to relationship: Order belongs to Currency
var OrderCurrency = schema.BelongsTo[
	OrderAlias, OrderColumnAlias, *OrderScanner,
	CurrencyAlias, CurrencyColumnAlias, *CurrencyScanner,
](
	OrderAliasName,
	CurrencysRef,
	OrderColumnCurrency,
	CurrencyColumnCode,
)

// ============================================================================
// OrderItem Relations
// ============================================================================

// OrderItemOrder defines the belongs-to relationship: OrderItem belongs to Order
var OrderItemOrder = schema.BelongsTo[
	OrderItemAlias, OrderItemColumnAlias, *OrderItemScanner,
	OrderAlias, OrderColumnAlias, *OrderScanner,
](
	OrderItemAliasName,
	OrdersRef,
	OrderItemColumnOrderId,
	OrderColumnId,
)

// OrderItemProduct defines the belongs-to relationship: OrderItem belongs to Product
var OrderItemProduct = schema.BelongsTo[
	OrderItemAlias, OrderItemColumnAlias, *OrderItemScanner,
	ProductAlias, ProductColumnAlias, *ProductScanner,
](
	OrderItemAliasName,
	ProductsRef,
	OrderItemColumnProductId,
	ProductColumnId,
)

// ============================================================================
// Constraint Names
// ============================================================================

const (
	CurrencyConstraintPkey                 = "currency_pkey"
	UserConstraintPkey                     = "users_pkey"
	UserConstraintEmailKey                 = "users_email_key"
	UserConstraintEmailIdx                 = "idx_users_email"
	ProfileConstraintPkey                  = "profiles_pkey"
	ProfileConstraintUserIdIdx             = "idx_profiles_user_id"
	CategoryConstraintPkey                 = "categories_pkey"
	CategoryConstraintSlugKey              = "categories_slug_key"
	TagConstraintPkey                      = "tags_pkey"
	TagConstraintSlugKey                   = "tags_slug_key"
	ProductConstraintPkey                  = "products_pkey"
	ProductConstraintSkuKey                = "products_sku_key"
	ProductConstraintCheck                 = "products_check"
	OrderConstraintPkey                    = "orders_pkey"
	OrderConstraintCheck                   = "orders_check"
	OrderItemConstraintOrderIdProductIdKey = "order_items_order_id_product_id_key"
	OrderItemConstraintPkey                = "order_items_pkey"
	OrderItemConstraintCheck               = "order_items_check"
	OrderItemConstraintCheck1              = "order_items_check1"
)

// ============================================================================
// Constraint Errors
// ============================================================================

var (
	ErrCurrencyPrimaryKey              = errors.New("primary key constraint violated: currency_pkey")
	ErrUserPrimaryKey                  = errors.New("primary key constraint violated: users_pkey")
	ErrUserEmailUnique                 = errors.New("unique constraint violated: users_email_key")
	ErrUserEmailUniqueIdx              = errors.New("unique constraint violated: idx_users_email")
	ErrProfilePrimaryKey               = errors.New("primary key constraint violated: profiles_pkey")
	ErrProfileUserIdUniqueIdx          = errors.New("unique constraint violated: idx_profiles_user_id")
	ErrCategoryPrimaryKey              = errors.New("primary key constraint violated: categories_pkey")
	ErrCategorySlugUnique              = errors.New("unique constraint violated: categories_slug_key")
	ErrTagPrimaryKey                   = errors.New("primary key constraint violated: tags_pkey")
	ErrTagSlugUnique                   = errors.New("unique constraint violated: tags_slug_key")
	ErrProductPrimaryKey               = errors.New("primary key constraint violated: products_pkey")
	ErrProductSkuUnique                = errors.New("unique constraint violated: products_sku_key")
	ErrProductCheck                    = errors.New("check constraint violated: products_check")
	ErrOrderPrimaryKey                 = errors.New("primary key constraint violated: orders_pkey")
	ErrOrderCheck                      = errors.New("check constraint violated: orders_check")
	ErrOrderItemOrderIdProductIdUnique = errors.New("unique constraint violated: order_items_order_id_product_id_key")
	ErrOrderItemPrimaryKey             = errors.New("primary key constraint violated: order_items_pkey")
	ErrOrderItemCheck                  = errors.New("check constraint violated: order_items_check")
	ErrOrderItemCheck1                 = errors.New("check constraint violated: order_items_check1")
)

// ============================================================================
// Constraint Error Check Functions
// ============================================================================

// IsCurrencyPrimaryKeyError checks if the error is a primary_key constraint violation on currency
func IsCurrencyPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, CurrencyConstraintPkey)
}

// IsUserPrimaryKeyError checks if the error is a primary_key constraint violation on users
func IsUserPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, UserConstraintPkey)
}

// IsUserEmailUniqueError checks if the error is a unique constraint violation on users
func IsUserEmailUniqueError(err error) bool {
	return sqlerr.IsConstraintNamed(err, UserConstraintEmailKey)
}

// IsUserEmailUniqueIdxError checks if the error is a unique constraint violation on users
func IsUserEmailUniqueIdxError(err error) bool {
	return sqlerr.IsConstraintNamed(err, UserConstraintEmailIdx)
}

// IsProfilePrimaryKeyError checks if the error is a primary_key constraint violation on profiles
func IsProfilePrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, ProfileConstraintPkey)
}

// IsProfileUserIdUniqueIdxError checks if the error is a unique constraint violation on profiles
func IsProfileUserIdUniqueIdxError(err error) bool {
	return sqlerr.IsConstraintNamed(err, ProfileConstraintUserIdIdx)
}

// IsCategoryPrimaryKeyError checks if the error is a primary_key constraint violation on categories
func IsCategoryPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, CategoryConstraintPkey)
}

// IsCategorySlugUniqueError checks if the error is a unique constraint violation on categories
func IsCategorySlugUniqueError(err error) bool {
	return sqlerr.IsConstraintNamed(err, CategoryConstraintSlugKey)
}

// IsTagPrimaryKeyError checks if the error is a primary_key constraint violation on tags
func IsTagPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, TagConstraintPkey)
}

// IsTagSlugUniqueError checks if the error is a unique constraint violation on tags
func IsTagSlugUniqueError(err error) bool {
	return sqlerr.IsConstraintNamed(err, TagConstraintSlugKey)
}

// IsProductPrimaryKeyError checks if the error is a primary_key constraint violation on products
func IsProductPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, ProductConstraintPkey)
}

// IsProductSkuUniqueError checks if the error is a unique constraint violation on products
func IsProductSkuUniqueError(err error) bool {
	return sqlerr.IsConstraintNamed(err, ProductConstraintSkuKey)
}

// IsProductCheckError checks if the error is a check constraint violation on products
func IsProductCheckError(err error) bool {
	return sqlerr.IsConstraintNamed(err, ProductConstraintCheck)
}

// IsOrderPrimaryKeyError checks if the error is a primary_key constraint violation on orders
func IsOrderPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, OrderConstraintPkey)
}

// IsOrderCheckError checks if the error is a check constraint violation on orders
func IsOrderCheckError(err error) bool {
	return sqlerr.IsConstraintNamed(err, OrderConstraintCheck)
}

// IsOrderItemOrderIdProductIdUniqueError checks if the error is a unique constraint violation on order_items
func IsOrderItemOrderIdProductIdUniqueError(err error) bool {
	return sqlerr.IsConstraintNamed(err, OrderItemConstraintOrderIdProductIdKey)
}

// IsOrderItemPrimaryKeyError checks if the error is a primary_key constraint violation on order_items
func IsOrderItemPrimaryKeyError(err error) bool {
	return sqlerr.IsConstraintNamed(err, OrderItemConstraintPkey)
}

// IsOrderItemCheckError checks if the error is a check constraint violation on order_items
func IsOrderItemCheckError(err error) bool {
	return sqlerr.IsConstraintNamed(err, OrderItemConstraintCheck)
}

// IsOrderItemCheck1Error checks if the error is a check constraint violation on order_items
func IsOrderItemCheck1Error(err error) bool {
	return sqlerr.IsConstraintNamed(err, OrderItemConstraintCheck1)
}
