// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: examples/proto/store.proto

package storepb

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	_ "github.com/yaroher/ratel/ratelproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserID - type alias для ID пользователя
type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_examples_proto_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{0}
}

func (x *UserID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ProductID - type alias для ID товара
type ProductID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductID) Reset() {
	*x = ProductID{}
	mi := &file_examples_proto_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductID) ProtoMessage() {}

func (x *ProductID) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductID.ProtoReflect.Descriptor instead.
func (*ProductID) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{1}
}

func (x *ProductID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// OrderID - type alias для ID заказа
type OrderID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderID) Reset() {
	*x = OrderID{}
	mi := &file_examples_proto_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderID) ProtoMessage() {}

func (x *OrderID) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderID.ProtoReflect.Descriptor instead.
func (*OrderID) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{2}
}

func (x *OrderID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// CategoryID - type alias для ID категории
type CategoryID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryID) Reset() {
	*x = CategoryID{}
	mi := &file_examples_proto_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryID) ProtoMessage() {}

func (x *CategoryID) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryID.ProtoReflect.Descriptor instead.
func (*CategoryID) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// TagID - type alias для ID тега
type TagID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagID) Reset() {
	*x = TagID{}
	mi := &file_examples_proto_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagID) ProtoMessage() {}

func (x *TagID) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagID.ProtoReflect.Descriptor instead.
func (*TagID) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{4}
}

func (x *TagID) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ============================================================================
// Currency - справочник валют
// ============================================================================
type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_examples_proto_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{5}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ============================================================================
// User - пользователь системы
// ============================================================================
type User struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    *UserID                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email     string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName  string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	IsActive  bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// OneToMany: User has many Orders
	Orders        []*Order `protobuf:"bytes,10,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_examples_proto_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetUserId() *UserID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// ============================================================================
// Category - категория товаров (с иерархией)
// ============================================================================
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    *CategoryID            `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId      *wrapperspb.Int64Value `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_examples_proto_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{7}
}

func (x *Category) GetCategoryId() *CategoryID {
	if x != nil {
		return x.CategoryId
	}
	return nil
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Category) GetParentId() *wrapperspb.Int64Value {
	if x != nil {
		return x.ParentId
	}
	return nil
}

// ============================================================================
// Tag - тег для товаров
// ============================================================================
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagId         *TagID                 `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_examples_proto_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{8}
}

func (x *Tag) GetTagId() *TagID {
	if x != nil {
		return x.TagId
	}
	return nil
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// ============================================================================
// Product - товар
// ============================================================================
type Product struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProductId *ProductID             `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Sku       string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price     float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Currency  string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"` // FK to currency.code
	StockQty  int32                  `protobuf:"varint,6,opt,name=stock_qty,json=stockQty,proto3" json:"stock_qty,omitempty"`
	IsDeleted bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// ManyToMany: Product has many Categories
	Categories []*Category `protobuf:"bytes,10,rep,name=categories,proto3" json:"categories,omitempty"`
	// ManyToMany: Product has many Tags
	Tags          []*Tag `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_examples_proto_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{9}
}

func (x *Product) GetProductId() *ProductID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetStockQty() int32 {
	if x != nil {
		return x.StockQty
	}
	return 0
}

func (x *Product) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ============================================================================
// Order - заказ
// ============================================================================
type Order struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrderId   *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId    *UserID                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // FK to users.user_id
	Status    string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Currency  string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"` // FK to currency.code
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// OneToMany: Order has many OrderItems
	Items         []*OrderItem `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_examples_proto_store_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *Order) GetUserId() *UserID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ============================================================================
// OrderItem - позиция заказа
// ============================================================================
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *OrderID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // FK to orders.order_id
	LineNo        int32                  `protobuf:"varint,2,opt,name=line_no,json=lineNo,proto3" json:"line_no,omitempty"`
	ProductId     *ProductID             `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // FK to products.product_id
	Qty           int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_examples_proto_store_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_store_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_examples_proto_store_proto_rawDescGZIP(), []int{11}
}

func (x *OrderItem) GetOrderId() *OrderID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *OrderItem) GetLineNo() int32 {
	if x != nil {
		return x.LineNo
	}
	return 0
}

func (x *OrderItem) GetProductId() *ProductID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *OrderItem) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

var File_examples_proto_store_proto protoreflect.FileDescriptor

const file_examples_proto_store_proto_rawDesc = "" +
	"\n" +
	"\x1aexamples/proto/store.proto\x12\x05store\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bratelproto/ratelproto.proto\x1a$examples/proto/goplain/goplain.proto\"(\n" +
	"\x06UserID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\"+\n" +
	"\tProductID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\")\n" +
	"\aOrderID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\",\n" +
	"\n" +
	"CategoryID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\"'\n" +
	"\x05TagID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value:\b\x82\xa6\x1d\x04\b\x01\x10\x01\"T\n" +
	"\bCurrency\x12\x1c\n" +
	"\x04code\x18\x01 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name:\x16\x92\xb5\x18\f\b\x01\x12\bcurrency\x82\xa6\x1d\x02\b\x01\"\xa4\x03\n" +
	"\x04User\x120\n" +
	"\auser_id\x18\x01 \x01(\v2\r.store.UserIDB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\x06userId\x12\x1e\n" +
	"\x05email\x18\x02 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12)\n" +
	"\tis_active\x18\x04 \x01(\bB\f\x9a\xb5\x18\b\x12\x06\x1a\x04trueR\bisActive\x12H\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tcreatedAt\x12H\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tupdatedAt\x127\n" +
	"\x06orders\x18\n" +
	" \x03(\v2\f.store.OrderB\x11\xa2\xb5\x18\r\n" +
	"\v\n" +
	"\auser_id\x18\x01R\x06orders:5\x92\xb5\x18+\b\x01\x12\x05users*\a\x12\x05email*\x17\x12\tis_active\x12\n" +
	"created_at\x82\xa6\x1d\x02\b\x01\"\xce\x01\n" +
	"\bCategory\x12<\n" +
	"\vcategory_id\x18\x01 \x01(\v2\x11.store.CategoryIDB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\x04slug\x18\x03 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x04slug\x128\n" +
	"\tparent_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueR\bparentId:\x18\x92\xb5\x18\x0e\b\x01\x12\n" +
	"categories\x82\xa6\x1d\x02\b\x01\"z\n" +
	"\x03Tag\x12-\n" +
	"\x06tag_id\x18\x01 \x01(\v2\f.store.TagIDB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\x05tagId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\x04slug\x18\x03 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x04slug:\x12\x92\xb5\x18\b\b\x01\x12\x04tags\x82\xa6\x1d\x02\b\x01\"\xea\x04\n" +
	"\aProduct\x129\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x10.store.ProductIDB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\tproductId\x12\x1a\n" +
	"\x03sku\x18\x02 \x01(\tB\b\x9a\xb5\x18\x04\x12\x02\b\x01R\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12&\n" +
	"\tstock_qty\x18\x06 \x01(\x05B\t\x9a\xb5\x18\x05\x12\x03\x1a\x010R\bstockQty\x12,\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bB\r\x9a\xb5\x18\t\x12\a\x1a\x05falseR\tisDeleted\x12H\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tcreatedAt\x12H\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tupdatedAt\x12;\n" +
	"\n" +
	"categories\x18\n" +
	" \x03(\v2\x0f.store.CategoryB\n" +
	"\xa2\xb5\x18\x06\x12\x04\x10\x01 \x01R\n" +
	"categories\x12*\n" +
	"\x04tags\x18\v \x03(\v2\n" +
	".store.TagB\n" +
	"\xa2\xb5\x18\x06\x12\x04\x10\x01 \x01R\x04tags:o\x92\xb5\x18e\b\x01\x12\bproducts\"\x16CHECK (stock_qty >= 0)*\x05\x12\x03sku*\n" +
	"\x12\bcurrency*,\x12\n" +
	"is_deleted\x12\n" +
	"created_at\"\x12is_deleted = false\x82\xa6\x1d\x02\b\x01\"\xeb\x03\n" +
	"\x05Order\x123\n" +
	"\border_id\x18\x01 \x01(\v2\x0e.store.OrderIDB\b\x9a\xb5\x18\x04\x12\x02\x10\x01R\aorderId\x12&\n" +
	"\auser_id\x18\x02 \x01(\v2\r.store.UserIDR\x06userId\x12%\n" +
	"\x06status\x18\x03 \x01(\tB\r\x9a\xb5\x18\t\x12\a\x1a\x05'NEW'R\x06status\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12H\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tcreatedAt\x12H\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\r\x9a\xb5\x18\t\x12\a\x1a\x05now()R\tupdatedAt\x12:\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x10.store.OrderItemB\x12\xa2\xb5\x18\x0e\n" +
	"\f\n" +
	"\border_id\x18\x01R\x05items:r\x92\xb5\x18h\b\x01\x12\x06orders\"9CHECK (status IN ('NEW', 'PAID', 'CANCELLED', 'SHIPPED'))*\t\x12\auser_id*\b\x12\x06status*\f\x12\n" +
	"created_at\x82\xa6\x1d\x02\b\x01\"\xb2\x02\n" +
	"\tOrderItem\x12)\n" +
	"\border_id\x18\x01 \x01(\v2\x0e.store.OrderIDR\aorderId\x12\x17\n" +
	"\aline_no\x18\x02 \x01(\x05R\x06lineNo\x12/\n" +
	"\n" +
	"product_id\x18\x03 \x01(\v2\x10.store.ProductIDR\tproductId\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPrice:\x7f\x92\xb5\x18u\b\x01\x12\vorder_items\"\x1fPRIMARY KEY (order_id, line_no)\"\x1dUNIQUE (order_id, product_id)\"\x13CHECK (line_no > 0)\"\x0fCHECK (qty > 0)\x82\xa6\x1d\x02\b\x01B1Z/github.com/yaroher/ratel/examples/proto/storepbb\x06proto3"

var (
	file_examples_proto_store_proto_rawDescOnce sync.Once
	file_examples_proto_store_proto_rawDescData []byte
)

func file_examples_proto_store_proto_rawDescGZIP() []byte {
	file_examples_proto_store_proto_rawDescOnce.Do(func() {
		file_examples_proto_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_proto_store_proto_rawDesc), len(file_examples_proto_store_proto_rawDesc)))
	})
	return file_examples_proto_store_proto_rawDescData
}

var file_examples_proto_store_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_examples_proto_store_proto_goTypes = []any{
	(*UserID)(nil),                // 0: store.UserID
	(*ProductID)(nil),             // 1: store.ProductID
	(*OrderID)(nil),               // 2: store.OrderID
	(*CategoryID)(nil),            // 3: store.CategoryID
	(*TagID)(nil),                 // 4: store.TagID
	(*Currency)(nil),              // 5: store.Currency
	(*User)(nil),                  // 6: store.User
	(*Category)(nil),              // 7: store.Category
	(*Tag)(nil),                   // 8: store.Tag
	(*Product)(nil),               // 9: store.Product
	(*Order)(nil),                 // 10: store.Order
	(*OrderItem)(nil),             // 11: store.OrderItem
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*wrapperspb.Int64Value)(nil), // 13: google.protobuf.Int64Value
}
var file_examples_proto_store_proto_depIdxs = []int32{
	0,  // 0: store.User.user_id:type_name -> store.UserID
	12, // 1: store.User.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: store.User.updated_at:type_name -> google.protobuf.Timestamp
	10, // 3: store.User.orders:type_name -> store.Order
	3,  // 4: store.Category.category_id:type_name -> store.CategoryID
	13, // 5: store.Category.parent_id:type_name -> google.protobuf.Int64Value
	4,  // 6: store.Tag.tag_id:type_name -> store.TagID
	1,  // 7: store.Product.product_id:type_name -> store.ProductID
	12, // 8: store.Product.created_at:type_name -> google.protobuf.Timestamp
	12, // 9: store.Product.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 10: store.Product.categories:type_name -> store.Category
	8,  // 11: store.Product.tags:type_name -> store.Tag
	2,  // 12: store.Order.order_id:type_name -> store.OrderID
	0,  // 13: store.Order.user_id:type_name -> store.UserID
	12, // 14: store.Order.created_at:type_name -> google.protobuf.Timestamp
	12, // 15: store.Order.updated_at:type_name -> google.protobuf.Timestamp
	11, // 16: store.Order.items:type_name -> store.OrderItem
	2,  // 17: store.OrderItem.order_id:type_name -> store.OrderID
	1,  // 18: store.OrderItem.product_id:type_name -> store.ProductID
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_examples_proto_store_proto_init() }
func file_examples_proto_store_proto_init() {
	if File_examples_proto_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_proto_store_proto_rawDesc), len(file_examples_proto_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_proto_store_proto_goTypes,
		DependencyIndexes: file_examples_proto_store_proto_depIdxs,
		MessageInfos:      file_examples_proto_store_proto_msgTypes,
	}.Build()
	File_examples_proto_store_proto = out.File
	file_examples_proto_store_proto_goTypes = nil
	file_examples_proto_store_proto_depIdxs = nil
}
