// Code generated by protoc-gen-go-plain. DO NOT EDIT.
// source: examples/proto/store.proto

package storepb

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// ============================================================================
//
//	Currency - справочник валют
//	============================================================================
type CurrencyScanner struct {
	Code string `json:"code"`
	Name string `json:"name"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Currency) IntoPlain() *CurrencyScanner {
	if pb == nil {
		return nil
	}
	p := &CurrencyScanner{}

	p.Code = pb.Code
	p.Src_ = append(p.Src_, 0)
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 1)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *CurrencyScanner) IntoPb() *Currency {
	if p == nil {
		return nil
	}
	pb := &Currency{}

	pb.Code = p.Code
	pb.Name = p.Name
	return pb
}

// ============================================================================
//
//	User - пользователь системы
//	============================================================================
type UserScanner struct {
	UserId    int64                  `json:"userId"`
	Email     string                 `json:"email"`
	FullName  string                 `json:"fullName"`
	IsActive  bool                   `json:"isActive"`
	CreatedAt *timestamppb.Timestamp `json:"createdAt"`
	UpdatedAt *timestamppb.Timestamp `json:"updatedAt"`
	Orders    []OrderScanner         `json:"orders"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *User) IntoPlain() *UserScanner {
	if pb == nil {
		return nil
	}
	p := &UserScanner{}

	p.UserId = pb.UserId
	p.Src_ = append(p.Src_, 0)
	p.Email = pb.Email
	p.Src_ = append(p.Src_, 1)
	p.FullName = pb.FullName
	p.Src_ = append(p.Src_, 2)
	p.IsActive = pb.IsActive
	p.Src_ = append(p.Src_, 3)
	p.CreatedAt = pb.CreatedAt
	p.Src_ = append(p.Src_, 4)
	p.UpdatedAt = pb.UpdatedAt
	p.Src_ = append(p.Src_, 5)
	if len(pb.Orders) > 0 {
		p.Orders = make([]OrderScanner, len(pb.Orders))
		for i, v := range pb.Orders {
			if v != nil {
				p.Orders[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 6)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *UserScanner) IntoPb() *User {
	if p == nil {
		return nil
	}
	pb := &User{}

	pb.UserId = p.UserId
	pb.Email = p.Email
	pb.FullName = p.FullName
	pb.IsActive = p.IsActive
	pb.CreatedAt = p.CreatedAt
	pb.UpdatedAt = p.UpdatedAt
	if len(p.Orders) > 0 {
		pb.Orders = make([]*Order, len(p.Orders))
		for i := range p.Orders {
			pb.Orders[i] = (&p.Orders[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	Category - категория товаров (с иерархией)
//	============================================================================
type CategoryScanner struct {
	CategoryId int64                  `json:"categoryId"`
	Name       string                 `json:"name"`
	Slug       string                 `json:"slug"`
	ParentId   *wrapperspb.Int64Value `json:"parentId"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Category) IntoPlain() *CategoryScanner {
	if pb == nil {
		return nil
	}
	p := &CategoryScanner{}

	p.CategoryId = pb.CategoryId
	p.Src_ = append(p.Src_, 0)
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 1)
	p.Slug = pb.Slug
	p.Src_ = append(p.Src_, 2)
	p.ParentId = pb.ParentId
	p.Src_ = append(p.Src_, 3)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *CategoryScanner) IntoPb() *Category {
	if p == nil {
		return nil
	}
	pb := &Category{}

	pb.CategoryId = p.CategoryId
	pb.Name = p.Name
	pb.Slug = p.Slug
	pb.ParentId = p.ParentId
	return pb
}

// ============================================================================
//
//	Tag - тег для товаров
//	============================================================================
type TagScanner struct {
	TagId int64  `json:"tagId"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Tag) IntoPlain() *TagScanner {
	if pb == nil {
		return nil
	}
	p := &TagScanner{}

	p.TagId = pb.TagId
	p.Src_ = append(p.Src_, 0)
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 1)
	p.Slug = pb.Slug
	p.Src_ = append(p.Src_, 2)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *TagScanner) IntoPb() *Tag {
	if p == nil {
		return nil
	}
	pb := &Tag{}

	pb.TagId = p.TagId
	pb.Name = p.Name
	pb.Slug = p.Slug
	return pb
}

// ============================================================================
//
//	Product - товар
//	============================================================================
type ProductScanner struct {
	ProductId  int64                  `json:"productId"`
	Sku        string                 `json:"sku"`
	Name       string                 `json:"name"`
	Price      float64                `json:"price"`
	Currency   string                 `json:"currency"`
	StockQty   int32                  `json:"stockQty"`
	IsDeleted  bool                   `json:"isDeleted"`
	CreatedAt  *timestamppb.Timestamp `json:"createdAt"`
	UpdatedAt  *timestamppb.Timestamp `json:"updatedAt"`
	Categories []CategoryScanner      `json:"categories"`
	Tags       []TagScanner           `json:"tags"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Product) IntoPlain() *ProductScanner {
	if pb == nil {
		return nil
	}
	p := &ProductScanner{}

	p.ProductId = pb.ProductId
	p.Src_ = append(p.Src_, 0)
	p.Sku = pb.Sku
	p.Src_ = append(p.Src_, 1)
	p.Name = pb.Name
	p.Src_ = append(p.Src_, 2)
	p.Price = pb.Price
	p.Src_ = append(p.Src_, 3)
	p.Currency = pb.Currency
	p.Src_ = append(p.Src_, 4)
	p.StockQty = pb.StockQty
	p.Src_ = append(p.Src_, 5)
	p.IsDeleted = pb.IsDeleted
	p.Src_ = append(p.Src_, 6)
	p.CreatedAt = pb.CreatedAt
	p.Src_ = append(p.Src_, 7)
	p.UpdatedAt = pb.UpdatedAt
	p.Src_ = append(p.Src_, 8)
	if len(pb.Categories) > 0 {
		p.Categories = make([]CategoryScanner, len(pb.Categories))
		for i, v := range pb.Categories {
			if v != nil {
				p.Categories[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 9)
	}
	if len(pb.Tags) > 0 {
		p.Tags = make([]TagScanner, len(pb.Tags))
		for i, v := range pb.Tags {
			if v != nil {
				p.Tags[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 10)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *ProductScanner) IntoPb() *Product {
	if p == nil {
		return nil
	}
	pb := &Product{}

	pb.ProductId = p.ProductId
	pb.Sku = p.Sku
	pb.Name = p.Name
	pb.Price = p.Price
	pb.Currency = p.Currency
	pb.StockQty = p.StockQty
	pb.IsDeleted = p.IsDeleted
	pb.CreatedAt = p.CreatedAt
	pb.UpdatedAt = p.UpdatedAt
	if len(p.Categories) > 0 {
		pb.Categories = make([]*Category, len(p.Categories))
		for i := range p.Categories {
			pb.Categories[i] = (&p.Categories[i]).IntoPb()
		}
	}
	if len(p.Tags) > 0 {
		pb.Tags = make([]*Tag, len(p.Tags))
		for i := range p.Tags {
			pb.Tags[i] = (&p.Tags[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	Order - заказ
//	============================================================================
type OrderScanner struct {
	OrderId   int64                  `json:"orderId"`
	UserId    int64                  `json:"userId"`
	Status    string                 `json:"status"`
	Currency  string                 `json:"currency"`
	CreatedAt *timestamppb.Timestamp `json:"createdAt"`
	UpdatedAt *timestamppb.Timestamp `json:"updatedAt"`
	Items     []OrderItemScanner     `json:"items"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *Order) IntoPlain() *OrderScanner {
	if pb == nil {
		return nil
	}
	p := &OrderScanner{}

	p.OrderId = pb.OrderId
	p.Src_ = append(p.Src_, 0)
	p.UserId = pb.UserId
	p.Src_ = append(p.Src_, 1)
	p.Status = pb.Status
	p.Src_ = append(p.Src_, 2)
	p.Currency = pb.Currency
	p.Src_ = append(p.Src_, 3)
	p.CreatedAt = pb.CreatedAt
	p.Src_ = append(p.Src_, 4)
	p.UpdatedAt = pb.UpdatedAt
	p.Src_ = append(p.Src_, 5)
	if len(pb.Items) > 0 {
		p.Items = make([]OrderItemScanner, len(pb.Items))
		for i, v := range pb.Items {
			if v != nil {
				p.Items[i] = *v.IntoPlain()
			}
		}
		p.Src_ = append(p.Src_, 6)
	}
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *OrderScanner) IntoPb() *Order {
	if p == nil {
		return nil
	}
	pb := &Order{}

	pb.OrderId = p.OrderId
	pb.UserId = p.UserId
	pb.Status = p.Status
	pb.Currency = p.Currency
	pb.CreatedAt = p.CreatedAt
	pb.UpdatedAt = p.UpdatedAt
	if len(p.Items) > 0 {
		pb.Items = make([]*OrderItem, len(p.Items))
		for i := range p.Items {
			pb.Items[i] = (&p.Items[i]).IntoPb()
		}
	}
	return pb
}

// ============================================================================
//
//	OrderItem - позиция заказа
//	============================================================================
type OrderItemScanner struct {
	OrderId   int64   `json:"orderId"`
	LineNo    int32   `json:"lineNo"`
	ProductId int64   `json:"productId"`
	Qty       int32   `json:"qty"`
	UnitPrice float64 `json:"unitPrice"`
	// Src_ contains indices of populated fields for sparse serialization
	Src_ []uint16 `json:"_src,omitempty"`
}

// IntoPlain converts protobuf message to plain struct
func (pb *OrderItem) IntoPlain() *OrderItemScanner {
	if pb == nil {
		return nil
	}
	p := &OrderItemScanner{}

	p.OrderId = pb.OrderId
	p.Src_ = append(p.Src_, 0)
	p.LineNo = pb.LineNo
	p.Src_ = append(p.Src_, 1)
	p.ProductId = pb.ProductId
	p.Src_ = append(p.Src_, 2)
	p.Qty = pb.Qty
	p.Src_ = append(p.Src_, 3)
	p.UnitPrice = pb.UnitPrice
	p.Src_ = append(p.Src_, 4)
	return p
}

// IntoPb converts plain struct to protobuf message
func (p *OrderItemScanner) IntoPb() *OrderItem {
	if p == nil {
		return nil
	}
	pb := &OrderItem{}

	pb.OrderId = p.OrderId
	pb.LineNo = p.LineNo
	pb.ProductId = p.ProductId
	pb.Qty = p.Qty
	pb.UnitPrice = p.UnitPrice
	return pb
}
