version: 2

builds:
  - id: ratel
    main: ./cmd/ratel
    binary: ratel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: protoc-gen-ratel
    main: ./cmd/protoc-gen-ratel
    binary: protoc-gen-ratel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  use: github
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^Merge"
      - "^ci:"
      - "^chore:"
      - "^test:"
