package main

import (
	"github.com/iancoleman/strcase"
	"google.golang.org/protobuf/compiler/protogen"
)

// generateRatelFile generates the _ratel.pb.go file
func generateRatelFile(p *protogen.Plugin, f *protogen.File, tables []*RatelTable) error {
	filename := f.GeneratedFilenamePrefix + "_ratel.pb.go"
	gf := p.NewGeneratedFile(filename, f.GoImportPath)

	// Header
	gf.P("// Code generated by protoc-gen-ratel. DO NOT EDIT.")
	gf.P("// source: ", f.Desc.Path())
	gf.P()
	gf.P("package ", f.GoPackageName)
	gf.P()

	// Imports
	gf.P("import (")
	gf.P("\t\"time\"")
	gf.P()
	gf.P("\t\"github.com/yaroher/ratel/pkg/ddl\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/dml/set\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/exec\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/schema\"")
	gf.P(")")
	gf.P()

	// Suppress unused import warning
	gf.P("var _ = time.Time{}")
	gf.P()

	// Generate code for each table
	for _, table := range tables {
		if err := generateTableCode(gf, table); err != nil {
			return err
		}
	}

	return nil
}

// generateTableCode generates code for a single table
func generateTableCode(gf *protogen.GeneratedFile, table *RatelTable) error {
	msgName := table.Message.GoIdent.GoName
	tableName := getTableName(table)

	// 1. Generate table alias type
	aliasTypeName := msgName + "Alias"
	gf.P("// ", aliasTypeName, " is the table alias type for the ", tableName, " table")
	gf.P("type ", aliasTypeName, " string")
	gf.P()
	gf.P("func (a ", aliasTypeName, ") String() string { return string(a) }")
	gf.P()
	gf.P("const ", aliasTypeName, "Name ", aliasTypeName, " = \"", tableName, "\"")
	gf.P()

	// 2. Generate column alias type
	colAliasTypeName := msgName + "ColumnAlias"
	gf.P("// ", colAliasTypeName, " represents column names for the ", tableName, " table")
	gf.P("type ", colAliasTypeName, " string")
	gf.P()
	gf.P("func (c ", colAliasTypeName, ") String() string { return string(c) }")
	gf.P()

	// 3. Generate column alias constants
	gf.P("const (")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		gf.P("\t", constName, " ", colAliasTypeName, " = \"", col.SQLName, "\"")
	}
	gf.P(")")
	gf.P()

	// Scanner struct is generated by protoc-gen-go-plain in _plain.pb.go
	// Here we only generate methods that extend the Scanner for ratel
	scannerTypeName := msgName + "Scanner"

	// 4. Generate GetTarget method
	gf.P("func (s *", scannerTypeName, ") GetTarget(col string) func() any {")
	gf.P("\tswitch ", colAliasTypeName, "(col) {")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		fieldName := col.GoName
		gf.P("\tcase ", constName, ":")
		gf.P("\t\treturn func() any { return &s.", fieldName, " }")
	}
	gf.P("\tdefault:")
	gf.P("\t\tpanic(\"unknown field: \" + col)")
	gf.P("\t}")
	gf.P("}")
	gf.P()

	// 5. Generate GetSetter method
	gf.P("func (s *", scannerTypeName, ") GetSetter(f ", colAliasTypeName, ") func() set.ValueSetter[", colAliasTypeName, "] {")
	gf.P("\tswitch f {")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		fieldName := col.GoName
		gf.P("\tcase ", constName, ":")
		gf.P("\t\treturn func() set.ValueSetter[", colAliasTypeName, "] { return set.NewSetter(f, &s.", fieldName, ") }")
	}
	gf.P("\tdefault:")
	gf.P("\t\tpanic(\"unknown field: \" + string(f))")
	gf.P("\t}")
	gf.P("}")
	gf.P()

	// 6. Generate GetValue method
	gf.P("func (s *", scannerTypeName, ") GetValue(f ", colAliasTypeName, ") func() any {")
	gf.P("\tswitch f {")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		fieldName := col.GoName
		gf.P("\tcase ", constName, ":")
		gf.P("\t\treturn func() any { return s.", fieldName, " }")
	}
	gf.P("\tdefault:")
	gf.P("\t\tpanic(\"unknown field: \" + string(f))")
	gf.P("\t}")
	gf.P("}")
	gf.P()

	// 7. Generate Relations method stub
	gf.P("// Relations returns the relation loaders for the ", tableName, " table")
	gf.P("func (s *", scannerTypeName, ") Relations() []exec.RelationLoader[*", scannerTypeName, "] {")
	gf.P("\treturn nil // TODO: generate relations")
	gf.P("}")
	gf.P()

	// 8. Generate table struct type
	tableStructName := msgName + "sTable"
	gf.P("// ", tableStructName, " represents the ", tableName, " table with its columns")
	gf.P("type ", tableStructName, " struct {")
	gf.P("\t*schema.Table[", aliasTypeName, ", ", colAliasTypeName, ", *", scannerTypeName, "]")
	for _, col := range table.Columns {
		fieldName := col.GoName
		colType := getSchemaColumnType(col, msgName)
		gf.P("\t", fieldName, " ", colType)
	}
	gf.P("}")
	gf.P()

	// 10. Generate table variable
	tableVarName := msgName + "s"
	gf.P("// ", tableVarName, " is the global ", tableName, " table instance")
	gf.P("var ", tableVarName, " = func() ", tableStructName, " {")

	// Column variable declarations
	for _, col := range table.Columns {
		fieldName := strcase.ToLowerCamel(col.GoName) + "Col"
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		constructor := getSchemaColumnConstructor(col, constName, msgName)
		gf.P("\t", fieldName, " := ", constructor)
	}
	gf.P()

	// Return table struct
	gf.P("\treturn ", tableStructName, "{")
	gf.P("\t\tTable: schema.NewTable[", aliasTypeName, ", ", colAliasTypeName, ", *", scannerTypeName, "](")
	gf.P("\t\t\t", aliasTypeName, "Name,")
	gf.P("\t\t\tfunc() *", scannerTypeName, " { return &", scannerTypeName, "{} },")
	gf.P("\t\t\t[]*ddl.ColumnDDL[", colAliasTypeName, "]{")
	for _, col := range table.Columns {
		fieldName := strcase.ToLowerCamel(col.GoName) + "Col"
		gf.P("\t\t\t\t", fieldName, ".DDL(),")
	}
	gf.P("\t\t\t},")
	gf.P("\t\t),")

	// Column fields
	for _, col := range table.Columns {
		fieldName := strcase.ToLowerCamel(col.GoName) + "Col"
		gf.P("\t\t", col.GoName, ": ", fieldName, ",")
	}
	gf.P("\t}")
	gf.P("}()")
	gf.P()

	// 11. Generate table ref for relations
	gf.P("// ", tableVarName, "Ref is a reference to the ", tableName, " table for relations")
	gf.P("var ", tableVarName, "Ref schema.RelationTableAlias[", aliasTypeName, "] = ", tableVarName, ".Table")
	gf.P()

	return nil
}
