package main

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/yaroher/protoc-gen-go-plain/generator"
	"google.golang.org/protobuf/compiler/protogen"
)

// generateRatelFile generates the _ratel.pb.go file
func generateRatelFile(p *protogen.Plugin, f *protogen.File, tables []*RatelTable, gen *generator.Generator) error {
	_ = gen // used in generateConverter via messageHasCasterFields

	filename := f.GeneratedFilenamePrefix + "_ratel.pb.go"
	gf := p.NewGeneratedFile(filename, f.GoImportPath)

	// Header
	gf.P("// Code generated by protoc-gen-ratel. DO NOT EDIT.")
	gf.P("// source: ", f.Desc.Path())
	gf.P()
	gf.P("package ", f.GoPackageName)
	gf.P()

	// Imports
	gf.P("import (")
	gf.P("\t\"errors\"")
	gf.P("\t\"time\"")
	gf.P()
	gf.P("\t\"github.com/yaroher/ratel/pkg/ddl\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/dml/set\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/exec\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/pgx-ext/sqlerr\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/repository\"")
	gf.P("\t\"github.com/yaroher/ratel/pkg/schema\"")
	gf.P(")")
	gf.P()

	// Suppress unused import warnings
	gf.P("var (")
	gf.P("\t_ = time.Time{}")
	gf.P("\t_ = errors.New")
	gf.P("\t_ = sqlerr.IsConstraintNamed")
	gf.P(")")
	gf.P()

	// Generate additional SQL statements from file-level options
	generateAdditionalSQL(gf, f)

	// First pass: generate table code
	for _, table := range tables {
		if err := generateTableCode(gf, table, gen); err != nil {
			return err
		}
	}

	// Second pass: generate relations (after all tables are defined)
	for _, table := range tables {
		relations := parseRelations(table)
		generateRelationVariables(gf, table, relations)
	}

	// Third pass: generate constraint errors
	generateConstraintErrors(gf, tables)

	return nil
}

// generateAdditionalSQL generates a slice of ddl.RawSQL from file-level
// additional_code options so they can be passed to ddl.SchemaSQL.
func generateAdditionalSQL(gf *protogen.GeneratedFile, f *protogen.File) {
	stmts := getAdditionalCode(f)
	if len(stmts) == 0 {
		return
	}

	gf.P("// ============================================================================")
	gf.P("// Additional SQL Statements (file-level)")
	gf.P("// ============================================================================")
	gf.P()
	gf.P("// AdditionalSQL contains raw SQL statements declared via additional_code")
	gf.P("// file option. Pass these to ddl.SchemaSQL() alongside table definitions.")
	gf.P("var AdditionalSQL = []ddl.SchemaSqler{")
	for _, stmt := range stmts {
		gf.P("\tddl.RawSQL(", strconv.Quote(stmt), "),")
	}
	gf.P("}")
	gf.P()
}

// generateConstraintErrors generates constraint-related code for all tables
func generateConstraintErrors(gf *protogen.GeneratedFile, tables []*RatelTable) {
	// Collect all constraints from all tables
	var allConstraints []*ConstraintInfo
	for _, table := range tables {
		constraints := collectConstraints(table)
		allConstraints = append(allConstraints, constraints...)
	}

	if len(allConstraints) == 0 {
		return
	}

	// Generate constraint names section
	gf.P("// ============================================================================")
	gf.P("// Constraint Names")
	gf.P("// ============================================================================")
	gf.P()
	gf.P("const (")
	for _, c := range allConstraints {
		gf.P("\t", c.GoConstName, " = \"", c.Name, "\"")
	}
	gf.P(")")
	gf.P()

	// Generate sentinel errors section
	gf.P("// ============================================================================")
	gf.P("// Constraint Errors")
	gf.P("// ============================================================================")
	gf.P()
	gf.P("var (")
	for _, c := range allConstraints {
		errMsg := constraintErrorMessage(c)
		gf.P("\t", c.GoErrorName, " = errors.New(\"", errMsg, "\")")
	}
	gf.P(")")
	gf.P()

	// Generate error check functions section
	gf.P("// ============================================================================")
	gf.P("// Constraint Error Check Functions")
	gf.P("// ============================================================================")
	gf.P()
	for _, c := range allConstraints {
		gf.P("// ", c.GoCheckFunc, " checks if the error is a ", c.Type, " constraint violation on ", c.Table)
		gf.P("func ", c.GoCheckFunc, "(err error) bool {")
		gf.P("\treturn sqlerr.IsConstraintNamed(err, ", c.GoConstName, ")")
		gf.P("}")
		gf.P()
	}
}

// constraintErrorMessage generates a human-readable error message for a constraint
func constraintErrorMessage(c *ConstraintInfo) string {
	switch c.Type {
	case ConstraintTypeUnique:
		return fmt.Sprintf("unique constraint violated: %s", c.Name)
	case ConstraintTypePrimaryKey:
		return fmt.Sprintf("primary key constraint violated: %s", c.Name)
	case ConstraintTypeForeignKey:
		return fmt.Sprintf("foreign key constraint violated: %s", c.Name)
	case ConstraintTypeCheck:
		return fmt.Sprintf("check constraint violated: %s", c.Name)
	default:
		return fmt.Sprintf("constraint violated: %s", c.Name)
	}
}

// generateTableCode generates code for a single table
func generateTableCode(gf *protogen.GeneratedFile, table *RatelTable, gen *generator.Generator) error {
	msgName := table.Message.GoIdent.GoName
	tableName := getTableName(table)
	tableSchema := getTableSchema(table)

	// 1. Generate table alias type
	aliasTypeName := msgName + "Alias"
	gf.P("// ", aliasTypeName, " is the table alias type for the ", tableName, " table")
	gf.P("type ", aliasTypeName, " string")
	gf.P()
	gf.P("func (a ", aliasTypeName, ") String() string { return string(a) }")
	gf.P()
	gf.P("const ", aliasTypeName, "Name ", aliasTypeName, " = \"", tableName, "\"")
	gf.P()

	// 2. Generate column alias type
	colAliasTypeName := msgName + "ColumnAlias"
	gf.P("// ", colAliasTypeName, " represents column names for the ", tableName, " table")
	gf.P("type ", colAliasTypeName, " string")
	gf.P()
	gf.P("func (c ", colAliasTypeName, ") String() string { return string(c) }")
	gf.P()

	// 3. Generate column alias constants
	gf.P("const (")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		gf.P("\t", constName, " ", colAliasTypeName, " = \"", col.SQLName, "\"")
	}
	gf.P(")")
	gf.P()

	// Scanner struct is generated by protoc-gen-go-plain in _plain.pb.go
	// Here we only generate methods that extend the Scanner for ratel
	scannerTypeName := msgName + "Scanner"

	// 4. Generate GetTarget method
	gf.P("func (s *", scannerTypeName, ") GetTarget(col string) func() any {")
	gf.P("\tswitch ", colAliasTypeName, "(col) {")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		fieldName := col.GoName
		gf.P("\tcase ", constName, ":")
		gf.P("\t\treturn func() any { return &s.", fieldName, " }")
	}
	gf.P("\tdefault:")
	gf.P("\t\tpanic(\"unknown field: \" + col)")
	gf.P("\t}")
	gf.P("}")
	gf.P()

	// 5. Generate GetSetter method
	gf.P("func (s *", scannerTypeName, ") GetSetter(f ", colAliasTypeName, ") func() set.ValueSetter[", colAliasTypeName, "] {")
	gf.P("\tswitch f {")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		fieldName := col.GoName
		gf.P("\tcase ", constName, ":")
		gf.P("\t\treturn func() set.ValueSetter[", colAliasTypeName, "] { return set.NewSetter(f, &s.", fieldName, ") }")
	}
	gf.P("\tdefault:")
	gf.P("\t\tpanic(\"unknown field: \" + string(f))")
	gf.P("\t}")
	gf.P("}")
	gf.P()

	// 6. Generate GetValue method
	gf.P("func (s *", scannerTypeName, ") GetValue(f ", colAliasTypeName, ") func() any {")
	gf.P("\tswitch f {")
	for _, col := range table.Columns {
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		fieldName := col.GoName
		gf.P("\tcase ", constName, ":")
		gf.P("\t\treturn func() any { return s.", fieldName, " }")
	}
	gf.P("\tdefault:")
	gf.P("\t\tpanic(\"unknown field: \" + string(f))")
	gf.P("\t}")
	gf.P("}")
	gf.P()

	// 7. Generate Relations method
	relations := parseRelations(table)
	generateRelationsMethod(gf, table, relations)

	// 7.1 Generate relation query options (UsersWithOrders, etc.)
	generateRelationOptions(gf, table, relations)

	// 8. Generate table struct type
	tableStructName := msgName + "sTable"
	gf.P("// ", tableStructName, " represents the ", tableName, " table with its columns")
	gf.P("type ", tableStructName, " struct {")
	gf.P("\t*schema.Table[", aliasTypeName, ", ", colAliasTypeName, ", *", scannerTypeName, "]")
	for _, col := range table.Columns {
		fieldName := col.GoName
		colType := getSchemaColumnType(col, msgName)
		gf.P("\t", fieldName, " ", colType)
	}
	gf.P("}")
	gf.P()

	// 10. Generate table variable
	tableVarName := msgName + "s"
	gf.P("// ", tableVarName, " is the global ", tableName, " table instance")
	gf.P("var ", tableVarName, " = func() ", tableStructName, " {")

	// Column variable declarations
	for _, col := range table.Columns {
		fieldName := strcase.ToLowerCamel(col.GoName) + "Col"
		constName := msgName + "Column" + strcase.ToCamel(string(col.Field.Desc.Name()))
		constructor := getSchemaColumnConstructor(col, constName, msgName)
		gf.P("\t", fieldName, " := ", constructor)
	}
	gf.P()

	// Generate indexes if any
	hasIndexes := table.Options != nil && len(table.Options.Indexes) > 0
	if hasIndexes {
		for i, idx := range table.Options.Indexes {
			idxName := idx.Name
			if idxName == "" {
				// Auto-generate index name: idx_<table>_<columns>
				idxName = "idx_" + tableName + "_" + strings.Join(idx.Columns, "_")
			}
			idxVarName := fmt.Sprintf("idx%d", i)

			// Build column constants list
			colConsts := make([]string, 0, len(idx.Columns))
			for _, colName := range idx.Columns {
				colConsts = append(colConsts, msgName+"Column"+strcase.ToCamel(colName))
			}

			gf.P("\t", idxVarName, " := ddl.NewIndex[", aliasTypeName, ", ", colAliasTypeName, "](\"", idxName, "\", ", aliasTypeName, "Name).OnColumns(", strings.Join(colConsts, ", "), ")")

			// Add unique if needed
			if idx.Unique {
				gf.P("\t", idxVarName, " = ", idxVarName, ".Unique()")
			}

			// Add WHERE clause if needed
			if idx.Where != "" {
				gf.P("\t", idxVarName, " = ", idxVarName, ".Where(\"", idx.Where, "\")")
			}

			// Add USING method if specified
			if idx.Using != "" {
				gf.P("\t", idxVarName, " = ", idxVarName, ".Using(\"", idx.Using, "\")")
			}
		}
		gf.P()
	}

	// Return table struct
	gf.P("\treturn ", tableStructName, "{")
	gf.P("\t\tTable: schema.NewTable[", aliasTypeName, ", ", colAliasTypeName, ", *", scannerTypeName, "](")
	gf.P("\t\t\t", aliasTypeName, "Name,")
	gf.P("\t\t\tfunc() *", scannerTypeName, " { return &", scannerTypeName, "{} },")
	gf.P("\t\t\t[]*ddl.ColumnDDL[", colAliasTypeName, "]{")
	for _, col := range table.Columns {
		fieldName := strcase.ToLowerCamel(col.GoName) + "Col"
		gf.P("\t\t\t\t", fieldName, ".DDL(),")
	}
	gf.P("\t\t\t},")

	// Add indexes option if any
	if hasIndexes {
		gf.P("\t\t\tddl.WithIndexes[", aliasTypeName, ", ", colAliasTypeName, "](")
		for i := range table.Options.Indexes {
			idxVarName := fmt.Sprintf("idx%d", i)
			gf.P("\t\t\t\t", idxVarName, ",")
		}
		gf.P("\t\t\t),")
	}

	// Add unique constraints if any
	hasUnique := table.Options != nil && len(table.Options.Unique) > 0
	if hasUnique {
		gf.P("\t\t\tddl.WithUniqueColumns[", aliasTypeName, ", ", colAliasTypeName, "](")
		for _, uq := range table.Options.Unique {
			colConsts := make([]string, 0, len(uq.Columns))
			for _, colName := range uq.Columns {
				colConsts = append(colConsts, msgName+"Column"+strcase.ToCamel(colName))
			}
			gf.P("\t\t\t\t[]", colAliasTypeName, "{", strings.Join(colConsts, ", "), "},")
		}
		gf.P("\t\t\t),")
	}

	// Add composite primary key if any
	hasPK := table.Options != nil && table.Options.PrimaryKey != nil && len(table.Options.PrimaryKey.Columns) > 0
	if hasPK {
		pkColConsts := make([]string, 0, len(table.Options.PrimaryKey.Columns))
		for _, colName := range table.Options.PrimaryKey.Columns {
			pkColConsts = append(pkColConsts, msgName+"Column"+strcase.ToCamel(colName))
		}
		gf.P("\t\t\tddl.WithPrimaryKeyColumns[", aliasTypeName, ", ", colAliasTypeName, "]([]", colAliasTypeName, "{", strings.Join(pkColConsts, ", "), "}),")
	}

	// Add schema if specified
	if tableSchema != "" {
		gf.P("\t\t\tddl.WithSchema[", aliasTypeName, ", ", colAliasTypeName, "](\"", tableSchema, "\"),")
	}

	// Add post-table statements if any
	if table.Options != nil && len(table.Options.PostStatements) > 0 {
		gf.P("\t\t\tddl.WithPostStatements[", aliasTypeName, ", ", colAliasTypeName, "](")
		for _, stmt := range table.Options.PostStatements {
			gf.P("\t\t\t\t", strconv.Quote(stmt), ",")
		}
		gf.P("\t\t\t),")
	}

	gf.P("\t\t),")

	// Column fields
	for _, col := range table.Columns {
		fieldName := strcase.ToLowerCamel(col.GoName) + "Col"
		gf.P("\t\t", col.GoName, ": ", fieldName, ",")
	}
	gf.P("\t}")
	gf.P("}()")
	gf.P()

	// 11. Generate table ref for relations
	gf.P("// ", tableVarName, "Ref is a reference to the ", tableName, " table for relations")
	gf.P("var ", tableVarName, "Ref schema.RelationTableAlias[", aliasTypeName, "] = ", tableVarName, ".Table")
	gf.P()

	// 12. Generate Converter for repository
	generateConverter(gf, table, gen)

	return nil
}

// generateConverter generates the Converter struct for proto <-> scanner conversion
func generateConverter(gf *protogen.GeneratedFile, table *RatelTable, gen *generator.Generator) {
	msgName := table.Message.GoIdent.GoName
	scannerTypeName := msgName + "Scanner"

	// Check if message has caster fields (fields requiring parameter-based casters)
	hasCasters := messageHasCasterFields(table.Message, gen)

	gf.P("// ", msgName, "Converter provides conversion between ", msgName, " and ", scannerTypeName)
	if hasCasters {
		// Generate with casters struct
		castersTypeName := scannerTypeName + "Casters"
		gf.P("func ", msgName, "ConverterWith(c *", castersTypeName, ") repository.Converter[*", scannerTypeName, ", *", msgName, "] {")
		gf.P("\treturn repository.Converter[*", scannerTypeName, ", *", msgName, "]{")
		gf.P("\t\tToScanner: func(pb *", msgName, ") *", scannerTypeName, " { return pb.IntoPlain(c) },")
		gf.P("\t\tToProto:   func(p *", scannerTypeName, ") *", msgName, " { return p.IntoPb(c) },")
		gf.P("\t}")
		gf.P("}")
	} else {
		gf.P("var ", msgName, "Converter = repository.Converter[*", scannerTypeName, ", *", msgName, "]{")
		gf.P("\tToScanner: (*", msgName, ").IntoPlain,")
		gf.P("\tToProto:   (*", scannerTypeName, ").IntoPb,")
		gf.P("}")
	}
	gf.P()
}

// messageHasCasterFields checks if a message has parameter-based caster fields
// (fields requiring casters that are NOT covered by existing/pre-defined casters).
// Uses the IR already built by go-plain during Generate().
func messageHasCasterFields(msg *protogen.Message, gen *generator.Generator) bool {
	if gen == nil {
		return false
	}
	irMsg := gen.GetIRMessage(msg)
	if irMsg == nil {
		return false
	}
	return len(gen.CollectCasterFields(irMsg)) > 0
}
