package commands

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

var (
	schemaInputPkg   string
	schemaOutputFile string
	schemaTables     []string
	schemaDiscover   bool
)

var schemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Generate SQL schema from Go models package",
	Long: `Generate a SQL schema file by importing Go models and calling ddl.SchemaStatements().

Example:
  ratel schema -p github.com/myproject/models -t Users,Products,Orders -o schema.sql
  ratel schema -p github.com/myproject/models --discover -o schema.sql

This creates a temporary Go program that imports your models package and generates
the SQL schema using the actual table definitions.`,
	Run: runSchema,
}

func init() {
	rootCmd.AddCommand(schemaCmd)

	schemaCmd.Flags().StringVarP(&schemaInputPkg, "package", "p", "", "Go package path containing models (required)")
	schemaCmd.Flags().StringSliceVarP(&schemaTables, "tables", "t", nil, "Table variable names to include (e.g., Users,Products)")
	schemaCmd.Flags().BoolVarP(&schemaDiscover, "discover", "d", false, "Auto-discover tables from source files")
	schemaCmd.Flags().StringVarP(&schemaOutputFile, "output", "o", "schema.sql", "Output SQL schema file")
	schemaCmd.MarkFlagRequired("package")
}

func runSchema(cmd *cobra.Command, args []string) {
	tables := schemaTables

	// Find workspace root (where go.mod is)
	workspaceRoot := mustGetWorkspaceRoot()

	// Auto-discover tables if requested
	if schemaDiscover || len(tables) == 0 {
		discovered, err := discoverTables(schemaInputPkg, workspaceRoot)
		if err != nil {
			exitWithError("failed to discover tables: %v", err)
		}
		if len(discovered) == 0 {
			exitWithError("no tables discovered in package %s", schemaInputPkg)
		}
		tables = discovered
		fmt.Printf("Discovered tables: %v\n", tables)
	}

	if len(tables) == 0 {
		exitWithError("no tables specified. Use -t or --discover")
	}

	// Create temporary Go file in workspace (so imports resolve correctly)
	tmpFile, err := os.CreateTemp(workspaceRoot, "ratel_schema_gen_*.go")
	if err != nil {
		exitWithError("failed to create temp file: %v", err)
	}
	tmpFileName := tmpFile.Name()
	defer os.Remove(tmpFileName)

	// Generate the temporary Go program
	program := generateSchemaProgram(schemaInputPkg, tables)

	if _, err := tmpFile.WriteString(program); err != nil {
		tmpFile.Close()
		exitWithError("failed to write temp program: %v", err)
	}
	tmpFile.Close()

	// Run the program from workspace root
	runCmd := exec.Command("go", "run", tmpFileName)
	runCmd.Dir = workspaceRoot
	runCmd.Stderr = os.Stderr
	output, err := runCmd.Output()
	if err != nil {
		exitWithError("failed to run schema generator: %v", err)
	}

	// Write output to file
	outputPath := schemaOutputFile
	if !filepath.IsAbs(outputPath) {
		// Make relative to current directory, not workspace root
		cwd, _ := os.Getwd()
		outputPath = filepath.Join(cwd, outputPath)
	}

	if err := os.WriteFile(outputPath, output, 0644); err != nil {
		exitWithError("failed to write output file: %v", err)
	}

	fmt.Printf("Generated %s with %d table(s)\n", schemaOutputFile, len(tables))
}

func generateSchemaProgram(pkg string, tables []string) string {
	var tableArgs strings.Builder
	for i, t := range tables {
		if i > 0 {
			tableArgs.WriteString(",\n\t\t")
		}
		tableArgs.WriteString("models.")
		tableArgs.WriteString(t)
	}

	return fmt.Sprintf(`//go:build ignore

package main

import (
	"fmt"
	"strings"

	models "%s"
	"github.com/yaroher/ratel/pkg/ddl"
)

func main() {
	statements := ddl.SchemaStatements(
		%s,
	)

	fmt.Println("-- Generated by ratel schema")
	fmt.Println("-- DO NOT EDIT")
	fmt.Println()
	fmt.Println(strings.Join(statements, ";\n") + ";")
}
`, pkg, tableArgs.String())
}

func discoverTables(pkg, workspaceRoot string) ([]string, error) {
	// Find the package directory
	pkgDir, err := findPackageDir(pkg, workspaceRoot)
	if err != nil {
		return nil, err
	}

	// Read all Go files and look for table variables
	files, err := filepath.Glob(filepath.Join(pkgDir, "*.go"))
	if err != nil {
		return nil, err
	}

	var tables []string
	// Match: var Users = func() UsersTable {
	// or: var Currencys = func() CurrencysTable {
	tablePattern := regexp.MustCompile(`var\s+(\w+)\s*=\s*func\(\)\s+\w+Table\s*\{`)

	for _, file := range files {
		// Skip test files
		if strings.HasSuffix(file, "_test.go") {
			continue
		}

		content, err := os.ReadFile(file)
		if err != nil {
			continue
		}

		matches := tablePattern.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) >= 2 {
				// Skip Ref variables
				if !strings.HasSuffix(match[1], "Ref") {
					tables = append(tables, match[1])
				}
			}
		}
	}

	return tables, nil
}

func findPackageDir(pkg, workspaceRoot string) (string, error) {
	// Check if package is relative to workspace
	// e.g., github.com/yaroher/ratel/examples/proto -> examples/proto
	modPath := getModulePath(workspaceRoot)
	if modPath != "" && strings.HasPrefix(pkg, modPath) {
		relPath := strings.TrimPrefix(pkg, modPath)
		relPath = strings.TrimPrefix(relPath, "/")
		pkgDir := filepath.Join(workspaceRoot, relPath)
		if _, err := os.Stat(pkgDir); err == nil {
			return pkgDir, nil
		}
	}

	return "", fmt.Errorf("package %s not found in workspace", pkg)
}

func getModulePath(dir string) string {
	modFile := filepath.Join(dir, "go.mod")
	content, err := os.ReadFile(modFile)
	if err != nil {
		return ""
	}

	// Extract module path from go.mod
	lines := strings.Split(string(content), "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

func mustGetWorkspaceRoot() string {
	// Get current working directory
	cwd, err := os.Getwd()
	if err != nil {
		exitWithError("failed to get current directory: %v", err)
	}

	// Walk up to find go.mod
	dir := cwd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	exitWithError("go.mod not found in any parent directory")
	return ""
}
