package commands

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/spf13/cobra"
)

var (
	schemaInputDir   string
	schemaOutputFile string
)

var schemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Generate SQL schema from Go models directory",
	Long: `Generate a SQL schema file from Go model files.

Example:
  ratel schema -i ./models -o schema.sql

This will parse all Go model files in the input directory and generate
a SQL schema file with CREATE TABLE and CREATE INDEX statements.`,
	Run: runSchema,
}

func init() {
	rootCmd.AddCommand(schemaCmd)

	schemaCmd.Flags().StringVarP(&schemaInputDir, "input", "i", "./models", "Input directory containing Go model files")
	schemaCmd.Flags().StringVarP(&schemaOutputFile, "output", "o", "schema.sql", "Output SQL schema file")
}

type parsedTable struct {
	name       string
	order      int // for sorting by dependency
	columns    []parsedColumn
	indexes    []parsedIndex
	primaryKey []string
	unique     [][]string
}

type parsedColumn struct {
	name       string
	sqlType    string
	notNull    bool
	primaryKey bool
	unique     bool
	defValue   string
	check      string
	references string
	onDelete   string
}

type parsedIndex struct {
	name    string
	columns []string
	where   string
	unique  bool
}

func runSchema(cmd *cobra.Command, args []string) {
	// Find all Go files in input directory
	files, err := filepath.Glob(filepath.Join(schemaInputDir, "*.go"))
	if err != nil {
		exitWithError("failed to list Go files: %v", err)
	}

	if len(files) == 0 {
		exitWithError("no Go files found in %s", schemaInputDir)
	}

	// Parse all Go files
	var tables []parsedTable
	tableOrder := make(map[string]int)

	for _, file := range files {
		// Skip relations.go and test files
		base := filepath.Base(file)
		if base == "relations.go" || strings.HasSuffix(base, "_test.go") {
			continue
		}

		parsed, err := parseGoModelFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to parse %s: %v\n", file, err)
			continue
		}

		if parsed != nil {
			tables = append(tables, *parsed)
			tableOrder[parsed.name] = len(tables)
		}
	}

	if len(tables) == 0 {
		exitWithError("no tables found in %s", schemaInputDir)
	}

	// Sort tables by dependency (tables with foreign keys come after referenced tables)
	sortTablesByDependency(tables, tableOrder)

	// Generate SQL
	var sql strings.Builder
	sql.WriteString("-- Generated by ratel\n")
	sql.WriteString("-- DO NOT EDIT\n\n")

	for i, table := range tables {
		if i > 0 {
			sql.WriteString("\n")
		}
		sql.WriteString(generateCreateTable(table))
		for _, idx := range table.indexes {
			sql.WriteString(generateCreateIndex(table.name, idx))
		}
	}

	// Write output file
	if err := os.WriteFile(schemaOutputFile, []byte(sql.String()), 0644); err != nil {
		exitWithError("failed to write output file: %v", err)
	}

	fmt.Printf("Generated %s with %d table(s)\n", schemaOutputFile, len(tables))
}

func parseGoModelFile(filename string) (*parsedTable, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var table *parsedTable

	ast.Inspect(node, func(n ast.Node) bool {
		// Look for variable declarations like: var Users = func() UsersTable { ... }()
		genDecl, ok := n.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.VAR {
			return true
		}

		for _, spec := range genDecl.Specs {
			valueSpec, ok := spec.(*ast.ValueSpec)
			if !ok || len(valueSpec.Names) == 0 {
				continue
			}

			varName := valueSpec.Names[0].Name
			// Skip Ref variables
			if strings.HasSuffix(varName, "Ref") {
				continue
			}

			// Look for the initialization expression
			if len(valueSpec.Values) == 0 {
				continue
			}

			// Try to extract table info from the source
			table = extractTableFromSource(filename, varName)
		}

		return true
	})

	return table, nil
}

func extractTableFromSource(filename, varName string) *parsedTable {
	content, err := os.ReadFile(filename)
	if err != nil {
		return nil
	}

	source := string(content)

	// Find table name from AliasName constant
	aliasPattern := regexp.MustCompile(varName + `AliasName\s+` + varName + `Alias\s*=\s*"(\w+)"`)
	aliasMatch := aliasPattern.FindStringSubmatch(source)
	if len(aliasMatch) < 2 {
		return nil
	}

	tableName := aliasMatch[1]
	table := &parsedTable{name: tableName}

	// Extract columns from the column creation calls
	columnPattern := regexp.MustCompile(`(\w+)Col\s*:=\s*schema\.(\w+Column)\(([^)]+(?:\([^)]*\)[^)]*)*)\)`)
	columnMatches := columnPattern.FindAllStringSubmatch(source, -1)

	for _, match := range columnMatches {
		if len(match) < 4 {
			continue
		}

		colVarName := match[1]
		colType := match[2]
		colArgs := match[3]

		col := parsedColumn{
			name:    extractColumnName(source, varName, colVarName),
			sqlType: columnTypeToSQL(colType, colArgs),
		}

		// Parse column options
		col.notNull = strings.Contains(colArgs, "WithNotNull")
		col.primaryKey = strings.Contains(colArgs, "WithPrimaryKey")
		col.unique = strings.Contains(colArgs, "WithUnique")

		if idx := strings.Index(colArgs, "WithDefault"); idx != -1 {
			col.defValue = extractStringArg(colArgs[idx:])
		}
		if idx := strings.Index(colArgs, "WithCheck"); idx != -1 {
			col.check = extractStringArg(colArgs[idx:])
		}
		if idx := strings.Index(colArgs, "WithReferences"); idx != -1 {
			col.references = extractReferencesArg(colArgs[idx:])
		}
		if idx := strings.Index(colArgs, "WithOnDelete"); idx != -1 {
			col.onDelete = extractStringArg(colArgs[idx:])
		}

		table.columns = append(table.columns, col)
	}

	// Extract indexes
	indexPattern := regexp.MustCompile(`ddl\.NewIndex\[[^\]]+\]\("([^"]+)",\s*\w+AliasName\)\.OnColumns\(([^)]+)\)(?:\.Where\("([^"]+)"\))?`)
	indexMatches := indexPattern.FindAllStringSubmatch(source, -1)

	for _, match := range indexMatches {
		if len(match) < 3 {
			continue
		}

		idx := parsedIndex{
			name: match[1],
		}

		// Parse column names
		colsStr := match[2]
		colPattern := regexp.MustCompile(`(\w+)Column(\w+)`)
		colMatches := colPattern.FindAllStringSubmatch(colsStr, -1)
		for _, cm := range colMatches {
			if len(cm) >= 3 {
				idx.columns = append(idx.columns, toSnakeCase(cm[2]))
			}
		}

		if len(match) > 3 && match[3] != "" {
			idx.where = match[3]
		}

		table.indexes = append(table.indexes, idx)
	}

	// Extract composite primary key
	pkPattern := regexp.MustCompile(`WithPrimaryKeyColumns\[[^\]]+\]\(\[\]\w+\{([^}]+)\}\)`)
	pkMatch := pkPattern.FindStringSubmatch(source)
	if len(pkMatch) >= 2 {
		colPattern := regexp.MustCompile(`\w+Column(\w+)`)
		colMatches := colPattern.FindAllStringSubmatch(pkMatch[1], -1)
		for _, cm := range colMatches {
			if len(cm) >= 2 {
				table.primaryKey = append(table.primaryKey, toSnakeCase(cm[1]))
			}
		}
	}

	// Extract unique constraints
	ucPattern := regexp.MustCompile(`WithUniqueColumns\[[^\]]+\]\(\[\]\w+\{([^}]+)\}\)`)
	ucMatches := ucPattern.FindAllStringSubmatch(source, -1)
	for _, ucMatch := range ucMatches {
		if len(ucMatch) >= 2 {
			var cols []string
			colPattern := regexp.MustCompile(`\w+Column(\w+)`)
			colMatches := colPattern.FindAllStringSubmatch(ucMatch[1], -1)
			for _, cm := range colMatches {
				if len(cm) >= 2 {
					cols = append(cols, toSnakeCase(cm[1]))
				}
			}
			if len(cols) > 0 {
				table.unique = append(table.unique, cols)
			}
		}
	}

	return table
}

func extractColumnName(source, tableName, colVarName string) string {
	// Look for the constant definition
	pattern := regexp.MustCompile(tableName + `Column(\w+)\s+` + tableName + `ColumnAlias\s*=\s*"(\w+)"`)
	matches := pattern.FindAllStringSubmatch(source, -1)

	pascalName := toPascalCase(colVarName)
	for _, match := range matches {
		if len(match) >= 3 && match[1] == pascalName {
			return match[2]
		}
	}

	return toSnakeCase(colVarName)
}

func columnTypeToSQL(colType, args string) string {
	// Extract precision/scale from args
	precisionPattern := regexp.MustCompile(`\w+Column\w+,\s*(\d+)(?:,\s*(\d+))?`)
	precMatch := precisionPattern.FindStringSubmatch(args)

	var precision, scale string
	if len(precMatch) >= 2 {
		precision = precMatch[1]
	}
	if len(precMatch) >= 3 {
		scale = precMatch[2]
	}

	switch colType {
	case "BigSerialColumn":
		return "BIGSERIAL"
	case "SerialColumn":
		return "SERIAL"
	case "SmallSerialColumn":
		return "SMALLSERIAL"
	case "BigIntColumn":
		return "BIGINT"
	case "IntegerColumn":
		return "INTEGER"
	case "SmallIntColumn":
		return "SMALLINT"
	case "BooleanColumn":
		return "BOOLEAN"
	case "TextColumn":
		return "TEXT"
	case "VarcharColumn":
		if precision != "" {
			return fmt.Sprintf("VARCHAR(%s)", precision)
		}
		return "VARCHAR"
	case "CharColumn":
		if precision != "" {
			return fmt.Sprintf("CHAR(%s)", precision)
		}
		return "CHAR"
	case "NumericColumn":
		if precision != "" && scale != "" {
			return fmt.Sprintf("NUMERIC(%s, %s)", precision, scale)
		} else if precision != "" {
			return fmt.Sprintf("NUMERIC(%s)", precision)
		}
		return "NUMERIC"
	case "RealColumn":
		return "REAL"
	case "DoubleColumn":
		return "DOUBLE PRECISION"
	case "TimestamptzColumn":
		return "TIMESTAMPTZ"
	case "TimestampColumn":
		return "TIMESTAMP"
	case "DateColumn":
		return "DATE"
	case "TimeColumn":
		return "TIME"
	case "TimetzColumn":
		return "TIMETZ"
	case "UUIDColumn":
		return "UUID"
	case "ByteaColumn":
		return "BYTEA"
	case "JSONColumn":
		return "JSON"
	case "JSONBColumn":
		return "JSONB"
	default:
		return "TEXT"
	}
}

func extractStringArg(s string) string {
	// Find first quoted string
	pattern := regexp.MustCompile(`"([^"]*)"`)
	match := pattern.FindStringSubmatch(s)
	if len(match) >= 2 {
		return match[1]
	}
	return ""
}

func extractReferencesArg(s string) string {
	// Extract table and column from WithReferences("table", "column")
	pattern := regexp.MustCompile(`"(\w+)",\s*"(\w+)"`)
	match := pattern.FindStringSubmatch(s)
	if len(match) >= 3 {
		return fmt.Sprintf("%s(%s)", match[1], match[2])
	}
	return ""
}

func sortTablesByDependency(tables []parsedTable, orderMap map[string]int) {
	// Build dependency graph
	deps := make(map[string][]string)
	for _, t := range tables {
		for _, col := range t.columns {
			if col.references != "" {
				// Extract referenced table name
				idx := strings.Index(col.references, "(")
				if idx > 0 {
					refTable := col.references[:idx]
					deps[t.name] = append(deps[t.name], refTable)
				}
			}
		}
	}

	// Topological sort
	sort.Slice(tables, func(i, j int) bool {
		// If j depends on i, i should come first
		for _, dep := range deps[tables[j].name] {
			if dep == tables[i].name {
				return true
			}
		}
		// If i depends on j, j should come first
		for _, dep := range deps[tables[i].name] {
			if dep == tables[j].name {
				return false
			}
		}
		// Otherwise, maintain original order
		return orderMap[tables[i].name] < orderMap[tables[j].name]
	})
}

func generateCreateTable(table parsedTable) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", table.name))

	for i, col := range table.columns {
		if i > 0 {
			b.WriteString(",\n")
		}
		b.WriteString(fmt.Sprintf("  %s %s", col.name, col.sqlType))

		if col.primaryKey {
			b.WriteString(" PRIMARY KEY")
		}
		if col.notNull || col.primaryKey || strings.Contains(col.sqlType, "SERIAL") {
			if !col.primaryKey {
				b.WriteString(" NOT NULL")
			}
		}
		if col.unique {
			b.WriteString(" UNIQUE")
		}
		if col.defValue != "" {
			b.WriteString(fmt.Sprintf(" DEFAULT %s", col.defValue))
		}
		if col.check != "" {
			b.WriteString(fmt.Sprintf(" CHECK (%s)", col.check))
		}
		if col.references != "" {
			b.WriteString(fmt.Sprintf(" REFERENCES %s", col.references))
		}
		if col.onDelete != "" {
			b.WriteString(fmt.Sprintf(" ON DELETE %s", col.onDelete))
		}
	}

	// Composite primary key
	if len(table.primaryKey) > 0 {
		b.WriteString(fmt.Sprintf(",\n  PRIMARY KEY (%s)", strings.Join(table.primaryKey, ", ")))
	}

	// Unique constraints
	for _, uc := range table.unique {
		b.WriteString(fmt.Sprintf(",\n  UNIQUE (%s)", strings.Join(uc, ", ")))
	}

	b.WriteString("\n);\n")

	return b.String()
}

func generateCreateIndex(tableName string, idx parsedIndex) string {
	var b strings.Builder

	if idx.unique {
		b.WriteString("CREATE UNIQUE INDEX IF NOT EXISTS ")
	} else {
		b.WriteString("CREATE INDEX IF NOT EXISTS ")
	}

	b.WriteString(fmt.Sprintf("%s ON %s (%s)", idx.name, tableName, strings.Join(idx.columns, ", ")))

	if idx.where != "" {
		b.WriteString(fmt.Sprintf(" WHERE %s", idx.where))
	}

	b.WriteString(";\n")

	return b.String()
}

func toSnakeCase(s string) string {
	return strcase.ToSnake(s)
}
