// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: ratelproto.proto

package ratelproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate table schema for this message
	Generate bool `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	// Override table name (default: snake_case of message name)
	TableName *string `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3,oneof" json:"table_name,omitempty"`
	// Virtual fields (columns not in proto message)
	VirtualColumns []*VirtualColumn `protobuf:"bytes,3,rep,name=virtual_columns,json=virtualColumns,proto3" json:"virtual_columns,omitempty"`
	// Table-level constraints (e.g., "CHECK (x > 0)")
	Constraints []string `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// Indexes
	Indexes []*Index `protobuf:"bytes,5,rep,name=indexes,proto3" json:"indexes,omitempty"`
	// Composite unique constraints
	// Example: unique: [{ columns: ["order_id", "product_id"] }]
	Unique []*UniqueConstraint `protobuf:"bytes,6,rep,name=unique,proto3" json:"unique,omitempty"`
	// Composite primary key (overrides column-level primary_key)
	// Example: primary_key: { columns: ["order_id", "line_no"] }
	PrimaryKey *PrimaryKey `protobuf:"bytes,7,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// PostgreSQL schema name (default: "public")
	// When set, generates CREATE SCHEMA IF NOT EXISTS and uses qualified table names
	// Example: schema: "auth" -> creates table "auth"."users"
	Schema *string `protobuf:"bytes,8,opt,name=schema,proto3,oneof" json:"schema,omitempty"`
	// Raw SQL statements executed after CREATE TABLE.
	// Use {table} placeholder for schema-qualified table name.
	// Example: post_statements: [
	//
	//	"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY",
	//	"GRANT ALL ON {table} TO authenticated"
	//
	// ]
	PostStatements []string `protobuf:"bytes,9,rep,name=post_statements,json=postStatements,proto3" json:"post_statements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_ratelproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

func (x *Table) GetTableName() string {
	if x != nil && x.TableName != nil {
		return *x.TableName
	}
	return ""
}

func (x *Table) GetVirtualColumns() []*VirtualColumn {
	if x != nil {
		return x.VirtualColumns
	}
	return nil
}

func (x *Table) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Table) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *Table) GetUnique() []*UniqueConstraint {
	if x != nil {
		return x.Unique
	}
	return nil
}

func (x *Table) GetPrimaryKey() *PrimaryKey {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *Table) GetSchema() string {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return ""
}

func (x *Table) GetPostStatements() []string {
	if x != nil {
		return x.PostStatements
	}
	return nil
}

// Composite unique constraint
type UniqueConstraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Constraint name (auto-generated if empty: uq_<table>_<columns>)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Columns in the unique constraint
	Columns       []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueConstraint) Reset() {
	*x = UniqueConstraint{}
	mi := &file_ratelproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueConstraint) ProtoMessage() {}

func (x *UniqueConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueConstraint.ProtoReflect.Descriptor instead.
func (*UniqueConstraint) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{1}
}

func (x *UniqueConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UniqueConstraint) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Composite primary key
type PrimaryKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Columns in the primary key
	Columns       []string `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimaryKey) Reset() {
	*x = PrimaryKey{}
	mi := &file_ratelproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimaryKey) ProtoMessage() {}

func (x *PrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimaryKey.ProtoReflect.Descriptor instead.
func (*PrimaryKey) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{2}
}

func (x *PrimaryKey) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

type Index struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index name (auto-generated if empty: idx_<table>_<columns>)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Columns to index
	Columns []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Unique index
	Unique bool `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	// Partial index WHERE clause (e.g., "is_deleted = false")
	Where string `protobuf:"bytes,4,opt,name=where,proto3" json:"where,omitempty"`
	// Index method: btree (default), hash, gin, gist, spgist, brin
	Using string `protobuf:"bytes,5,opt,name=using,proto3" json:"using,omitempty"`
	// Include columns (INCLUDE clause for covering indexes)
	Include []string `protobuf:"bytes,6,rep,name=include,proto3" json:"include,omitempty"`
	// Expression columns (e.g., "lower(email)", "created_at::date")
	// Use instead of 'columns' for expression-based indexes
	Expressions []string `protobuf:"bytes,7,rep,name=expressions,proto3" json:"expressions,omitempty"`
	// Concurrent index creation (CREATE INDEX CONCURRENTLY)
	Concurrent    bool `protobuf:"varint,8,opt,name=concurrent,proto3" json:"concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_ratelproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{3}
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Index) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Index) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *Index) GetUsing() string {
	if x != nil {
		return x.Using
	}
	return ""
}

func (x *Index) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *Index) GetExpressions() []string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *Index) GetConcurrent() bool {
	if x != nil {
		return x.Concurrent
	}
	return false
}

type Constraint struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Unique       bool                   `protobuf:"varint,1,opt,name=unique,proto3" json:"unique,omitempty"`
	PrimaryKey   bool                   `protobuf:"varint,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	DefaultValue string                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Raw SQL constraint (overrides above if set)
	Raw string `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`
	// CHECK expression, combinable with other constraints
	// Example: check: "id <> ”"  →  CHECK (id <> ”)
	Check         string `protobuf:"bytes,5,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_ratelproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{4}
}

func (x *Constraint) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Constraint) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Constraint) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *Constraint) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *Constraint) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

type VirtualColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqlName       string                 `protobuf:"bytes,1,opt,name=sql_name,json=sqlName,proto3" json:"sql_name,omitempty"`
	SqlType       string                 `protobuf:"bytes,2,opt,name=sql_type,json=sqlType,proto3" json:"sql_type,omitempty"` // e.g., "BIGINT", "TEXT", "TIMESTAMPTZ"
	Constraints   *Constraint            `protobuf:"bytes,3,opt,name=constraints,proto3" json:"constraints,omitempty"`
	IsNullable    bool                   `protobuf:"varint,4,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	IsArray       bool                   `protobuf:"varint,5,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualColumn) Reset() {
	*x = VirtualColumn{}
	mi := &file_ratelproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualColumn) ProtoMessage() {}

func (x *VirtualColumn) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualColumn.ProtoReflect.Descriptor instead.
func (*VirtualColumn) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{5}
}

func (x *VirtualColumn) GetSqlName() string {
	if x != nil {
		return x.SqlName
	}
	return ""
}

func (x *VirtualColumn) GetSqlType() string {
	if x != nil {
		return x.SqlType
	}
	return ""
}

func (x *VirtualColumn) GetConstraints() *Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *VirtualColumn) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *VirtualColumn) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skip this field in table generation
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// Column constraints
	Constraints   *Constraint `protobuf:"bytes,2,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_ratelproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{6}
}

func (x *Column) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *Column) GetConstraints() *Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// OneToMany: Parent has many Children (e.g., User has many Orders)
// The FK column is in the related (child) table
type OneToMany struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FK column name in related table (default: <table>_id)
	RefName string `protobuf:"bytes,1,opt,name=ref_name,json=refName,proto3" json:"ref_name,omitempty"`
	// Raw constraint for FK (overrides default REFERENCES)
	Constraint string `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
	// Add ON DELETE CASCADE
	OnDeleteCascade bool `protobuf:"varint,3,opt,name=on_delete_cascade,json=onDeleteCascade,proto3" json:"on_delete_cascade,omitempty"`
	// FK column already exists in related table (don't create virtual)
	ExistedField  bool `protobuf:"varint,4,opt,name=existed_field,json=existedField,proto3" json:"existed_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneToMany) Reset() {
	*x = OneToMany{}
	mi := &file_ratelproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneToMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneToMany) ProtoMessage() {}

func (x *OneToMany) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneToMany.ProtoReflect.Descriptor instead.
func (*OneToMany) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{7}
}

func (x *OneToMany) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *OneToMany) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *OneToMany) GetOnDeleteCascade() bool {
	if x != nil {
		return x.OnDeleteCascade
	}
	return false
}

func (x *OneToMany) GetExistedField() bool {
	if x != nil {
		return x.ExistedField
	}
	return false
}

// HasOne: Parent has one Child (e.g., User has one Profile)
// Similar to OneToMany but returns single record instead of slice
type HasOne struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FK column name in related table (default: <table>_id)
	RefName string `protobuf:"bytes,1,opt,name=ref_name,json=refName,proto3" json:"ref_name,omitempty"`
	// Raw constraint for FK (overrides default REFERENCES)
	Constraint string `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
	// Add ON DELETE CASCADE
	OnDeleteCascade bool `protobuf:"varint,3,opt,name=on_delete_cascade,json=onDeleteCascade,proto3" json:"on_delete_cascade,omitempty"`
	// Add ON DELETE SET NULL
	OnDeleteSetNull bool `protobuf:"varint,4,opt,name=on_delete_set_null,json=onDeleteSetNull,proto3" json:"on_delete_set_null,omitempty"`
	// FK column already exists in related table (don't create virtual)
	ExistedField  bool `protobuf:"varint,5,opt,name=existed_field,json=existedField,proto3" json:"existed_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasOne) Reset() {
	*x = HasOne{}
	mi := &file_ratelproto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasOne) ProtoMessage() {}

func (x *HasOne) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasOne.ProtoReflect.Descriptor instead.
func (*HasOne) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{8}
}

func (x *HasOne) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *HasOne) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *HasOne) GetOnDeleteCascade() bool {
	if x != nil {
		return x.OnDeleteCascade
	}
	return false
}

func (x *HasOne) GetOnDeleteSetNull() bool {
	if x != nil {
		return x.OnDeleteSetNull
	}
	return false
}

func (x *HasOne) GetExistedField() bool {
	if x != nil {
		return x.ExistedField
	}
	return false
}

// BelongsTo: Child belongs to Parent (e.g., Order belongs to User)
// The FK column is in the current (child) table
type BelongsTo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FK column name in current table (default: <related_table>_id)
	ForeignKey string `protobuf:"bytes,1,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	// PK column name in related table (default: id)
	OwnerKey      string `protobuf:"bytes,2,opt,name=owner_key,json=ownerKey,proto3" json:"owner_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BelongsTo) Reset() {
	*x = BelongsTo{}
	mi := &file_ratelproto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BelongsTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BelongsTo) ProtoMessage() {}

func (x *BelongsTo) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BelongsTo.ProtoReflect.Descriptor instead.
func (*BelongsTo) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{9}
}

func (x *BelongsTo) GetForeignKey() string {
	if x != nil {
		return x.ForeignKey
	}
	return ""
}

func (x *BelongsTo) GetOwnerKey() string {
	if x != nil {
		return x.OwnerKey
	}
	return ""
}

// ManyToMany: Both sides have many of each other through pivot table
// (e.g., Product has many Categories through product_categories)
type ManyToMany struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional pivot table configuration
	PivotTable *Table `protobuf:"bytes,1,opt,name=pivot_table,json=pivotTable,proto3,oneof" json:"pivot_table,omitempty"`
	// FK constraints
	RefOnDeleteCascade     bool   `protobuf:"varint,2,opt,name=ref_on_delete_cascade,json=refOnDeleteCascade,proto3" json:"ref_on_delete_cascade,omitempty"`
	RefConstraint          string `protobuf:"bytes,3,opt,name=ref_constraint,json=refConstraint,proto3" json:"ref_constraint,omitempty"`
	BackRefOnDeleteCascade bool   `protobuf:"varint,4,opt,name=back_ref_on_delete_cascade,json=backRefOnDeleteCascade,proto3" json:"back_ref_on_delete_cascade,omitempty"`
	BackRefConstraint      string `protobuf:"bytes,5,opt,name=back_ref_constraint,json=backRefConstraint,proto3" json:"back_ref_constraint,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ManyToMany) Reset() {
	*x = ManyToMany{}
	mi := &file_ratelproto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManyToMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyToMany) ProtoMessage() {}

func (x *ManyToMany) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyToMany.ProtoReflect.Descriptor instead.
func (*ManyToMany) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{10}
}

func (x *ManyToMany) GetPivotTable() *Table {
	if x != nil {
		return x.PivotTable
	}
	return nil
}

func (x *ManyToMany) GetRefOnDeleteCascade() bool {
	if x != nil {
		return x.RefOnDeleteCascade
	}
	return false
}

func (x *ManyToMany) GetRefConstraint() string {
	if x != nil {
		return x.RefConstraint
	}
	return ""
}

func (x *ManyToMany) GetBackRefOnDeleteCascade() bool {
	if x != nil {
		return x.BackRefOnDeleteCascade
	}
	return false
}

func (x *ManyToMany) GetBackRefConstraint() string {
	if x != nil {
		return x.BackRefConstraint
	}
	return ""
}

type Relation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Relation:
	//
	//	*Relation_OneToMany
	//	*Relation_ManyToMany
	//	*Relation_HasOne
	//	*Relation_BelongsTo
	Relation      isRelation_Relation `protobuf_oneof:"relation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_ratelproto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{11}
}

func (x *Relation) GetRelation() isRelation_Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

func (x *Relation) GetOneToMany() *OneToMany {
	if x != nil {
		if x, ok := x.Relation.(*Relation_OneToMany); ok {
			return x.OneToMany
		}
	}
	return nil
}

func (x *Relation) GetManyToMany() *ManyToMany {
	if x != nil {
		if x, ok := x.Relation.(*Relation_ManyToMany); ok {
			return x.ManyToMany
		}
	}
	return nil
}

func (x *Relation) GetHasOne() *HasOne {
	if x != nil {
		if x, ok := x.Relation.(*Relation_HasOne); ok {
			return x.HasOne
		}
	}
	return nil
}

func (x *Relation) GetBelongsTo() *BelongsTo {
	if x != nil {
		if x, ok := x.Relation.(*Relation_BelongsTo); ok {
			return x.BelongsTo
		}
	}
	return nil
}

type isRelation_Relation interface {
	isRelation_Relation()
}

type Relation_OneToMany struct {
	OneToMany *OneToMany `protobuf:"bytes,1,opt,name=one_to_many,json=oneToMany,proto3,oneof"`
}

type Relation_ManyToMany struct {
	ManyToMany *ManyToMany `protobuf:"bytes,2,opt,name=many_to_many,json=manyToMany,proto3,oneof"`
}

type Relation_HasOne struct {
	HasOne *HasOne `protobuf:"bytes,3,opt,name=has_one,json=hasOne,proto3,oneof"`
}

type Relation_BelongsTo struct {
	BelongsTo *BelongsTo `protobuf:"bytes,4,opt,name=belongs_to,json=belongsTo,proto3,oneof"`
}

func (*Relation_OneToMany) isRelation_Relation() {}

func (*Relation_ManyToMany) isRelation_Relation() {}

func (*Relation_HasOne) isRelation_Relation() {}

func (*Relation_BelongsTo) isRelation_Relation() {}

var file_ratelproto_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50000,
		Name:          "ratel.additional_code",
		Tag:           "bytes,50000,rep,name=additional_code",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Table)(nil),
		Field:         50001,
		Name:          "ratel.virtual_tables",
		Tag:           "bytes,50001,rep,name=virtual_tables",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Table)(nil),
		Field:         50002,
		Name:          "ratel.table",
		Tag:           "bytes,50002,opt,name=table",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         50003,
		Name:          "ratel.column",
		Tag:           "bytes,50003,opt,name=column",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Relation)(nil),
		Field:         50004,
		Name:          "ratel.relation",
		Tag:           "bytes,50004,opt,name=relation",
		Filename:      "ratelproto.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated string additional_code = 50000;
	E_AdditionalCode = &file_ratelproto_proto_extTypes[0]
	// repeated ratel.Table virtual_tables = 50001;
	E_VirtualTables = &file_ratelproto_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional ratel.Table table = 50002;
	E_Table = &file_ratelproto_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ratel.Column column = 50003;
	E_Column = &file_ratelproto_proto_extTypes[3]
	// optional ratel.Relation relation = 50004;
	E_Relation = &file_ratelproto_proto_extTypes[4]
)

var File_ratelproto_proto protoreflect.FileDescriptor

const file_ratelproto_proto_rawDesc = "" +
	"\n" +
	"\x10ratelproto.proto\x12\x05ratel\x1a google/protobuf/descriptor.proto\"\x95\x03\n" +
	"\x05Table\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate\x12\"\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tH\x00R\ttableName\x88\x01\x01\x12=\n" +
	"\x0fvirtual_columns\x18\x03 \x03(\v2\x14.ratel.VirtualColumnR\x0evirtualColumns\x12 \n" +
	"\vconstraints\x18\x04 \x03(\tR\vconstraints\x12&\n" +
	"\aindexes\x18\x05 \x03(\v2\f.ratel.IndexR\aindexes\x12/\n" +
	"\x06unique\x18\x06 \x03(\v2\x17.ratel.UniqueConstraintR\x06unique\x122\n" +
	"\vprimary_key\x18\a \x01(\v2\x11.ratel.PrimaryKeyR\n" +
	"primaryKey\x12\x1b\n" +
	"\x06schema\x18\b \x01(\tH\x01R\x06schema\x88\x01\x01\x12'\n" +
	"\x0fpost_statements\x18\t \x03(\tR\x0epostStatementsB\r\n" +
	"\v_table_nameB\t\n" +
	"\a_schema\"@\n" +
	"\x10UniqueConstraint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\"&\n" +
	"\n" +
	"PrimaryKey\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\"\xd5\x01\n" +
	"\x05Index\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x14\n" +
	"\x05where\x18\x04 \x01(\tR\x05where\x12\x14\n" +
	"\x05using\x18\x05 \x01(\tR\x05using\x12\x18\n" +
	"\ainclude\x18\x06 \x03(\tR\ainclude\x12 \n" +
	"\vexpressions\x18\a \x03(\tR\vexpressions\x12\x1e\n" +
	"\n" +
	"concurrent\x18\b \x01(\bR\n" +
	"concurrent\"\x92\x01\n" +
	"\n" +
	"Constraint\x12\x16\n" +
	"\x06unique\x18\x01 \x01(\bR\x06unique\x12\x1f\n" +
	"\vprimary_key\x18\x02 \x01(\bR\n" +
	"primaryKey\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\tR\x03raw\x12\x14\n" +
	"\x05check\x18\x05 \x01(\tR\x05check\"\xb6\x01\n" +
	"\rVirtualColumn\x12\x19\n" +
	"\bsql_name\x18\x01 \x01(\tR\asqlName\x12\x19\n" +
	"\bsql_type\x18\x02 \x01(\tR\asqlType\x123\n" +
	"\vconstraints\x18\x03 \x01(\v2\x11.ratel.ConstraintR\vconstraints\x12\x1f\n" +
	"\vis_nullable\x18\x04 \x01(\bR\n" +
	"isNullable\x12\x19\n" +
	"\bis_array\x18\x05 \x01(\bR\aisArray\"Q\n" +
	"\x06Column\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x123\n" +
	"\vconstraints\x18\x02 \x01(\v2\x11.ratel.ConstraintR\vconstraints\"\x97\x01\n" +
	"\tOneToMany\x12\x19\n" +
	"\bref_name\x18\x01 \x01(\tR\arefName\x12\x1e\n" +
	"\n" +
	"constraint\x18\x02 \x01(\tR\n" +
	"constraint\x12*\n" +
	"\x11on_delete_cascade\x18\x03 \x01(\bR\x0fonDeleteCascade\x12#\n" +
	"\rexisted_field\x18\x04 \x01(\bR\fexistedField\"\xc1\x01\n" +
	"\x06HasOne\x12\x19\n" +
	"\bref_name\x18\x01 \x01(\tR\arefName\x12\x1e\n" +
	"\n" +
	"constraint\x18\x02 \x01(\tR\n" +
	"constraint\x12*\n" +
	"\x11on_delete_cascade\x18\x03 \x01(\bR\x0fonDeleteCascade\x12+\n" +
	"\x12on_delete_set_null\x18\x04 \x01(\bR\x0fonDeleteSetNull\x12#\n" +
	"\rexisted_field\x18\x05 \x01(\bR\fexistedField\"I\n" +
	"\tBelongsTo\x12\x1f\n" +
	"\vforeign_key\x18\x01 \x01(\tR\n" +
	"foreignKey\x12\x1b\n" +
	"\towner_key\x18\x02 \x01(\tR\bownerKey\"\x96\x02\n" +
	"\n" +
	"ManyToMany\x122\n" +
	"\vpivot_table\x18\x01 \x01(\v2\f.ratel.TableH\x00R\n" +
	"pivotTable\x88\x01\x01\x121\n" +
	"\x15ref_on_delete_cascade\x18\x02 \x01(\bR\x12refOnDeleteCascade\x12%\n" +
	"\x0eref_constraint\x18\x03 \x01(\tR\rrefConstraint\x12:\n" +
	"\x1aback_ref_on_delete_cascade\x18\x04 \x01(\bR\x16backRefOnDeleteCascade\x12.\n" +
	"\x13back_ref_constraint\x18\x05 \x01(\tR\x11backRefConstraintB\x0e\n" +
	"\f_pivot_table\"\xde\x01\n" +
	"\bRelation\x122\n" +
	"\vone_to_many\x18\x01 \x01(\v2\x10.ratel.OneToManyH\x00R\toneToMany\x125\n" +
	"\fmany_to_many\x18\x02 \x01(\v2\x11.ratel.ManyToManyH\x00R\n" +
	"manyToMany\x12(\n" +
	"\ahas_one\x18\x03 \x01(\v2\r.ratel.HasOneH\x00R\x06hasOne\x121\n" +
	"\n" +
	"belongs_to\x18\x04 \x01(\v2\x10.ratel.BelongsToH\x00R\tbelongsToB\n" +
	"\n" +
	"\brelation:G\n" +
	"\x0fadditional_code\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x03(\tR\x0eadditionalCode:S\n" +
	"\x0evirtual_tables\x12\x1c.google.protobuf.FileOptions\x18ц\x03 \x03(\v2\f.ratel.TableR\rvirtualTables:E\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\v2\f.ratel.TableR\x05table:F\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\v2\r.ratel.ColumnR\x06column:L\n" +
	"\brelation\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\v2\x0f.ratel.RelationR\brelationB%Z#github.com/yaroher/ratel/ratelprotob\x06proto3"

var (
	file_ratelproto_proto_rawDescOnce sync.Once
	file_ratelproto_proto_rawDescData []byte
)

func file_ratelproto_proto_rawDescGZIP() []byte {
	file_ratelproto_proto_rawDescOnce.Do(func() {
		file_ratelproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelproto_proto_rawDesc), len(file_ratelproto_proto_rawDesc)))
	})
	return file_ratelproto_proto_rawDescData
}

var file_ratelproto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ratelproto_proto_goTypes = []any{
	(*Table)(nil),                       // 0: ratel.Table
	(*UniqueConstraint)(nil),            // 1: ratel.UniqueConstraint
	(*PrimaryKey)(nil),                  // 2: ratel.PrimaryKey
	(*Index)(nil),                       // 3: ratel.Index
	(*Constraint)(nil),                  // 4: ratel.Constraint
	(*VirtualColumn)(nil),               // 5: ratel.VirtualColumn
	(*Column)(nil),                      // 6: ratel.Column
	(*OneToMany)(nil),                   // 7: ratel.OneToMany
	(*HasOne)(nil),                      // 8: ratel.HasOne
	(*BelongsTo)(nil),                   // 9: ratel.BelongsTo
	(*ManyToMany)(nil),                  // 10: ratel.ManyToMany
	(*Relation)(nil),                    // 11: ratel.Relation
	(*descriptorpb.FileOptions)(nil),    // 12: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 13: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 14: google.protobuf.FieldOptions
}
var file_ratelproto_proto_depIdxs = []int32{
	5,  // 0: ratel.Table.virtual_columns:type_name -> ratel.VirtualColumn
	3,  // 1: ratel.Table.indexes:type_name -> ratel.Index
	1,  // 2: ratel.Table.unique:type_name -> ratel.UniqueConstraint
	2,  // 3: ratel.Table.primary_key:type_name -> ratel.PrimaryKey
	4,  // 4: ratel.VirtualColumn.constraints:type_name -> ratel.Constraint
	4,  // 5: ratel.Column.constraints:type_name -> ratel.Constraint
	0,  // 6: ratel.ManyToMany.pivot_table:type_name -> ratel.Table
	7,  // 7: ratel.Relation.one_to_many:type_name -> ratel.OneToMany
	10, // 8: ratel.Relation.many_to_many:type_name -> ratel.ManyToMany
	8,  // 9: ratel.Relation.has_one:type_name -> ratel.HasOne
	9,  // 10: ratel.Relation.belongs_to:type_name -> ratel.BelongsTo
	12, // 11: ratel.additional_code:extendee -> google.protobuf.FileOptions
	12, // 12: ratel.virtual_tables:extendee -> google.protobuf.FileOptions
	13, // 13: ratel.table:extendee -> google.protobuf.MessageOptions
	14, // 14: ratel.column:extendee -> google.protobuf.FieldOptions
	14, // 15: ratel.relation:extendee -> google.protobuf.FieldOptions
	0,  // 16: ratel.virtual_tables:type_name -> ratel.Table
	0,  // 17: ratel.table:type_name -> ratel.Table
	6,  // 18: ratel.column:type_name -> ratel.Column
	11, // 19: ratel.relation:type_name -> ratel.Relation
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	16, // [16:20] is the sub-list for extension type_name
	11, // [11:16] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ratelproto_proto_init() }
func file_ratelproto_proto_init() {
	if File_ratelproto_proto != nil {
		return
	}
	file_ratelproto_proto_msgTypes[0].OneofWrappers = []any{}
	file_ratelproto_proto_msgTypes[10].OneofWrappers = []any{}
	file_ratelproto_proto_msgTypes[11].OneofWrappers = []any{
		(*Relation_OneToMany)(nil),
		(*Relation_ManyToMany)(nil),
		(*Relation_HasOne)(nil),
		(*Relation_BelongsTo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelproto_proto_rawDesc), len(file_ratelproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_ratelproto_proto_goTypes,
		DependencyIndexes: file_ratelproto_proto_depIdxs,
		MessageInfos:      file_ratelproto_proto_msgTypes,
		ExtensionInfos:    file_ratelproto_proto_extTypes,
	}.Build()
	File_ratelproto_proto = out.File
	file_ratelproto_proto_goTypes = nil
	file_ratelproto_proto_depIdxs = nil
}
