// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ratelproto.proto

package ratelproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Table struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate table schema for this message
	Generate bool `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	// Override table name (default: snake_case of message name)
	TableName *string `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3,oneof" json:"table_name,omitempty"`
	// Virtual fields (columns not in proto message)
	VirtualColumns []*VirtualColumn `protobuf:"bytes,3,rep,name=virtual_columns,json=virtualColumns,proto3" json:"virtual_columns,omitempty"`
	// Table-level constraints (e.g., "UNIQUE (a, b)", "CHECK (x > 0)")
	Constraints []string `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// Indexes
	Indexes       []*Index `protobuf:"bytes,5,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_ratelproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{0}
}

func (x *Table) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

func (x *Table) GetTableName() string {
	if x != nil && x.TableName != nil {
		return *x.TableName
	}
	return ""
}

func (x *Table) GetVirtualColumns() []*VirtualColumn {
	if x != nil {
		return x.VirtualColumns
	}
	return nil
}

func (x *Table) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Table) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type Index struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index name (auto-generated if empty: idx_<table>_<columns>)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Columns to index
	Columns []string `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	// Unique index
	Unique bool `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	// Partial index WHERE clause (e.g., "is_deleted = false")
	Where string `protobuf:"bytes,4,opt,name=where,proto3" json:"where,omitempty"`
	// Index method: btree (default), hash, gin, gist, spgist, brin
	Using string `protobuf:"bytes,5,opt,name=using,proto3" json:"using,omitempty"`
	// Include columns (INCLUDE clause for covering indexes)
	Include []string `protobuf:"bytes,6,rep,name=include,proto3" json:"include,omitempty"`
	// Expression columns (e.g., "lower(email)", "created_at::date")
	// Use instead of 'columns' for expression-based indexes
	Expressions []string `protobuf:"bytes,7,rep,name=expressions,proto3" json:"expressions,omitempty"`
	// Concurrent index creation (CREATE INDEX CONCURRENTLY)
	Concurrent    bool `protobuf:"varint,8,opt,name=concurrent,proto3" json:"concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_ratelproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{1}
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Index) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Index) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *Index) GetUsing() string {
	if x != nil {
		return x.Using
	}
	return ""
}

func (x *Index) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *Index) GetExpressions() []string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *Index) GetConcurrent() bool {
	if x != nil {
		return x.Concurrent
	}
	return false
}

type Constraint struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Unique       bool                   `protobuf:"varint,1,opt,name=unique,proto3" json:"unique,omitempty"`
	PrimaryKey   bool                   `protobuf:"varint,2,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	DefaultValue string                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Raw SQL constraint (overrides above if set)
	Raw           string `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_ratelproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{2}
}

func (x *Constraint) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Constraint) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *Constraint) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *Constraint) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type VirtualColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqlName       string                 `protobuf:"bytes,1,opt,name=sql_name,json=sqlName,proto3" json:"sql_name,omitempty"`
	SqlType       string                 `protobuf:"bytes,2,opt,name=sql_type,json=sqlType,proto3" json:"sql_type,omitempty"` // e.g., "BIGINT", "TEXT", "TIMESTAMPTZ"
	Constraints   *Constraint            `protobuf:"bytes,3,opt,name=constraints,proto3" json:"constraints,omitempty"`
	IsNullable    bool                   `protobuf:"varint,4,opt,name=is_nullable,json=isNullable,proto3" json:"is_nullable,omitempty"`
	IsArray       bool                   `protobuf:"varint,5,opt,name=is_array,json=isArray,proto3" json:"is_array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualColumn) Reset() {
	*x = VirtualColumn{}
	mi := &file_ratelproto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualColumn) ProtoMessage() {}

func (x *VirtualColumn) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualColumn.ProtoReflect.Descriptor instead.
func (*VirtualColumn) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualColumn) GetSqlName() string {
	if x != nil {
		return x.SqlName
	}
	return ""
}

func (x *VirtualColumn) GetSqlType() string {
	if x != nil {
		return x.SqlType
	}
	return ""
}

func (x *VirtualColumn) GetConstraints() *Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *VirtualColumn) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *VirtualColumn) GetIsArray() bool {
	if x != nil {
		return x.IsArray
	}
	return false
}

type Column struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skip this field in table generation
	Skip bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	// Column constraints
	Constraints   *Constraint `protobuf:"bytes,2,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_ratelproto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{4}
}

func (x *Column) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *Column) GetConstraints() *Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type OneToMany struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FK column name in related table (default: <table>_id)
	RefName string `protobuf:"bytes,1,opt,name=ref_name,json=refName,proto3" json:"ref_name,omitempty"`
	// Raw constraint for FK (overrides default REFERENCES)
	Constraint string `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
	// Add ON DELETE CASCADE
	OnDeleteCascade bool `protobuf:"varint,3,opt,name=on_delete_cascade,json=onDeleteCascade,proto3" json:"on_delete_cascade,omitempty"`
	// FK column already exists in related table (don't create virtual)
	ExistedField  bool `protobuf:"varint,4,opt,name=existed_field,json=existedField,proto3" json:"existed_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneToMany) Reset() {
	*x = OneToMany{}
	mi := &file_ratelproto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneToMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneToMany) ProtoMessage() {}

func (x *OneToMany) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneToMany.ProtoReflect.Descriptor instead.
func (*OneToMany) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{5}
}

func (x *OneToMany) GetRefName() string {
	if x != nil {
		return x.RefName
	}
	return ""
}

func (x *OneToMany) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *OneToMany) GetOnDeleteCascade() bool {
	if x != nil {
		return x.OnDeleteCascade
	}
	return false
}

func (x *OneToMany) GetExistedField() bool {
	if x != nil {
		return x.ExistedField
	}
	return false
}

type ManyToMany struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional pivot table configuration
	PivotTable *Table `protobuf:"bytes,1,opt,name=pivot_table,json=pivotTable,proto3,oneof" json:"pivot_table,omitempty"`
	// FK constraints
	RefOnDeleteCascade     bool   `protobuf:"varint,2,opt,name=ref_on_delete_cascade,json=refOnDeleteCascade,proto3" json:"ref_on_delete_cascade,omitempty"`
	RefConstraint          string `protobuf:"bytes,3,opt,name=ref_constraint,json=refConstraint,proto3" json:"ref_constraint,omitempty"`
	BackRefOnDeleteCascade bool   `protobuf:"varint,4,opt,name=back_ref_on_delete_cascade,json=backRefOnDeleteCascade,proto3" json:"back_ref_on_delete_cascade,omitempty"`
	BackRefConstraint      string `protobuf:"bytes,5,opt,name=back_ref_constraint,json=backRefConstraint,proto3" json:"back_ref_constraint,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ManyToMany) Reset() {
	*x = ManyToMany{}
	mi := &file_ratelproto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManyToMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyToMany) ProtoMessage() {}

func (x *ManyToMany) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyToMany.ProtoReflect.Descriptor instead.
func (*ManyToMany) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{6}
}

func (x *ManyToMany) GetPivotTable() *Table {
	if x != nil {
		return x.PivotTable
	}
	return nil
}

func (x *ManyToMany) GetRefOnDeleteCascade() bool {
	if x != nil {
		return x.RefOnDeleteCascade
	}
	return false
}

func (x *ManyToMany) GetRefConstraint() string {
	if x != nil {
		return x.RefConstraint
	}
	return ""
}

func (x *ManyToMany) GetBackRefOnDeleteCascade() bool {
	if x != nil {
		return x.BackRefOnDeleteCascade
	}
	return false
}

func (x *ManyToMany) GetBackRefConstraint() string {
	if x != nil {
		return x.BackRefConstraint
	}
	return ""
}

type Relation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Relation:
	//
	//	*Relation_OneToMany
	//	*Relation_ManyToMany
	Relation      isRelation_Relation `protobuf_oneof:"relation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_ratelproto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_ratelproto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_ratelproto_proto_rawDescGZIP(), []int{7}
}

func (x *Relation) GetRelation() isRelation_Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

func (x *Relation) GetOneToMany() *OneToMany {
	if x != nil {
		if x, ok := x.Relation.(*Relation_OneToMany); ok {
			return x.OneToMany
		}
	}
	return nil
}

func (x *Relation) GetManyToMany() *ManyToMany {
	if x != nil {
		if x, ok := x.Relation.(*Relation_ManyToMany); ok {
			return x.ManyToMany
		}
	}
	return nil
}

type isRelation_Relation interface {
	isRelation_Relation()
}

type Relation_OneToMany struct {
	OneToMany *OneToMany `protobuf:"bytes,1,opt,name=one_to_many,json=oneToMany,proto3,oneof"`
}

type Relation_ManyToMany struct {
	ManyToMany *ManyToMany `protobuf:"bytes,2,opt,name=many_to_many,json=manyToMany,proto3,oneof"`
}

func (*Relation_OneToMany) isRelation_Relation() {}

func (*Relation_ManyToMany) isRelation_Relation() {}

var file_ratelproto_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50000,
		Name:          "ratel.additional_code",
		Tag:           "bytes,50000,rep,name=additional_code",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*Table)(nil),
		Field:         50001,
		Name:          "ratel.virtual_tables",
		Tag:           "bytes,50001,rep,name=virtual_tables",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Table)(nil),
		Field:         50002,
		Name:          "ratel.table",
		Tag:           "bytes,50002,opt,name=table",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Column)(nil),
		Field:         50003,
		Name:          "ratel.column",
		Tag:           "bytes,50003,opt,name=column",
		Filename:      "ratelproto.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Relation)(nil),
		Field:         50004,
		Name:          "ratel.relation",
		Tag:           "bytes,50004,opt,name=relation",
		Filename:      "ratelproto.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated string additional_code = 50000;
	E_AdditionalCode = &file_ratelproto_proto_extTypes[0]
	// repeated ratel.Table virtual_tables = 50001;
	E_VirtualTables = &file_ratelproto_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional ratel.Table table = 50002;
	E_Table = &file_ratelproto_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ratel.Column column = 50003;
	E_Column = &file_ratelproto_proto_extTypes[3]
	// optional ratel.Relation relation = 50004;
	E_Relation = &file_ratelproto_proto_extTypes[4]
)

var File_ratelproto_proto protoreflect.FileDescriptor

const file_ratelproto_proto_rawDesc = "" +
	"\n" +
	"\x10ratelproto.proto\x12\x05ratel\x1a google/protobuf/descriptor.proto\"\xdf\x01\n" +
	"\x05Table\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate\x12\"\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tH\x00R\ttableName\x88\x01\x01\x12=\n" +
	"\x0fvirtual_columns\x18\x03 \x03(\v2\x14.ratel.VirtualColumnR\x0evirtualColumns\x12 \n" +
	"\vconstraints\x18\x04 \x03(\tR\vconstraints\x12&\n" +
	"\aindexes\x18\x05 \x03(\v2\f.ratel.IndexR\aindexesB\r\n" +
	"\v_table_name\"\xd5\x01\n" +
	"\x05Index\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x14\n" +
	"\x05where\x18\x04 \x01(\tR\x05where\x12\x14\n" +
	"\x05using\x18\x05 \x01(\tR\x05using\x12\x18\n" +
	"\ainclude\x18\x06 \x03(\tR\ainclude\x12 \n" +
	"\vexpressions\x18\a \x03(\tR\vexpressions\x12\x1e\n" +
	"\n" +
	"concurrent\x18\b \x01(\bR\n" +
	"concurrent\"|\n" +
	"\n" +
	"Constraint\x12\x16\n" +
	"\x06unique\x18\x01 \x01(\bR\x06unique\x12\x1f\n" +
	"\vprimary_key\x18\x02 \x01(\bR\n" +
	"primaryKey\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\tR\x03raw\"\xb6\x01\n" +
	"\rVirtualColumn\x12\x19\n" +
	"\bsql_name\x18\x01 \x01(\tR\asqlName\x12\x19\n" +
	"\bsql_type\x18\x02 \x01(\tR\asqlType\x123\n" +
	"\vconstraints\x18\x03 \x01(\v2\x11.ratel.ConstraintR\vconstraints\x12\x1f\n" +
	"\vis_nullable\x18\x04 \x01(\bR\n" +
	"isNullable\x12\x19\n" +
	"\bis_array\x18\x05 \x01(\bR\aisArray\"Q\n" +
	"\x06Column\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\x123\n" +
	"\vconstraints\x18\x02 \x01(\v2\x11.ratel.ConstraintR\vconstraints\"\x97\x01\n" +
	"\tOneToMany\x12\x19\n" +
	"\bref_name\x18\x01 \x01(\tR\arefName\x12\x1e\n" +
	"\n" +
	"constraint\x18\x02 \x01(\tR\n" +
	"constraint\x12*\n" +
	"\x11on_delete_cascade\x18\x03 \x01(\bR\x0fonDeleteCascade\x12#\n" +
	"\rexisted_field\x18\x04 \x01(\bR\fexistedField\"\x96\x02\n" +
	"\n" +
	"ManyToMany\x122\n" +
	"\vpivot_table\x18\x01 \x01(\v2\f.ratel.TableH\x00R\n" +
	"pivotTable\x88\x01\x01\x121\n" +
	"\x15ref_on_delete_cascade\x18\x02 \x01(\bR\x12refOnDeleteCascade\x12%\n" +
	"\x0eref_constraint\x18\x03 \x01(\tR\rrefConstraint\x12:\n" +
	"\x1aback_ref_on_delete_cascade\x18\x04 \x01(\bR\x16backRefOnDeleteCascade\x12.\n" +
	"\x13back_ref_constraint\x18\x05 \x01(\tR\x11backRefConstraintB\x0e\n" +
	"\f_pivot_table\"\x81\x01\n" +
	"\bRelation\x122\n" +
	"\vone_to_many\x18\x01 \x01(\v2\x10.ratel.OneToManyH\x00R\toneToMany\x125\n" +
	"\fmany_to_many\x18\x02 \x01(\v2\x11.ratel.ManyToManyH\x00R\n" +
	"manyToManyB\n" +
	"\n" +
	"\brelation:G\n" +
	"\x0fadditional_code\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x03(\tR\x0eadditionalCode:S\n" +
	"\x0evirtual_tables\x12\x1c.google.protobuf.FileOptions\x18ц\x03 \x03(\v2\f.ratel.TableR\rvirtualTables:E\n" +
	"\x05table\x12\x1f.google.protobuf.MessageOptions\x18҆\x03 \x01(\v2\f.ratel.TableR\x05table:F\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18ӆ\x03 \x01(\v2\r.ratel.ColumnR\x06column:L\n" +
	"\brelation\x12\x1d.google.protobuf.FieldOptions\x18Ԇ\x03 \x01(\v2\x0f.ratel.RelationR\brelationB%Z#github.com/yaroher/ratel/ratelprotob\x06proto3"

var (
	file_ratelproto_proto_rawDescOnce sync.Once
	file_ratelproto_proto_rawDescData []byte
)

func file_ratelproto_proto_rawDescGZIP() []byte {
	file_ratelproto_proto_rawDescOnce.Do(func() {
		file_ratelproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratelproto_proto_rawDesc), len(file_ratelproto_proto_rawDesc)))
	})
	return file_ratelproto_proto_rawDescData
}

var file_ratelproto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ratelproto_proto_goTypes = []any{
	(*Table)(nil),                       // 0: ratel.Table
	(*Index)(nil),                       // 1: ratel.Index
	(*Constraint)(nil),                  // 2: ratel.Constraint
	(*VirtualColumn)(nil),               // 3: ratel.VirtualColumn
	(*Column)(nil),                      // 4: ratel.Column
	(*OneToMany)(nil),                   // 5: ratel.OneToMany
	(*ManyToMany)(nil),                  // 6: ratel.ManyToMany
	(*Relation)(nil),                    // 7: ratel.Relation
	(*descriptorpb.FileOptions)(nil),    // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 10: google.protobuf.FieldOptions
}
var file_ratelproto_proto_depIdxs = []int32{
	3,  // 0: ratel.Table.virtual_columns:type_name -> ratel.VirtualColumn
	1,  // 1: ratel.Table.indexes:type_name -> ratel.Index
	2,  // 2: ratel.VirtualColumn.constraints:type_name -> ratel.Constraint
	2,  // 3: ratel.Column.constraints:type_name -> ratel.Constraint
	0,  // 4: ratel.ManyToMany.pivot_table:type_name -> ratel.Table
	5,  // 5: ratel.Relation.one_to_many:type_name -> ratel.OneToMany
	6,  // 6: ratel.Relation.many_to_many:type_name -> ratel.ManyToMany
	8,  // 7: ratel.additional_code:extendee -> google.protobuf.FileOptions
	8,  // 8: ratel.virtual_tables:extendee -> google.protobuf.FileOptions
	9,  // 9: ratel.table:extendee -> google.protobuf.MessageOptions
	10, // 10: ratel.column:extendee -> google.protobuf.FieldOptions
	10, // 11: ratel.relation:extendee -> google.protobuf.FieldOptions
	0,  // 12: ratel.virtual_tables:type_name -> ratel.Table
	0,  // 13: ratel.table:type_name -> ratel.Table
	4,  // 14: ratel.column:type_name -> ratel.Column
	7,  // 15: ratel.relation:type_name -> ratel.Relation
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	12, // [12:16] is the sub-list for extension type_name
	7,  // [7:12] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ratelproto_proto_init() }
func file_ratelproto_proto_init() {
	if File_ratelproto_proto != nil {
		return
	}
	file_ratelproto_proto_msgTypes[0].OneofWrappers = []any{}
	file_ratelproto_proto_msgTypes[6].OneofWrappers = []any{}
	file_ratelproto_proto_msgTypes[7].OneofWrappers = []any{
		(*Relation_OneToMany)(nil),
		(*Relation_ManyToMany)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratelproto_proto_rawDesc), len(file_ratelproto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_ratelproto_proto_goTypes,
		DependencyIndexes: file_ratelproto_proto_depIdxs,
		MessageInfos:      file_ratelproto_proto_msgTypes,
		ExtensionInfos:    file_ratelproto_proto_extTypes,
	}.Build()
	File_ratelproto_proto = out.File
	file_ratelproto_proto_goTypes = nil
	file_ratelproto_proto_depIdxs = nil
}
