// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/proto/goplain/goplain.proto

package goplain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	typepb "google.golang.org/protobuf/types/known/typepb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoIdent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImportPath    string                 `protobuf:"bytes,2,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoIdent) Reset() {
	*x = GoIdent{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoIdent) ProtoMessage() {}

func (x *GoIdent) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoIdent.ProtoReflect.Descriptor instead.
func (*GoIdent) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{0}
}

func (x *GoIdent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoIdent) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

type OverrideSelector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetFullPath *string                `protobuf:"bytes,1,opt,name=target_full_path,json=targetFullPath,proto3,oneof" json:"target_full_path,omitempty"`
	// from google.protobuf.Field
	FieldKind        *typepb.Field_Kind        `protobuf:"varint,2,opt,name=field_kind,json=fieldKind,proto3,enum=google.protobuf.Field_Kind,oneof" json:"field_kind,omitempty"`
	FieldCardinality *typepb.Field_Cardinality `protobuf:"varint,3,opt,name=field_cardinality,json=fieldCardinality,proto3,enum=google.protobuf.Field_Cardinality,oneof" json:"field_cardinality,omitempty"`
	FieldTypeUrl     *string                   `protobuf:"bytes,4,opt,name=field_type_url,json=fieldTypeUrl,proto3,oneof" json:"field_type_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OverrideSelector) Reset() {
	*x = OverrideSelector{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideSelector) ProtoMessage() {}

func (x *OverrideSelector) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideSelector.ProtoReflect.Descriptor instead.
func (*OverrideSelector) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{1}
}

func (x *OverrideSelector) GetTargetFullPath() string {
	if x != nil && x.TargetFullPath != nil {
		return *x.TargetFullPath
	}
	return ""
}

func (x *OverrideSelector) GetFieldKind() typepb.Field_Kind {
	if x != nil && x.FieldKind != nil {
		return *x.FieldKind
	}
	return typepb.Field_Kind(0)
}

func (x *OverrideSelector) GetFieldCardinality() typepb.Field_Cardinality {
	if x != nil && x.FieldCardinality != nil {
		return *x.FieldCardinality
	}
	return typepb.Field_Cardinality(0)
}

func (x *OverrideSelector) GetFieldTypeUrl() string {
	if x != nil && x.FieldTypeUrl != nil {
		return *x.FieldTypeUrl
	}
	return ""
}

type TypeOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *OverrideSelector      `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	TargetGoType  *GoIdent               `protobuf:"bytes,2,opt,name=target_go_type,json=targetGoType,proto3" json:"target_go_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeOverride) Reset() {
	*x = TypeOverride{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeOverride) ProtoMessage() {}

func (x *TypeOverride) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeOverride.ProtoReflect.Descriptor instead.
func (*TypeOverride) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{2}
}

func (x *TypeOverride) GetSelector() *OverrideSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *TypeOverride) GetTargetGoType() *GoIdent {
	if x != nil {
		return x.TargetGoType
	}
	return nil
}

type MessageOptions struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Generate bool                   `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	// Type alias instead of message.
	// This means that this message has one field named "<scalar_type> value"
	// example:
	// message Int32Alias {
	// option (plain.field).type_alias = true;
	// int32 value = 1;
	// }
	// // this:
	// message Int32AliasUSAGE {
	// Int32Alias value = 1;
	// }
	// // becomes:
	// message Int32AliasUSAGE {
	// int32 value = 1;
	// }
	TypeAlias      bool   `protobuf:"varint,2,opt,name=type_alias,json=typeAlias,proto3" json:"type_alias,omitempty"`
	TypeAliasField string `protobuf:"bytes,3,opt,name=type_alias_field,json=typeAliasField,proto3" json:"type_alias_field,omitempty"`
	// Virtual fields for this message.
	// Number is filled automatically.
	// This does not affect the original message numbers alignment cause this field does not apply to the original message.
	// Needs only to included in plain message and use in final code with plain messages.
	// Example:
	// message User {
	// (plain.message).virtual_fields = [
	// {name: "password_hash", kind: TYPE_STRING}
	// ];
	// string name = 1;
	// }
	// // becomes:
	// message UserPlain {
	// string name = 1;
	// string password_hash = 2;
	// }
	VirtualFields []*typepb.Field `protobuf:"bytes,4,rep,name=virtual_fields,json=virtualFields,proto3" json:"virtual_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{3}
}

func (x *MessageOptions) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

func (x *MessageOptions) GetTypeAlias() bool {
	if x != nil {
		return x.TypeAlias
	}
	return false
}

func (x *MessageOptions) GetTypeAliasField() string {
	if x != nil {
		return x.TypeAliasField
	}
	return ""
}

func (x *MessageOptions) GetVirtualFields() []*typepb.Field {
	if x != nil {
		return x.VirtualFields
	}
	return nil
}

type FileOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GoTypesOverrides []*TypeOverride        `protobuf:"bytes,1,rep,name=go_types_overrides,json=goTypesOverrides,proto3" json:"go_types_overrides,omitempty"`
	VirtualTypes     []*typepb.Type         `protobuf:"bytes,2,rep,name=virtual_types,json=virtualTypes,proto3" json:"virtual_types,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{4}
}

func (x *FileOptions) GetGoTypesOverrides() []*TypeOverride {
	if x != nil {
		return x.GoTypesOverrides
	}
	return nil
}

func (x *FileOptions) GetVirtualTypes() []*typepb.Type {
	if x != nil {
		return x.VirtualTypes
	}
	return nil
}

type FieldOptions struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	OverrideType *GoIdent               `protobuf:"bytes,1,opt,name=override_type,json=overrideType,proto3" json:"override_type,omitempty"`
	// Field serialization options.
	// If set to true, the field will be serialized as a JSON object.
	//
	// Example:
	// message User {
	// string name = 1;
	// Address address = 2 [(goplain.field).serialized = true];
	// repeated Address addresses = 3 [(goplain.field).serialized = true];
	// }
	//
	// Becomes:
	// message UserPlain {
	// string name = 1;
	//
	// // without prefix:
	// bytes address = 2;
	// repeated bytes addresses = 3;
	// }
	Serialize bool `protobuf:"varint,2,opt,name=serialize,proto3" json:"serialize,omitempty"`
	// Embed field into parent message
	//
	// Example:
	// message Address {
	// string street = 1;
	// }
	// message User {
	// string name = 1;
	// Address address = 2 [(goplain.field).embed = {with_prefix: true}];
	// }
	//
	// Becomes:
	// message UserPlain {
	// string name = 1;
	//
	// // without prefix:
	// string street = 2;
	//
	// // or with prefix:
	// string address_street = 3;
	// }
	Embed           bool `protobuf:"varint,4,opt,name=embed,proto3" json:"embed,omitempty"`
	EmbedWithPrefix bool `protobuf:"varint,5,opt,name=embed_with_prefix,json=embedWithPrefix,proto3" json:"embed_with_prefix,omitempty"`
	EnumAsString    bool `protobuf:"varint,7,opt,name=enum_as_string,json=enumAsString,proto3" json:"enum_as_string,omitempty"`
	EnumAsInt       bool `protobuf:"varint,8,opt,name=enum_as_int,json=enumAsInt,proto3" json:"enum_as_int,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{5}
}

func (x *FieldOptions) GetOverrideType() *GoIdent {
	if x != nil {
		return x.OverrideType
	}
	return nil
}

func (x *FieldOptions) GetSerialize() bool {
	if x != nil {
		return x.Serialize
	}
	return false
}

func (x *FieldOptions) GetEmbed() bool {
	if x != nil {
		return x.Embed
	}
	return false
}

func (x *FieldOptions) GetEmbedWithPrefix() bool {
	if x != nil {
		return x.EmbedWithPrefix
	}
	return false
}

func (x *FieldOptions) GetEnumAsString() bool {
	if x != nil {
		return x.EnumAsString
	}
	return false
}

func (x *FieldOptions) GetEnumAsInt() bool {
	if x != nil {
		return x.EnumAsInt
	}
	return false
}

type OneofOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embed oneof into parent message
	//
	// Example:
	// message User {
	// string name = 1;
	// oneof address {
	// (goplain.oneof).embed = true;
	// Address address = 2;
	// string street = 3;
	// }
	// }
	//
	// Becomes:
	// message UserPlain {
	// string name = 1;
	//
	// // without prefix:
	// Address address = 2;
	// string street = 3;
	//
	// // or with prefix:
	// Address address_address = 4;
	// string address_street = 5;
	// }
	Embed           bool `protobuf:"varint,1,opt,name=embed,proto3" json:"embed,omitempty"` // only meanfull for go-plain structs (not protoc-gen-go)
	EmbedWithPrefix bool `protobuf:"varint,2,opt,name=embed_with_prefix,json=embedWithPrefix,proto3" json:"embed_with_prefix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_goplain_goplain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_examples_proto_goplain_goplain_proto_rawDescGZIP(), []int{6}
}

func (x *OneofOptions) GetEmbed() bool {
	if x != nil {
		return x.Embed
	}
	return false
}

func (x *OneofOptions) GetEmbedWithPrefix() bool {
	if x != nil {
		return x.EmbedWithPrefix
	}
	return false
}

var file_examples_proto_goplain_goplain_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         60000,
		Name:          "goplain.file",
		Tag:           "bytes,60000,opt,name=file",
		Filename:      "examples/proto/goplain/goplain.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         60000,
		Name:          "goplain.message",
		Tag:           "bytes,60000,opt,name=message",
		Filename:      "examples/proto/goplain/goplain.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         60000,
		Name:          "goplain.field",
		Tag:           "bytes,60000,opt,name=field",
		Filename:      "examples/proto/goplain/goplain.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         50000,
		Name:          "goplain.oneof",
		Tag:           "bytes,50000,opt,name=oneof",
		Filename:      "examples/proto/goplain/goplain.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional goplain.FileOptions file = 60000;
	E_File = &file_examples_proto_goplain_goplain_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional goplain.MessageOptions message = 60000;
	E_Message = &file_examples_proto_goplain_goplain_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional goplain.FieldOptions field = 60000;
	E_Field = &file_examples_proto_goplain_goplain_proto_extTypes[2]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional goplain.OneofOptions oneof = 50000;
	E_Oneof = &file_examples_proto_goplain_goplain_proto_extTypes[3]
)

var File_examples_proto_goplain_goplain_proto protoreflect.FileDescriptor

const file_examples_proto_goplain_goplain_proto_rawDesc = "" +
	"\n" +
	"$examples/proto/goplain/goplain.proto\x12\agoplain\x1a google/protobuf/descriptor.proto\x1a\x1agoogle/protobuf/type.proto\">\n" +
	"\aGoIdent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vimport_path\x18\x02 \x01(\tR\n" +
	"importPath\"\xd0\x02\n" +
	"\x10OverrideSelector\x12-\n" +
	"\x10target_full_path\x18\x01 \x01(\tH\x00R\x0etargetFullPath\x88\x01\x01\x12?\n" +
	"\n" +
	"field_kind\x18\x02 \x01(\x0e2\x1b.google.protobuf.Field.KindH\x01R\tfieldKind\x88\x01\x01\x12T\n" +
	"\x11field_cardinality\x18\x03 \x01(\x0e2\".google.protobuf.Field.CardinalityH\x02R\x10fieldCardinality\x88\x01\x01\x12)\n" +
	"\x0efield_type_url\x18\x04 \x01(\tH\x03R\ffieldTypeUrl\x88\x01\x01B\x13\n" +
	"\x11_target_full_pathB\r\n" +
	"\v_field_kindB\x14\n" +
	"\x12_field_cardinalityB\x11\n" +
	"\x0f_field_type_url\"}\n" +
	"\fTypeOverride\x125\n" +
	"\bselector\x18\x01 \x01(\v2\x19.goplain.OverrideSelectorR\bselector\x126\n" +
	"\x0etarget_go_type\x18\x02 \x01(\v2\x10.goplain.GoIdentR\ftargetGoType\"\xb4\x01\n" +
	"\x0eMessageOptions\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate\x12\x1d\n" +
	"\n" +
	"type_alias\x18\x02 \x01(\bR\ttypeAlias\x12(\n" +
	"\x10type_alias_field\x18\x03 \x01(\tR\x0etypeAliasField\x12=\n" +
	"\x0evirtual_fields\x18\x04 \x03(\v2\x16.google.protobuf.FieldR\rvirtualFields\"\x8e\x01\n" +
	"\vFileOptions\x12C\n" +
	"\x12go_types_overrides\x18\x01 \x03(\v2\x15.goplain.TypeOverrideR\x10goTypesOverrides\x12:\n" +
	"\rvirtual_types\x18\x02 \x03(\v2\x15.google.protobuf.TypeR\fvirtualTypes\"\xeb\x01\n" +
	"\fFieldOptions\x125\n" +
	"\roverride_type\x18\x01 \x01(\v2\x10.goplain.GoIdentR\foverrideType\x12\x1c\n" +
	"\tserialize\x18\x02 \x01(\bR\tserialize\x12\x14\n" +
	"\x05embed\x18\x04 \x01(\bR\x05embed\x12*\n" +
	"\x11embed_with_prefix\x18\x05 \x01(\bR\x0fembedWithPrefix\x12$\n" +
	"\x0eenum_as_string\x18\a \x01(\bR\fenumAsString\x12\x1e\n" +
	"\venum_as_int\x18\b \x01(\bR\tenumAsInt\"P\n" +
	"\fOneofOptions\x12\x14\n" +
	"\x05embed\x18\x01 \x01(\bR\x05embed\x12*\n" +
	"\x11embed_with_prefix\x18\x02 \x01(\bR\x0fembedWithPrefix:H\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xe0\xd4\x03 \x01(\v2\x14.goplain.FileOptionsR\x04file:T\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xe0\xd4\x03 \x01(\v2\x17.goplain.MessageOptionsR\amessage:L\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xe0\xd4\x03 \x01(\v2\x15.goplain.FieldOptionsR\x05field:L\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18І\x03 \x01(\v2\x15.goplain.OneofOptionsR\x05oneofB0Z.github.com/yaroher/protoc-gen-go-plain/goplainb\x06proto3"

var (
	file_examples_proto_goplain_goplain_proto_rawDescOnce sync.Once
	file_examples_proto_goplain_goplain_proto_rawDescData []byte
)

func file_examples_proto_goplain_goplain_proto_rawDescGZIP() []byte {
	file_examples_proto_goplain_goplain_proto_rawDescOnce.Do(func() {
		file_examples_proto_goplain_goplain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_proto_goplain_goplain_proto_rawDesc), len(file_examples_proto_goplain_goplain_proto_rawDesc)))
	})
	return file_examples_proto_goplain_goplain_proto_rawDescData
}

var file_examples_proto_goplain_goplain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_examples_proto_goplain_goplain_proto_goTypes = []any{
	(*GoIdent)(nil),                     // 0: goplain.GoIdent
	(*OverrideSelector)(nil),            // 1: goplain.OverrideSelector
	(*TypeOverride)(nil),                // 2: goplain.TypeOverride
	(*MessageOptions)(nil),              // 3: goplain.MessageOptions
	(*FileOptions)(nil),                 // 4: goplain.FileOptions
	(*FieldOptions)(nil),                // 5: goplain.FieldOptions
	(*OneofOptions)(nil),                // 6: goplain.OneofOptions
	(typepb.Field_Kind)(0),              // 7: google.protobuf.Field.Kind
	(typepb.Field_Cardinality)(0),       // 8: google.protobuf.Field.Cardinality
	(*typepb.Field)(nil),                // 9: google.protobuf.Field
	(*typepb.Type)(nil),                 // 10: google.protobuf.Type
	(*descriptorpb.FileOptions)(nil),    // 11: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 12: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 13: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),   // 14: google.protobuf.OneofOptions
}
var file_examples_proto_goplain_goplain_proto_depIdxs = []int32{
	7,  // 0: goplain.OverrideSelector.field_kind:type_name -> google.protobuf.Field.Kind
	8,  // 1: goplain.OverrideSelector.field_cardinality:type_name -> google.protobuf.Field.Cardinality
	1,  // 2: goplain.TypeOverride.selector:type_name -> goplain.OverrideSelector
	0,  // 3: goplain.TypeOverride.target_go_type:type_name -> goplain.GoIdent
	9,  // 4: goplain.MessageOptions.virtual_fields:type_name -> google.protobuf.Field
	2,  // 5: goplain.FileOptions.go_types_overrides:type_name -> goplain.TypeOverride
	10, // 6: goplain.FileOptions.virtual_types:type_name -> google.protobuf.Type
	0,  // 7: goplain.FieldOptions.override_type:type_name -> goplain.GoIdent
	11, // 8: goplain.file:extendee -> google.protobuf.FileOptions
	12, // 9: goplain.message:extendee -> google.protobuf.MessageOptions
	13, // 10: goplain.field:extendee -> google.protobuf.FieldOptions
	14, // 11: goplain.oneof:extendee -> google.protobuf.OneofOptions
	4,  // 12: goplain.file:type_name -> goplain.FileOptions
	3,  // 13: goplain.message:type_name -> goplain.MessageOptions
	5,  // 14: goplain.field:type_name -> goplain.FieldOptions
	6,  // 15: goplain.oneof:type_name -> goplain.OneofOptions
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	12, // [12:16] is the sub-list for extension type_name
	8,  // [8:12] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_examples_proto_goplain_goplain_proto_init() }
func file_examples_proto_goplain_goplain_proto_init() {
	if File_examples_proto_goplain_goplain_proto != nil {
		return
	}
	file_examples_proto_goplain_goplain_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_proto_goplain_goplain_proto_rawDesc), len(file_examples_proto_goplain_goplain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_examples_proto_goplain_goplain_proto_goTypes,
		DependencyIndexes: file_examples_proto_goplain_goplain_proto_depIdxs,
		MessageInfos:      file_examples_proto_goplain_goplain_proto_msgTypes,
		ExtensionInfos:    file_examples_proto_goplain_goplain_proto_extTypes,
	}.Build()
	File_examples_proto_goplain_goplain_proto = out.File
	file_examples_proto_goplain_goplain_proto_goTypes = nil
	file_examples_proto_goplain_goplain_proto_depIdxs = nil
}
